### ISSUE TITLE
找不到父工程pom，无法正确依赖，这个项目不可用啊

### ISSUE THREAD

**Issue by zhenjia001** [alibaba/jvm-sandbox#1]
<parent>
        <groupId>com.taobao</groupId>
       <artifactId>parent</artifactId>
        <version>1.0.3</version>
找不到父工程pom，无法正确依赖，这个项目不可用啊

**Comment by dongchenxu** [comment]
把 <parent>
        <groupId>com.taobao</groupId>
        <artifactId>parent</artifactId>
        <version>1.0.3</version>
    </parent>注释掉

**Comment by zhenjia001** [comment]
恩，是的，
    
        
        
        
    
这部分实际没有用处，谢谢

**Comment by zhenjia001** [comment]
windows下，jettyServer.start启动后，CoreLauncher进程就停止了，没有异常日志，但是/sandbox请求无法访问，不知道遇到过这种情况吗？用ide调试着怎么搞

**Comment by zhenjia001** [comment]
发现CoreLauncher虽然执行完，但是jetty实际已经启动了，端口在占用了，
但是访问HTTP ERROR: 404了，应该是url不对

Problem accessing /sandbox/module/http/info/version. Reason:

    Not Found
Powered by Jetty://

**Comment by zhenjia001** [comment]
1、spy包为何是java.会编译报错，这是会有二义性
2、AgentLauncher.substringBeforeLast在windows下会有问题
3、AgentLauncher执行时少包问题，修改pom，生成jar

**Comment by dongchenxu** [comment]
Hi 我已经完成了整个工程的更新，请看下是否还有上述反馈的问题？

1. pom的parent已经完成去除
2. 核心API已经提交到maven中央仓库
3. windows下的异常行为请帮忙核对是否仍然存在，我找不到一个windows机器进行测试，非常惭愧

**Comment by zhenjia001** [comment]
前段一直在用greys，发现最近sandbox更新很快，试一下后答复，谢谢
