### ISSUE TITLE
工程代码缺乏可测性要求

### ISSUE THREAD

**Issue by oldmanpushcart** [alibaba/jvm-sandbox#103]
jvm-sandbox的工程代码在很多地方强依赖了`Instrumentation`来完成功能，但这个会导致工程测试用例没办法顺利编写。

需要变更部分工程代码，让整个工程可被测试

**Comment by oldmanpushcart** [comment]
已经在分支上实现[develop-20181012-qatest](https://github.com/alibaba/jvm-sandbox/tree/develop-20181012-qatest)

**Comment by dongchenxu** [comment]
分支已经合并并且发布
