### ISSUE TITLE
使用内部类数组作为方法参数时，方法无法被增强

### ISSUE THREAD

**Issue by Benjar** [alibaba/jvm-sandbox#107]
目标方法如下： test2和test3方法参数中含有一个内部枚举类数组
![wechatimg449](https://user-images.githubusercontent.com/8326387/47540566-6149ea80-d908-11e8-8400-192bb05ab310.jpeg)

rewrite method之前校验方法的signcode不相同，导致该方法无法被重写，增强不生效
![wechatimg445](https://user-images.githubusercontent.com/8326387/47540565-6149ea80-d908-11e8-8a1b-3cd04c84c69e.jpeg)

原因：
com.alibaba.jvm.sandbox.core.util.matcher.structure.ClassStructureImplByJDK#getJavaClassName  
com.alibaba.jvm.sandbox.core.enhance.weaver.asm.EventWeaver#getBehaviorSignCode
处理数组类型的class时逻辑不一致

**Comment by dongchenxu** [comment]
确认是BUG，需要一个比较长的时间进行修复。重点是梳理和重构`ClassStructureImplByAsm`的逻辑和架构。

**Comment by dongchenxu** [comment]
问题已修复，且已补充测试用例
