### ISSUE TITLE
执行ControlModule的shutdown操作后，应用里的sandbox内存对象没有全部清除

### ISSUE THREAD

**Issue by luozhihuan** [alibaba/jvm-sandbox#108]
![image](https://user-images.githubusercontent.com/6283609/47554593-38dbe380-d93c-11e8-815e-aec5a8733967.png)
执行完shutdown后，发现还有sandbox的相关对象在应用中没有清除
源码中ControlModule类cleanSpy()方法会对Spy类的熟悉进行赋值null操作，但没有对非Method的属性进行该操作
![image](https://user-images.githubusercontent.com/6283609/47554687-70e32680-d93c-11e8-87be-ef8240a5be3c.png)
![image](https://user-images.githubusercontent.com/6283609/47554766-a9830000-d93c-11e8-9197-f77c8f1661c1.png)
通过内存分析，也发现该对象进行存活于应用内存中
![image](https://user-images.githubusercontent.com/6283609/47554779-b7388580-d93c-11e8-80fb-2d4bd100b3e1.png)

**Comment by dongchenxu** [comment]
非常感谢指出问题所在，会在下一个版本中修复这个问题

**Comment by dongchenxu** [comment]
经过内存分析，发现内存泄漏的点应该是在卸载时，忘记对`GenericKeyedObjectPool`进行close()了

<img width="921" alt="2018-11-07 10 15 20" src="https://user-images.githubusercontent.com/3461439/48106523-a6f6a380-e276-11e8-816c-ed6f4fa4338c.png">

**Comment by dongchenxu** [comment]
1.2.0版本修复
