### ISSUE TITLE
为什么在设计中使用event pool？

### ISSUE THREAD

**Issue by buzhidaolvtu** [alibaba/jvm-sandbox#112]
研究源代码时，发现使用了apache的GenericKeyedObjectPool，从pool这个概念本身来说，希望达到可以复用资源（资源创建很耗费成本）以及管理资源（超时，最大最小限制等等）的目的，但是spy产生的event为什么要放到这个池子里呢，能达到什么样的效果呢，似乎guava的EventBus的概念更好理解一些，module收到event，sandbox再把event dispatch到各个module里。希望可以解惑。

**Comment by dongchenxu** [comment]
## 使用背景

EventPool使用对象池的期待达到的效果是减少大量Event对象的创建，降低Eden区的压力。

- 随着渲染方法的增多，尤其是如果监听了方法的`Call系列事件`和`Line事件`，都会在方法运行中产生巨量朝生暮死的Event对象。会对Eden区造成压力，YGC/YGCT的指标都会上升。

## 后悔的事

但使用了Apache的GenericKeyedObjectPool是我比较后悔的一件事，因为这个对象池是有锁的，所以会在高并发场景下带来大量的上下文切换开销。如果有好心人能替换成无锁的版本我讲不胜感激。

## 关于EventBus

因为这里需要解决的事是Event对象的临时分配问题，并不需要解决Event对象的分发订阅问题，所以没用EventBus。未来如果有Event在不同模块分发的场景，我可能会引进这个框架。

**Comment by buzhidaolvtu** [comment]
谢谢
