### ISSUE TITLE
EventWatchBuilder支持正则表达式

### ISSUE THREAD

**Issue by oldmanpushcart** [alibaba/jvm-sandbox#115]
**操作环境**

|...|...|
|---|---|
|操作系统|Linux|
|JVM版本|OpenJDK-8.0.5|
|沙箱容器版本|1.1.1|
|沙箱API版本|1.0.16|

**问题描述**

`EventWatchBuilder`的`onClass()`和`onBehavie()`方法目前支持通配符表达式，但通配符表达式在很多场合下没有正则表达式灵活，这里需要直接支持正则表达式的方式。

**重现步骤**

无需重现

**附件（如有）**

在这个环节添加上可能的附件

**Comment by dongchenxu** [comment]
1.2.0版本支持
