### ISSUE TITLE
建议收集好的应用实践

### ISSUE THREAD

**Issue by yiding17** [alibaba/jvm-sandbox#116]
建议收集好的应用实践一起发布，更好的推广工具的落地，谢谢

**操作环境**

|...|...|
|---|---|
|操作系统|Linux|
|JVM版本|OpenJDK-8.0.5|
|沙箱容器版本|1.1.0|
|沙箱API版本|1.0.16|

**问题描述**

简明扼要的描述清楚遇到的问题

**重现步骤**

描述通过怎样的操作重现你的问题和疑惑
1. 第一步
2. 第二步
3. 第三步
4. ...

**附件（如有）**

在这个环节添加上可能的附件

**Comment by dongchenxu** [comment]
很好的提议，我们会将这件事提得更高，实践分享是一个方面，更多方面我们想让大家的模块能有更多的复用，真正实现模块级的复用。

**Comment by fangyuanrui** [comment]
什么时候才有更多的样例参考呀，菜鸟看的有点痛苦

**Comment by dadiyang** [comment]
我建了一个 jvm-sandbox-in-action 项目，里面放一些模块的使用实例，可以参考。
后续有好的实践，我也会持续添加进来，欢迎关注：https://github.com/dadiyang/jvm-sandbox-in-action
