### ISSUE TITLE
ClassStructureImplByAsm性能问题

### ISSUE THREAD

**Issue by haola334** [alibaba/jvm-sandbox#119]
1、ClassStructureImplByAsm中，getJavaClassName、getSuperClassStructure等方法，每次都要重新解析一次字节码，性能消耗很大，加一层cache后，性能有了质的提升。
2、classStructure在实例化后，可以加到一个cache中，这样，不论是在retransform的时候还是程序中获取classStructure时，性能均有质的飞跃（加了这层cache后，原本一个方法执行十几秒，现在几百毫秒就搞定了）。

**Comment by dongchenxu** [comment]
非常感谢！能否提交下代码？

**Comment by haola334** [comment]
sandbox的改造的比较多，就截一下相关的代码吧
![image](https://user-images.githubusercontent.com/1846439/49846148-cd26da80-fe04-11e8-9e49-8683f464c1c1.png)
![image](https://user-images.githubusercontent.com/1846439/49846181-f9daf200-fe04-11e8-8c3f-e326d5f1f13f.png)

**Comment by dongchenxu** [comment]
担心缓存导致一致性问题（Class有可能在运行期变更），暂不采纳方案，不过思路GOT
