### ISSUE TITLE
代码review，返回0.0.0.0:0

### ISSUE THREAD

**Issue by buzhidaolvtu** [alibaba/jvm-sandbox#121]
<img width="695" alt="20181214100714" src="https://user-images.githubusercontent.com/13989168/49979012-0cc9ff80-ff88-11e8-93fb-7ccfc92a99d1.png">
这段代码在如下位置被引用，应该是为了显示版本信息，但是代码中竟然在抛异常的情况下返回了【0.0.0.0:0】，个人认为这段代码是不可理解的：如果恒常返回【0.0.0.0:0】还说的过去，至少全局一致，但是看情况似乎不是。
<img width="1292" alt="20181214101320" src="https://user-images.githubusercontent.com/13989168/49979188-e6589400-ff88-11e8-8216-3652b16ef35b.png">

**Comment by dongchenxu** [comment]
1.2.0版本修复
