### ISSUE TITLE
同时拦截嵌套调用的两个方法出现ClassCastException，子方法中抛出的异常无法触发上级调用者的afterThrowing事件

### ISSUE THREAD

**Issue by zengguoyu** [alibaba/jvm-sandbox#123]
**操作环境**

|...|...|
|---|---|
|操作系统|macOS Mojave 版本10.14.1|
|JVM版本|1.8.0_181|
|沙箱容器版本|1.1.2|
|沙箱API版本|1.1.2|

**问题描述**

如果Sandbox同时拦截ServiceA.sayHello和ServiceB.sayHello方法，并在ServiceB.sayHello的Before事件中抛出 ProcessController.throwsImmediately(new RuntimeException());会导致ClassCastException。

![image](https://user-images.githubusercontent.com/7541266/50411825-2f88cd80-083e-11e9-9508-6b96db5ade37.png)

另外ServiceB.sayHello的before事件中抛出的异常无法触发ServiceA.sayHello的afterThrowing事件。

**重现步骤**

1. 两个服务，在服务A中调用了服务B
```java
package com.demo.app1.service.impl;

import com.demo.app1.service.ServiceA;
import com.demo.app1.service.ServiceB;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ServceAImpl implements ServiceA {
    @Autowired
    private ServiceB serviceB;
    @Override
    public String sayHello(String name) {
        return this.serviceB.sayHello(name);
    }
}

```
```java
package com.demo.app1.service.impl;

import com.demo.app1.service.ServiceB;
import org.springframework.stereotype.Service;

@Service
public class ServceBImpl implements ServiceB {
    @Override
    public String sayHello(String name) {
        return "hello," + name;
    }
}

```
2. 第二步
```java
  eventWatcher = new EventWatchBuilder(this.moduleEventWatcher)
                .onClass("com.demo.app1.service.impl.Servce*")
                .onBehavior("sayHello")
                .onWatch(new AdviceListener() {
                    @Override
                    protected void before(Advice advice) throws Throwable {
                        logger.error("before:" + advice.getTarget().getClass().getName());
                        if ("com.demo.app1.service.impl.ServceBImpl".equals(advice.getTarget().getClass().getName())) {
                            ProcessController.throwsImmediately(new RuntimeException("---------------------------"));
                        }
                    }
                    @Override
                    protected void afterReturning(Advice advice) throws Throwable {
                        logger.error("afterReturning:" + advice.getTarget().getClass().getName());
                    }

                    @Override
                    protected void afterThrowing(Advice advice) throws Throwable {
                        logger.error("afterThrowing:" + advice.getTarget().getClass().getName());
                    }
                });

```
打印的日志
![image](https://user-images.githubusercontent.com/7541266/50411652-c2c10380-083c-11e9-9b06-356aae178d16.png)

sandbox.log日志
![image](https://user-images.githubusercontent.com/7541266/50411666-eb48fd80-083c-11e9-8f8f-91c5b04ef92b.png)

3. 第三步
4. ...

**Comment by dongchenxu** [comment]
@oldmanpushcart 这还用定位，肉眼都看出来，`81行`处理完后，忘记break了！！

**Comment by zengguoyu** [comment]
> @oldmanpushcart 这还用定位，肉眼都看出来，`81行`处理完后，忘记break了！！

@dongchenxu 我们尝试过加上break，可以解决类转换异常，但是在加上后仍不能解决ServiceB.sayHello的before事件中抛出异常被上层调用者SerivceA.sayHello的afterThrowing事件感知。

我这边跟踪了一下，当上面的的情况下出现THROWS_IMMEDIATELY的时候，
![image](https://user-images.githubusercontent.com/7541266/50421916-4996d000-087f-11e9-80f0-9499055ca0c3.png)
invokeId并不是栈顶上的元素，popByExpectInvokeId一直失败。

考虑是维护invokeId的 栈和维护Advice的栈弹出不一致导致！

**Comment by huangzhenren** [comment]
在AdviceListeret的before中，但执行过throwThrowsImmediately以后，也会出现ClassCastException的错误
在公司电脑上运行的，没法截图
最后出错的行：SeparateImmediatelyEventListener 
case STEP_IMMEDIATELY_THROWS_EVENT: {
                final ThrowsEvent throwsEvent = (ThrowsEvent) event;   //这里出错了
                replaceEvent = eventPool.borrowImmediatelyThrowsEvent(throwsEvent.processId, throwsEvent.invokeId, throwsEvent.throwable);
                break;
            }

**Comment by zengguoyu** [comment]
> 已在分支：https://github.com/alibaba/jvm-sandbox/tree/develop-for-20181227 上修复这个问题，可以拉下来进行测试 :)

好的，感谢
