### ISSUE TITLE
Syp.SelfCallBarrier.isEnter数组越界，thread.hashCode()的值为负数

### ISSUE THREAD

**Issue by huangzhenren** [alibaba/jvm-sandbox#126]
**操作环境**

|...|...|
|---|---|
|操作系统|Linux|
|JVM版本|IBMJDK-1.8.0 base on oracle jdk8u71-b15|
|沙箱容器版本|1.1.2|
|沙箱API版本|1.1|.2
|中间件|IBM WAS 8.5.5.9|

**问题描述**

Syp.SelfCallBarrier.boolean isEnter(Thread thread)方法中thread.hashCode()偶尔会取到负数
**重现步骤**
目前是随机性出现，暂时没有发现规律

描述通过怎样的操作重现你的问题和疑惑
1. 第一步
2. 第二步
3. 第三步
4. ...

**附件（如有）**

在这个环节添加上可能的附件

**Comment by huangzhenren** [comment]
![img_20190101_102800_hdr](https://user-images.githubusercontent.com/46289870/50569946-d6c2b300-0db0-11e9-9a83-cfefe84c19f7.jpg)

**Comment by huangzhenren** [comment]
![img_20190101_102800_hdr](https://user-images.githubusercontent.com/46289870/50569950-0376ca80-0db1-11e9-9925-1f51f4c1eadf.jpg)

**Comment by dongchenxu** [comment]
1.2.0版本修复
