### ISSUE TITLE
readme.md 及其子文档的各种描述问题

### ISSUE THREAD

**Issue by FlowBreeze** [alibaba/jvm-sandbox#127]
作为一个刚了解sandbox的编程新手
讲真,这个文档看的我头晕
1.这里(https://github.com/alibaba/jvm-sandbox/wiki/MODULE-DEVELOPER-GUIDE#%E6%81%A2%E5%A4%8D%E8%A2%AB%E4%BF%AE%E5%A4%8D%E7%9A%84check%E6%96%B9%E6%B3%95)
的命令 "./sandbox.sh -p 64229 -d" 应改为 "./sandbox.sh -p 64229 -S"
2.找遍了整个帮助文档和 " bin/sandbox.sh -help" 没有发现任何对于 -d 参数的描述
3.建议将 "- [用户手册](https://github.com/alibaba/jvm-sandbox/wiki/USER-GUIDE)
- [模块研发手册](https://github.com/alibaba/jvm-sandbox/wiki/MODULE-DEVELOPER-GUIDE)
- [模块研发例子](https://github.com/alibaba/jvm-sandbox/wiki/FOR-EXAMPLE)" 中的
"用户手册"重命名 为 "sandbox安装与配置",
"模块研发手册"重命名为"编写入门模块",
"模块研发例子"重命名为"其他模块案例",
或者起码不要全部使用手册进行区分,搞得我当时想看一个简单的案例,最后才点进"模块研发手册",
这名字会让人误以为是项目贡献者需要了解的知识
4.建议补全 api 的介绍,目前尚未看到关于 AdviceListener, LoadCompleted,Sentry... 对象的介绍,希望能通过阅读源码以外的方式理解整个执行过程

**Comment by oldmanpushcart** [comment]
你说的对，逐一改进。欢迎你也来参加哦

**Comment by dongchenxu** [comment]
根据您的建议反馈，我们正在重新组织我们的WIKI文档，欢迎一起参加哦。
