### ISSUE TITLE
[问题]sandbox server是和目标进程公用一个JVM？

### ISSUE THREAD

**Issue by YuhuiFeng** [alibaba/jvm-sandbox#13]
简单的了解了下启动部分，看到jetty的启动是在AgentLauncher里进行的，所以最后外部访问的server是放在目标的JVM里吗？如果是这样，这么做的考量是什么呢？为什么不单独放在外部呢？

如果有理解错的地方，望指正。

**Comment by diecui1202** [comment]
要操纵目标jvm，这个server必须在目标jvm里啊，放在外面，那还得和目标jvm进行通信，目标jvm还得有个server。

**Comment by YuhuiFeng** [comment]
server放在外部的话，JVM里面不用放server啊，简单的一个client做信息发送就好了。在这里我比较关心的是在目标JVM里面在放入一个Jetty会不会对目标JVM原有app有性能上损耗，以及想问问最开始这么设计有没有别的考量。

**Comment by oldmanpushcart** [comment]
jetty对性能的损耗主要集中在对持久代的压力，其他真的还好。

引入jetty的一个主要原因就是为了解决和目标JVM通讯的问题，通讯频率很低，所以不会引起CPU的性能风险。

@YuhuiFeng 的核心观点我猜测应该是：植入的AOP采集到的数据希望和采集中心通讯，此时用一个client即可。但毕竟两者解决的不是同一个问题。

**Comment by dongchenxu** [comment]
楼上说得对！
