### ISSUE TITLE
sandbox在jdk11无法运行

### ISSUE THREAD

**Issue by hezhimin** [alibaba/jvm-sandbox#136]
https://github.com/alibaba/jvm-sandbox/wiki/FIRST-MODULE
安装jdk11后，安装成功sandbox
但是运动命令启动sandbox后会报错。

dingcldeMacBook-Pro:bin dingcl$ ./sandbox.sh -p 12101
错误: 找不到或无法加载主类 
原因: java.lang.ClassNotFoundException: 
attach JVM 12101 fail.

**Comment by dongchenxu** [comment]
目前是的，JDK11刚出来，还没完成对其特性的适配。
BTW，Oracle出东西真快

**Comment by dongchenxu** [comment]
已经在JDK11上完成适配工作
