### ISSUE TITLE
返回值是自定义对象，如何进行替换呢？

### ISSUE THREAD

**Issue by binger1990** [alibaba/jvm-sandbox#142]
想做返回值替换，是自定义对象的话，一般会怎么做呢？
感谢指教～

**Comment by lpl606606** [comment]
兄弟你解决了吗，我在自己的module中写了相同的类，执行时类冲突，你是怎么解决的

**Comment by dadiyang** [comment]
全程反射可以解决。advice.getTarget().getClass().newInstance()

**Comment by dadiyang** [comment]
生成新的返回值实例用这个：advice.getBehavior().getReturnType().newInstance()

**Comment by oldmanpushcart** [comment]
楼上正解

**Comment by binger1990** [comment]
反射就可以解决了呢
