### ISSUE TITLE
建议封装直接invoke方法的api，这样体系更加完善。目前都是事件驱动的。

### ISSUE THREAD

**Issue by skytraveler** [alibaba/jvm-sandbox#148]

**Comment by oldmanpushcart** [comment]
sandbox曾经有过一分支是封装了标准的`aopalliance`的标准API，编码起来确实非常方便。胎死腹中的原因是：**没有足够的精力进行完善和测试**，所以最终一直没有release出来，最后也因为master的改动和分支差异过大而且呼声没有那么高，最终放弃

**Comment by skytraveler** [comment]
got it ，那个分支还在么？也许我能继续往上堆一下。

**Comment by oldmanpushcart** [comment]
@skytraveler 哪个分支最终没有push，非常抱歉 :)
