### ISSUE TITLE
启动sandbox出现错误:attach JVM 进程号 fail,attach lose response 怎么接决？

### ISSUE THREAD

**Issue by lpl606606** [alibaba/jvm-sandbox#149]

**Comment by oldmanpushcart** [comment]
已经在群里回答。

**Comment by tanzanlong** [comment]
请问是怎么解决的？我现在在docker容器里面使用碰到同样的问题。

**Comment by lpl606606** [comment]
一般是目标程序启动用户和当前登录用户名不一致，比如程序a是admin启动，你当前登录用户是user，用user用户attach报错，你可以查看~/.sandbox.token 文件，启动后将端口号放该文件

**Comment by tanzanlong** [comment]
好的，谢谢！ @lpl606606

**Comment by zwrsw** [comment]
请问怎么解决的

**Comment by zwrsw** [comment]
> 一般是目标程序启动用户和当前登录用户名不一致，比如程序a是admin启动，你当前登录用户是user，用user用户attach报错，你可以查看~/.sandbox.token 文件，启动后将端口号放该文件

将什么端口号放在这个文件

**Comment by wongoo** [comment]
解决方案参考：https://github.com/alibaba/jvm-sandbox/pull/185
