### ISSUE TITLE
有没有录制回放的例子？

### ISSUE THREAD

**Issue by fangyuanrui** [alibaba/jvm-sandbox#152]
有没有录制回放的例子？

**Comment by lpl606606** [comment]
同求

**Comment by dadiyang** [comment]
我之前写过一个，不过比较简陋，看看其他人有没有好一点的例子分享，没有的话，我晚点整理一下发一个出来。

**Comment by lpl606606** [comment]
可以，兄弟，你知道在before(Advice advice)改变原来返回值是用ProcessController.returnImmediately(obj)方法吧，还是用什么，我用这个方法没有改变返回值

**Comment by dadiyang** [comment]
在 afterReturning 和 afterThrowing 里面调用试试。before 还没有真正执行方法，还没有返回值。

**Comment by fangyuanrui** [comment]
有个简单的例子参考一下就好
采集大概可以理解怎么做，但是还处于完全搞不定如何回放的阶段

**Comment by dadiyang** [comment]
我这里写了几个模块的实例，其中 time-tunnel 这个模块就是录制和回放的功能实现，可以看一下符不符合你的需求：https://github.com/dadiyang/jvm-sandbox-in-action

**Comment by fangyuanrui** [comment]
有没有系统测试级别的录制回放？单元测试级别的暂时应该不会涉及到链路的唯一标识的匹配回放，主要是这块搞不太明白

**Comment by lpl606606** [comment]
有没有办法能在一个程序执行时加入标识，这个标识用来记录这个程序的完整链路，到程序结束时，各个位置都能取到这个标识？

**Comment by dadiyang** [comment]
建两个全局共享的 ThreadLocal 变量，一个存放标识，一个存放当前栈深度。在所有方法的 before 里查看当前能不能获取到标识，不能则添加。然后栈深度加1。然后在 afterReturn 和 afterThrow 里栈深度减1，当栈深度为0时移除标识。

**Comment by lpl606606** [comment]
你说的是一次调用这段程序，当我连续调用这段程序这样不行

**Comment by dadiyang** [comment]
什么叫连续调用？同一个方法调用多次，你当成链路中的一环？

**Comment by lpl606606** [comment]
就是并发，而且你这个只是记录一个方法的链路，比如我有个程序往队列添加信息，另一边从队列拿消息然后处理，在不同的Thread，而且往队列添加信息一直执行，拿不到返回值，怎么处理

**Comment by dadiyang** [comment]
额。这种要是当成同一个链路，那你得在消息里加个id了。可以在业务代码中的消息加个id，也可以切面中加个Map来存放。
如果你再扩展一下，通过MQ发个消息出去，在其他程序里处理，你也当成同一个链路，只靠AOP框架是无能为力的。

**Comment by lpl606606** [comment]
好的，谢谢

**Comment by lpl606606** [comment]
兄弟，你有没有改变过java.lang包下的返回值，我试着改System.currentTimeMillis()的返回值，加了.onClass("java.lang.System") .includeBootstrap() ,然后sandbox.properties的unsafe.enable=true,在afterReturning执行ProcessController.returnImmediately(111111111)，测试后还是没有改变值，你知道为什么吗

**Comment by dadiyang** [comment]
`public static native long currentTimeMillis();`

sandbox 不支持 native 方法

**Comment by z529192557** [comment]
官方开源的录制回放  https://github.com/alibaba/jvm-sandbox-repeater

**Comment by 1saacYing** [comment]
> 可以，兄弟，你知道在before(Advice advice)改变原来返回值是用ProcessController.returnImmediately(obj)方法吧，还是用什么，我用这个方法没有改变返回值

这个问题有解决吗？
