### ISSUE TITLE
有同学反馈原声的EventListener很难用

### ISSUE THREAD

**Issue by dongchenxu** [alibaba/jvm-sandbox#16]
集中在

1. 并发场景需要处理
2. `ReturnEvent`需要拿到`BeforeEvent`中的信息需要处理
3. 各种Event是事件池管控，如若处理不当会引起Event污染的问题

JVM-SANDBOX暴露出`EventListener`是出于性能上的考虑，所以这个原生的Listener仍然还会留着，只是提供给对性能非常敏感的场景下进行高级使用。

另外将会提供出更多便于使用的封装API给大家

**Comment by oldmanpushcart** [comment]
已经在1.0.14版本解决
