### ISSUE TITLE
Advice中获取ClassLoader很麻烦

### ISSUE THREAD

**Issue by oldmanpushcart** [alibaba/jvm-sandbox#161]
在现有的Advice中获取ClassLoader非常麻烦，必须

```java
final Class<?> classOfHttpServletResponse = advice.getBehavior()
    .getDeclaringClass()
    .getClassLoader()
    .loadClass("javax.servlet.http.HttpServletResponse");
```

但ClassLoader一直都在，所以希望Advice能Release出获取ClassLoader的方法

**Comment by dadiyang** [comment]
```java
```

**Comment by dadiyang** [comment]
直接在 Advice 对象添加这个方法，可以不？  
 /**
     * 获取目标对象的类加载器
     *
     * @return 目标对象的类加载器
     */
    public ClassLoader getTargetClassLoader() {
        return target.getClass().getClassLoader();
    }

**Comment by oldmanpushcart** [comment]
1.2.2版本解决
