### ISSUE TITLE
如何拦截System.currentTimeMillis方法

### ISSUE THREAD

**Issue by flyheart** [alibaba/jvm-sandbox#165]
请教如何拦截System.currentTimeMillis方法。
下面的代码不生效，没有起到拦截效果
``` Java
new EventWatchBuilder(moduleEventWatcher)
                .onClass("java.lang.System")
                .isIncludeBootstrap(true)
                .isIncludeSubClasses(false)
                .withAccess(AccessFlags.ACF_PUBLIC)
                .withAccess(AccessFlags.ACF_STATIC)
                .withAccess(AccessFlags.ACF_NATIVE)
                .onBehavior("currentTimeMillis")
                .onWatch(new AdviceListener() {
                    @Override
                    protected void before(Advice advice) throws Throwable {
                        ProcessController.returnImmediately(1555309211000l);
                    }
                });
```

sandbox 信息:
>
                     NAMESPACE : default
                      VERSION : 1.2.1
                         MODE : ATTACH
                  SERVER_ADDR : 0.0.0.0
                  SERVER_PORT : 59052
               UNSAFE_SUPPORT : ENABLE
                 SANDBOX_HOME : /Users/xxx/Downloads/sandbox/bin/..
            SYSTEM_MODULE_LIB : /Users/xxx/Downloads/sandbox/bin/../module
              USER_MODULE_LIB : /Users/xxx/Downloads/sandbox/sandbox-module;~/.sandbox-module;
          SYSTEM_PROVIDER_LIB : /Users/xxx/Downloads/sandbox/bin/../provider
           EVENT_POOL_SUPPORT : DISABLE

**Comment by dadiyang** [comment]
System.currentTimeMillis 是 native 方法。目前 sandbox 不支持 native 方法。

**Comment by flyheart** [comment]
好的。多谢。请问有什么办法可以去改变当前线程的时间吗？ @dadiyang

**Comment by dadiyang** [comment]
"当前线程的时间" 是特指 System.currentTimeMillis 吗？

**Comment by flyheart** [comment]
嗯，是的 @dadiyang

**Comment by dadiyang** [comment]
我这暂时无解。不知道其他人有没有办法。可以参考下这个：
https://stackoverflow.com/questions/20472304/bytecode-instrumentation-to-native-java-functions

**Comment by flyheart** [comment]
好的，谢谢。 @dadiyang

**Comment by CoconutLoveCoffee** [comment]
新版已经支持：

**Comment by CoconutLoveCoffee** [comment]
新版已经支持：

**Comment by CoconutLoveCoffee** [comment]
新版已经支持，可以支持 native 方法增强 例如：System.currentTimeMillis的增强
实测环境：jdk1.8.0_351，jvm-sandbox1.4.0
使用以下方式监听：

>       
             new EventWatchBuilder(moduleEventWatcher)
                .onClass("java.lang.System")
                .includeBootstrap()
                .onBehavior("currentTimeMillis")
                .onWatch(new AdviceListener() {
                    @Override
                    protected void before(Advice advice) throws Throwable {
                        ProcessController.returnImmediately(1697782952000L);
                    }
                });

Note:
    1.com.alibaba.jvm.sandbox.core.JvmSandbox#isNativeSupported   是否支持native是由代码逻辑计算，无法外部配置
    2.如果拦截失效，目标jvm启动加上-XX:+UnlockDiagnosticVMOptions -XX:CompileCommand=dontinline,java.lang.System::currentTimeMillis -XX:DisableIntrinsic=_currentTimeMillis
    3.jdk环境仅支持oracle-jdk-[1.8,12]

**Comment by huangsir1** [comment]
上面说的都做了，就是公司用的openjdk，没生效
