### ISSUE TITLE
DebugWatchModule使用writer打印中文乱码

### ISSUE THREAD

**Issue by shimine** [alibaba/jvm-sandbox#167]
测试DebugWatchModule模块时发现中文在终端打印成问号。
查了下
com/alibaba/jvm/sandbox/core/server/jetty/servlet/ModuleHttpServlet.java里doGet方法的入参resp编码类型为默认的ISO-8859-1
导致对应的PrintWriter的编码也是ISO-8859-1。
建议修改为使用较多的UTF-8。 
改成如下测试中文额已可正常显示

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setCharacterEncoding("UTF-8");
        doMethod(req, resp, Http.Method.GET);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setCharacterEncoding("UTF-8");
        doMethod(req, resp, Http.Method.POST);
    }

改动很小就不提pr了。如果没有带来其他负面影响建议下个版本合入

**Comment by oldmanpushcart** [comment]
收到我尽量考虑下设计为可配置的

**Comment by oldmanpushcart** [comment]
在1.2.2版本解决
