### ISSUE TITLE
如何调试module本身？

### ISSUE THREAD

**Issue by fangyuanrui** [alibaba/jvm-sandbox#169]
现在只能挂载了自己打日志看，不指定怎么debug module本身的代码

**Comment by fangyuanrui** [comment]
不知道怎么debug module本身的代码

**Comment by dadiyang** [comment]
我用 IDEA，在目标项目的 maven projects 面板中将 module 添加进来，然后启动目标项目再开启 sandbox 之后，在 module 中打的断点就生效可以调试了。

<img width="312" alt="image" src="https://user-images.githubusercontent.com/28141217/56354043-662b8f00-6205-11e9-97e8-120b8bffeb7b.png">

**Comment by shaozhengmao** [comment]
https://github.com/oldmanpushcart/greys-anatomy/issues/96
可参考

**Comment by wentiegang** [comment]
> 我用 IDEA，在目标项目的 maven projects 面板中将 module 添加进来，然后启动目标项目再开启 sandbox 之后，在 module 中打的断点就生效可以调试了。
> 
> <img alt="image" width="312" src="https://user-images.githubusercontent.com/28141217/56354043-662b8f00-6205-11e9-97e8-120b8bffeb7b.png">

请问目标项目需要debug模式启动吗？为什么我debug启动目标项目后再开启sandbox，目标项目异常退出了
