### ISSUE TITLE
提个建议：用微信群交流是不是更方便呢？

### ISSUE THREAD

**Issue by albon** [alibaba/jvm-sandbox#17]
谢谢！

**Comment by jacarrichan** [comment]
用qq也不错

**Comment by dongchenxu** [comment]
尝试过微信群，但微信的群二维码只有7天有效期，不利于把入群二维码挂在网站上和大家一起交流。

平时在阿里工作，用钉钉比较多，微信偏向于私人生活，QQ基本上都比较少用了（尤其是QQ，已经万年不开了）

所以，处于回复效率的考虑，优先钉钉哈。后续人如果确实太多了，我会考虑用QQ群。

**Comment by nimeijian** [comment]
钉钉群又打不开了，jvm-sandbox-repeater的钉钉群也打不开，可以再开一个钉钉群吗？
