### ISSUE TITLE
应用启动失败后，进程无法正常退出

### ISSUE THREAD

**Issue by wangmingxiang** [alibaba/jvm-sandbox#172]
**操作环境**

|...|...|
|---|---|
|操作系统|Windows 10|
|JVM版本|Oracle JDK 1.8.0_131|
|沙箱容器版本|1.2.0|
|沙箱API版本|1.2.0|

**问题描述**
sandbox 1.2.0版本，应用启动失败后，应用进程无法正常退出

**重现步骤**
1. 下载1.2.0版本的sandbox包
2. 指定javaagent启动参数
3. 应用启动失败后进程未退出

相关代码如下：
加入启动参数```-javaagent:your_sandbox_agent_path/sandbox-agent.jar```
```
public static void main(String[] args) {
    throw new RuntimeException();
}
```
应用抛出异常后，进程未正常退出

**Comment by oldmanpushcart** [comment]
1.2.2版本解决，多谢提交的PR
