### ISSUE TITLE
flush/shutdown后，不会回收堆外内存中的ClassLoader

### ISSUE THREAD

**Issue by link-nj** [alibaba/jvm-sandbox#174]
**操作环境**
... | ...
-- | --
操作系统 | Linux
JVM版本 | JDK 1.8.0_131
沙箱容器版本 | 1.2.0

**问题描述**
flush或shutdown命令后，服务的classloader数量不会下降，多次flush后，堆外内存持续增加最终导致OOM
![image](https://user-images.githubusercontent.com/20139095/56795234-9812a600-6842-11e9-9383-709ae053369d.png)

**重现步骤**
1. attach应用
2. flush/shutdown
3. 重复步骤1/2

**Comment by oldmanpushcart** [comment]
请问是否有挂载自己的研发模块呢？sandbox自带的那几个模块我们都测试过，是会回收

**Comment by link-nj** [comment]
> 请问是否有挂载自己的研发模块呢？sandbox自带的那几个模块我们都测试过，是会回收

issue中的截图是挂载了自己研发的模块。也试过只有自带模块的，在shutdown之后，classloader和堆外内存仍然会有一定的增长无法回收
PS: shutdown后，使用jmap查看内存，也会有一些sandbox的类
![image](https://user-images.githubusercontent.com/20139095/57205335-97230680-6ff0-11e9-9f39-80f5479162ea.png)

**Comment by oldmanpushcart** [comment]
如果是自研的模块这个我不能保证，但如果是沙箱自带的模块，都是经过我们严格测试过的，都是可以回收掉的 :)

**Comment by sanxun0325** [comment]
使用文档中的clock demo 也发现此问题

**Comment by Ken199416** [comment]
从官网下载的module，没做任何修改，直接开启之后，再关闭，发现没有被回收，而且关闭之后再开启，又重新加载了一遍，重启多少次就会新加载多少类，时间长导致metespace的空间占用越来越高

**Comment by Ken199416** [comment]
> 使用文档中的clock demo 也发现此问题

貌似fullGC之后就会被回收掉了
