### ISSUE TITLE
为什么要将Spy类注入到BootStrapClassLoader里？

### ISSUE THREAD

**Issue by Yuanxiangz** [alibaba/jvm-sandbox#175]
// 将Spy注入到BootstrapClassLoader
            inst.appendToBootstrapClassLoaderSearch(new JarFile(new File(
                    getSandboxSpyJarPath(getSandboxHome(featureMap))

我最近正在看sandbox的代码，如上代码比较困惑。从代码里我看到对Spy类相应方法的绑定操作都是在SandboxClassLoader加载的相关类里操作的，AppClassLoader加载的类根本不会去查找Spy类，为什么不用SandboxClassLoader来加载Spy？这样卸载的时候Spy类也不会残留在目标应用里了

**Comment by Yuanxiangz** [comment]
Arthas的代码我也看过，也是同样将Spy类注入到了BootstrapClassLoader。Arthas跟sandbox不同的是AgentBootstrap会依赖Spy类（参考sandbox的用法这是没有必要的），所以必须将Spy类注入到BootstrapClassLoader里这样ArthasClassLoader才能找到它。

**Comment by Yuanxiangz** [comment]
Arthas的代码我也看过，也是同样将Spy类注入到了BootstrapClassLoader。Arthas跟sandbox不同的是AgentBootstrap（agentmain所在的类）会依赖Spy类（参考sandbox的用法这是没有必要的），所以必须将Spy类注入到BootstrapClassLoader里这样ArthasClassLoader才能找到它。

**Comment by Yuanxiangz** [comment]
刚反编译了一下sandbox增强的类，发现里面有添加的代码会调用Spy类相应的方法，这应该就是为什么Spy需要注入到BootStrapClassloader里的原因了

**Comment by oldmanpushcart** [comment]
U ARE RIGHT
