### ISSUE TITLE
Unable to access jarfile  in cygwin

### ISSUE THREAD

**Issue by xsllvip** [alibaba/jvm-sandbox#176]
sh sandbox.sh -p 18796
Error: Unable to access jarfile /cygdrive/c/sandbox-stable-bin/sandbox/bin/../lib/sandbox-core.jar
attach JVM 18796 fail.

**Comment by oldmanpushcart** [comment]
cygwin的环境没有试过，1.2.2我merge了别人贡献的代码，你可以再试试
