### ISSUE TITLE
请问怎么拿子调用的返回值呢

### ISSUE THREAD

**Issue by xj81** [alibaba/jvm-sandbox#178]
watch 一个class 里的某一个method，想要获取在这个方法调用链路中各个其他方法的返回值，afterCallReturning下，advice.getReturnObj()拿到的全是 null 。 怎么样才能拿到这些过程中子调用的返回值呢？是需要一个个子调用的class 去通过watch，然后通过 子调用method 的afterReturning 来获取返回值么？

**Comment by lpl606606** [comment]
兄弟，可以参考arthas的issue[#597](https://github.com/alibaba/arthas/issues/597)，他俩很像，要想拿到全部，可以用通配符或正则表达式匹配你关注包下的类和方法

**Comment by xj81** [comment]
谢谢

**Comment by wupflove** [comment]
> 兄弟，可以参考arthas的issue[#597](https://github.com/alibaba/arthas/issues/597)，他俩很像，要想拿到全部，可以用通配符或正则表达式匹配你关注包下的类和方法

这个是要已知调用关系的情况下，如果未知调用关系呢？
