### ISSUE TITLE
sandbox提供一个统一管理的配置文件

### ISSUE THREAD

**Issue by lpl606606** [alibaba/jvm-sandbox#179]
sandbox可不可以提供一个统一的配置文件，用sandbox的cfg的sandbox.properties也行，在sandbox-api中提供获取配置文件的接口，这样自定义的module都可以从哪里获取，不用每个module都加，既能够让自定义modole拿到sandbox的一些配置，而且还能减少冗余的配置

**Comment by zhaoyb1990** [comment]
如果模块需要拿sandbox的配置文件，可以在module中增加

**Comment by oldmanpushcart** [comment]
先简单的用吧，这个需求保持观望。其实多个模块要共享的内容还不只是配置。目前我们的方案是每个module都自己去拿自己的配置，封装好工具类即可。
