### ISSUE TITLE
钉钉群为啥不能加？

### ISSUE THREAD

**Issue by lvzeting** [alibaba/jvm-sandbox#18]

**Comment by dongchenxu** [comment]
可以的哦，是用[钉钉](https://www.dingtalk.com)这个聊天工具扫描图片
![](https://github.com/alibaba/jvm-sandbox/wiki/img/dingding_card.png)

我平时工作用钉钉比较多，微信比较少看～

**Comment by dongchenxu** [comment]
知道原因了 #24 中反馈，这个群被群主设置为不可被外部搜索到。已经重新设置了，非常抱歉
