### ISSUE TITLE
root can't attach jvm starting by other user

### ISSUE THREAD

**Issue by wongoo** [alibaba/jvm-sandbox#184]
sandbox can only attach jvm success when the jvm is started by the same user who starting sandbox. Although starting sandbox.sh using same user can fix the problem, I think sandbox.sh should support attach jvm for different user, especially for root user. 

The following show starting sandbox.sh using other user, you need to find the target user first, which is a boring step:
 ```
> PID=1234
> JVM_USER=$(ps -ef |grep $PID | awk '{printf $1}')
> su - $JVM_USER -c "/path/bin/sandbox.sh -p $PID"
```

I will submit a PR for it.

**Comment by oldmanpushcart** [comment]
thank you
