### ISSUE TITLE
tomcat agent方式启动module抛异常找不到类

### ISSUE THREAD

**Issue by a13794479495** [alibaba/jvm-sandbox#187]
场景：
想通过agent的module方式实现一个AOP，用来拦截mybatis的类完成动态修改sql（同mybatis插件功能）

环境：
目标项目为springmvc项目
项目构建：maven
容器tomcat8.0
mybatis 3.4.6

问题
module中引入mybatis 3.4.6，scope为provided，核心代码如下：
![image](https://user-images.githubusercontent.com/18589654/60014984-e3b3c580-96b4-11e9-99c5-06d27b23da83.png)

![image](https://user-images.githubusercontent.com/18589654/60014963-d0085f00-96b4-11e9-801a-4507f0a3401e.png)

目标项目使用tomcat启动后，sandbox日志出现如下错误：
![image](https://user-images.githubusercontent.com/18589654/60015024-ff1ed080-96b4-11e9-9ecb-d80fd6181ea0.png)

换了一个springboot项目尝试，项目启动正常且module功能正常，
应该是独立tomcat容器的类加载与springboot类加载机制不一样造成以上差别。

期望结果
tomcat附带sandbox agent启动不报错，并且以上module功能正常

**Comment by oldmanpushcart** [comment]
你模块的代码缺少类导致无法完成模块SPI加载，这个和jvm-sandbox、springboot、tomcat应该没有关系才对。但我也挺好奇用springboot启动的时候竟然没有报错，可以用arthas来看看这个类到底是从那个ClassLoader加载进来的。
