### ISSUE TITLE
不同namespace多个agent启动不指定home路径获取问题

### ISSUE THREAD

**Issue by zhaoyb1990** [alibaba/jvm-sandbox#188]
### 问题描述：

不同namespace多个agent启动不指定home路径获取问题，sandbox主目录只使用第一个agent的路径

### 问题原因：

代码片段：
```java
private static final String DEFAULT_SANDBOX_HOME
            = new File(AgentLauncher.class.getProtectionDomain().getCodeSource().getLocation().getFile())
            .getParentFile()
            .getParent();
```

agent启动时使用了appClassLoader，AgentLauncher.class只加载一次，所以这里拿到的始终是第一个agent的位置

### 解决方案：

暂无

**Comment by oldmanpushcart** [comment]
你可以在agent启动方式中，指定home的配置，DEFAULT_SANDBOX_HOME是只有在你没有指定home的时候采用的默认值
