### ISSUE TITLE
请问为什么不允许增强main方法

### ISSUE THREAD

**Issue by yelaixiang2581** [alibaba/jvm-sandbox#190]
另外：
UnsupportedMatcher.isStealthClass/isFromStealthClassLoader
这2个方法判断是否是隐形类是不是得使用classStructure.getFamilyAnnotationTypeClassStructures()。

**Comment by oldmanpushcart** [comment]
1. 不允许增强main方法，是因为增强main方法没有意义。大多数应用默认main方法有且只能执行一次。
1. 确实应该是getFamilyAnnotationTypeClassStructures()，多谢指正！我会在1.2.2版本中解决这个问题
