### ISSUE TITLE
LineEvent是否考虑返回当前行有效的局部变量对象列表

### ISSUE THREAD

**Issue by SevenPlusPlus** [alibaba/jvm-sandbox#191]
我们在做一个java应用远程调试项目，需要录制局部变量的变化过程，用于回放模拟调试，是否考虑支持？

**Comment by SevenPlusPlus** [comment]
类似这样对行断点增强如下：
public static void spyMethodOnLineExt(final int lineNumber,
                                             final String namespace,
                                             final int listenerId,
                                             final Object target,
                                             final Object[] argumentArray,
                                             final Object[] localVariables) throws Throwable

**Comment by oldmanpushcart** [comment]
啊，要来做啥？
