### ISSUE TITLE
EventProcessor.ProcessRef 该ThreadLocal 在两种情况下存在泄露，导致shutdown回收不掉sandbox的Classloader，造成MetaSpace空间内存泄露

### ISSUE THREAD

**Issue by z529192557** [alibaba/jvm-sandbox#194]
情况一：使用了ProcessControl 特性，shutdown无法释放SandboxClassLoader
分析：
EventListenerHandlers.handleEvent中的 
catch (ProcessControlException pce) { 
final EventProcessor.Process process = processor.processRef.get();
....}
此处的  processor.processRef 很可能在 EventListenerHandlers.handleOnEnd 的方法中，已经被释放掉，此处的get会导致重新初始化且后续无释放

一个空Process 对象放在ThreadLocal中，导致使用了ProcessControl 特性且复用线程的的应用，ThreadLocal始终存在没有释放的Process，shutdown导致Classloader泄露

情况二：
被切的方法存在阻塞方法或方法执行时间较长，在阻塞或方法自身执行的的过程中，shutdown会导致processor.processRef 无法释放，并发分析图如下
![并发分析](https://user-images.githubusercontent.com/9245774/60779637-0c849200-a16e-11e9-9636-df463235fcab.png)

**Comment by z529192557** [comment]
情况一：建议修改方案：
catch (ProcessControlException pce) {
...
//return 前检查 局部变量EventProcessor.Process process，process的栈空时释放对方
}
情况二：建议修改方案：
EventProcessor 内部由状态变量和读写锁保护 释放/运行并发的情况，
状态变量作用：标记EventProcessor正在被冻结，阻止新的用户线程使用EventProcessor
读写锁：冻结操作要等所有当前正在操作EventProcessor用户线程退出

**Comment by z529192557** [comment]
情况一：使用了ProcessControl 特性，shutdown无法释放SandboxClassLoader
1. 启动官方Clock例子
2.挂载sandbox
3.执行表修复脚本
- 在Clock例子中打上断点,为了加快gc，在代码里主动加了System.gc
![image](https://user-images.githubusercontent.com/9245774/61269949-ba2d1c00-a7d2-11e9-84af-04cf60c4d7a4.png)
- 检查当前线程本地变量，发现有Sandbox的类
![image](https://user-images.githubusercontent.com/9245774/61270029-ffe9e480-a7d2-11e9-918a-70aa1070d529.png)
-此时，代码已经走到sandbox未增强的指令中（断点处非checkstate方法），大胆猜测此时发生shutdown，不会释放用户线程中的EventProcessor$Prcocess
4.恢复执行，执行shutdown
 - 断点后检查shutdown遗留的类
![image](https://user-images.githubusercontent.com/9245774/61270113-3de70880-a7d3-11e9-8b1c-3e1b0fd02818.png)
 - 检查当前线程本地变量
![image](https://user-images.githubusercontent.com/9245774/61270148-55be8c80-a7d3-11e9-8cf3-7be2a2b4171b.png)
 - 基本认为是线程本地变量发生了泄露

5.验证思想1
 - shutdown后在用户代码中暴力清理线程本地变量
![暴力清理](https://user-images.githubusercontent.com/9245774/61269624-c5cc1300-a7d1-11e9-8e9c-e2a2ddfbb5c8.png)
- 重复1-4的流程，检查遗留的类,可以看到基本清理干净
![image](https://user-images.githubusercontent.com/9245774/61269873-79350780-a7d2-11e9-8dda-38a7e8db4f24.png)

**Comment by oldmanpushcart** [comment]
必须给你点个赞，看得非常仔细！跟着代码和你说的场景，我仔细思考了下，的确是会出现你说的情况导致ThreadLocal泄漏，让Sandbox无法被卸载！

**Comment by dongchenxu** [comment]
这次发布我暂时先不修复这个问题，需要更详细的讨论方案

**Comment by xl1605368195** [comment]
修复方案不错，赞一个👍👍

**Comment by xl1605368195** [comment]
经过反复测试，上诉修复方案，仍然有内存泄漏，泄漏代码如下：
![image](https://user-images.githubusercontent.com/26989019/143021145-81cf09ec-529a-4a21-ba2d-07a92ceab684.png)
代码分析：
1）如果当前线程的 process 已经被清除了，这里再次 get 会往当前线程copy一个新的线程变量，造成内存泄漏
修复方案：
2） 在第二处判断获取的 process.isEmptyStack()成立时，应当清楚现场变量

**Comment by oldmanpushcart** [comment]
@xl1605368195 在分支 [develop-for-20220822](https://github.com/alibaba/jvm-sandbox/tree/develop-for-20220822)中解决
