### ISSUE TITLE
请问支持并发吗?

### ISSUE THREAD

**Issue by YouDianLengDeXiaoHuoZi** [alibaba/jvm-sandbox#196]
比如说监听一个线上服务的方法，多个用户先后访问了该方法，可以通过IP或者别的方式进行用户的区分吗？

**Comment by z529192557** [comment]
无状态的，支持并发，根据IP或其他方式区分是属于使用方法的范围

**Comment by YouDianLengDeXiaoHuoZi** [comment]
谢谢回复！还是不太清楚。。我的需求是想获取一个业务流程中涉及到的代码行号，但是如果多个IP同时操作的话会导入不是该业务流程的信息。我想请问用什么方法可以把无效信息清除出去？

**Comment by oldmanpushcart** [comment]
可以找到对应业务的processId，一个线程一次完整的请求，他的processId都是一样的
