### ISSUE TITLE
遇到的问题

### ISSUE THREAD

**Issue by zhenjia001** [alibaba/jvm-sandbox#2]

**Comment by zhenjia001** [comment]
windows下，jettyServer.start启动后，CoreLauncher进程就停止了，没有异常日志，但是/sandbox请求无法访问，不知道遇到过这种情况吗？用ide调试着怎么搞
 @zhenjia001
     
zhenjia001 commented Nov 14, 2017
发现CoreLauncher虽然执行完，但是jetty实际已经启动了，端口在占用了，
但是访问HTTP ERROR: 404了，应该是url不对，正确的url是啥，看module加入servlet这部分开着晕啊

Problem accessing /sandbox/module/http/info/version. Reason:

Not Found
Powered by Jetty://
 @zhenjia001
     
zhenjia001 commented Nov 14, 2017
1、spy包为何是java.会编译报错，这是会有二义性
2、AgentLauncher.substringBeforeLast在windows下会有问题
3、AgentLauncher执行时少包问题，修改pom，生成jar

**Comment by zhenjia001** [comment]
agentmain代理调用的方式，如何能使用ide进行单步调试啊？很苦恼

**Comment by dongchenxu** [comment]
HI，抱歉这两天在忙上传中央仓库以及写WIKI的事情，没有及时回复你的问题。

不知道这篇[用户手册](https://github.com/alibaba/jvm-sandbox/wiki/USER-GUIDE)是否能帮助到你，如果仍然不行，可以加群，我们直接沟通下？
