### ISSUE TITLE
SelfCallBarrier#delete(Node node)

### ISSUE THREAD

**Issue by caoenergy** [alibaba/jvm-sandbox#20]
节点删除后，虽然没有外部引用它，但它却引用了top节点和next节点，虽然可被回收，但相对gc不友好，
不知道理解的对不对?

**Comment by dongchenxu** [comment]
嗯嗯，这位大兄弟说得很对，这个细节我没注意到，的确会对GC不友好。劳烦提个PR，我merge上来，下个版本弄掉哦～
