### ISSUE TITLE
sandbox-1.2.0版本中使用@Command注解不生效

### ISSUE THREAD

**Issue by infra-qa** [alibaba/jvm-sandbox#200]
在sandbox-1.2.0中使用@Command注解时，在调用时报错信息如下：
`./sandbox.sh -p 11502 -d 'my-sandbox-module/addLog'
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /sandbox/default/module/http/my-sandbox-module/addLog. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
                                                                                              
</body>
</html>
`

如果将@Command换成@Http（其它什么都不变），则正常，代码如下；

`package com.nucc;

import com.alibaba.jvm.sandbox.api.Information;
import com.alibaba.jvm.sandbox.api.Module;
import com.alibaba.jvm.sandbox.api.ModuleLifecycle;
import com.alibaba.jvm.sandbox.api.annotation.Command;
import com.alibaba.jvm.sandbox.api.http.Http;
import com.alibaba.jvm.sandbox.api.listener.ext.Advice;
import com.alibaba.jvm.sandbox.api.listener.ext.AdviceListener;
import com.alibaba.jvm.sandbox.api.listener.ext.EventWatchBuilder;
import com.alibaba.jvm.sandbox.api.resource.ModuleEventWatcher;
import org.kohsuke.MetaInfServices;

import javax.annotation.Resource;
import java.util.logging.Logger;

@MetaInfServices(Module.class)
@Information(id = "my-sandbox-module", version = "1.0.0", author = "maliang")
public class TestSandBoxModule implements Module {

    private Logger LOG = Logger.getLogger(TestSandBoxModule.class.getName());

    @Resource
    private ModuleEventWatcher moduleEventWatcher;

    //@Command("/addLog")
    @Http("/addLog")
    public void addLog() {
        new EventWatchBuilder(moduleEventWatcher)
                .onClass("com.example.quickstart2.service.impl.SimpleServiceImpl")
                .onBehavior("simle")
                .onWatch(new AdviceListener() {

                    @Override
                    protected void before(Advice advice) throws Throwable {
                        System.out.println(" before...方法名: " + advice.getBehavior().getName());
                    }

                    @Override
                    protected void afterReturning(Advice advice) throws Throwable {
                        System.out.println(" after...方法名: " + advice.getBehavior().getName());
                    }

                    ;
                });
    }

}
`

**Comment by dadiyang** [comment]
@Http("/addLog") 
应该改成
@Command("addLog")
重点在于这个 /
Http注解有 / Command 注解不能用 /

**Comment by infra-qa** [comment]
感谢@dadiyang，该细节确实没有注意到；

**Comment by infra-qa** [comment]
#
