### ISSUE TITLE
bug: AdviceAdapterListener里调用了clazz.getDeclaredMethods()方法导致异常

### ISSUE THREAD

**Issue by hust419** [alibaba/jvm-sandbox#202]
AdviceAdapterListener里调用了clazz.getDeclaredMethods()，
像logback的logger.java这个类里面的log方法，    public void log(org.slf4j.event.LoggingEvent slf4jEvent) {} 
由于低版本的slf4j里面是没有这个类，导致调用抛异常，无法正常工作。

	
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.12</version>
		</dependency>

这个版本的slf4j配合logback使用，如果增强logger.java这个类，就会出现问题

**Comment by oldmanpushcart** [comment]
能给我看下异常堆栈么？
