### ISSUE TITLE
maven-gpg-plugin插件能否从POM文件中去除？

### ISSUE THREAD

**Issue by AlexRenCN** [alibaba/jvm-sandbox#204]
第一次手动编写该项目，根据[修复损坏的钟](https://github.com/alibaba/jvm-sandbox/wiki/FIRST-MODULE)进行编写用例的时候，在打包过程中发生了异常，错误提示异常发生在gpg插件，了解这个插件之后发现我们平时并不需要这个功能，也没有配置签名，所以在打包时期会发生异常，相信我这样的情况不是个例，该插件是必须存在的么？这回打乱我们项目的maven配置，成本过高，目前我通过在项目中重写关闭了该插件：

```xml
   <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-gpg-plugin</artifactId>
                    <version>1.5</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
```

能否在pom中移除这个插件交给实现者去自己决定呢？
部分报错如下：

```text
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ baldhead ---
/bin/sh: gpg: command not found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.572 s
[INFO] Finished at: 2019-07-31T19:44:00+08:00
[INFO] Final Memory: 22M/311M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project {projectname}: Exit code: 127 -> [Help 1]
```

**Comment by oldmanpushcart** [comment]
不能，你也不应该用我这个工程打包啊？！

**Comment by AlexRenCN** [comment]
> 不能，你也不应该用我这个工程打包啊？！

hi～sandbox-module-starter这个模块是做什么的？你们的官方文档里是这么描述的
`
编写一个模块修复损坏的钟

创建一个Java工程clock-tinker

假设用的是MAVEN，这里通过将parent指向sandbox-module-starter来简化我们的配置工作

<parent>
    <groupId>com.alibaba.jvm.sandbox</groupId>
    <artifactId>sandbox-module-starter</artifactId>
    <version>1.2.0</version>
</parent> 
`
如果这个不是对外提供的包，那写自定义插件pom应该如何定义呢？

**Comment by oldmanpushcart** [comment]
@AlexRenCN Hi, sandbox-module-starter的用法可以在这个wiki中看到哦

https://github.com/alibaba/jvm-sandbox/wiki/FIRST-MODULE

假设用的是MAVEN，这里通过将parent指向sandbox-module-starter来简化我们的配置工作

``` xml
<parent>
    <groupId>com.alibaba.jvm.sandbox</groupId>
    <artifactId>sandbox-module-starter</artifactId>
    <version>1.2.0</version>
</parent> 
```

**Comment by AlexRenCN** [comment]
> @AlexRenCN Hi, sandbox-module-starter的用法可以在这个wiki中看到哦
> 
> https://github.com/alibaba/jvm-sandbox/wiki/FIRST-MODULE
> 
> 假设用的是MAVEN，这里通过将parent指向sandbox-module-starter来简化我们的配置工作
> 
> ```
> <parent>
>     <groupId>com.alibaba.jvm.sandbox</groupId>
>     <artifactId>sandbox-module-starter</artifactId>
>     <version>1.2.0</version>
> </parent> 
> ```

这就是我奇怪的地方，我自己写了一个module并且已经部署在测试环境了，用的也是你说的这种方法，但是我不得不在maven中添加一个plugins，将gpg插件配置覆盖掉，既然对外提供了，是不是应该在这个父pom里去掉这个插件，现在这种方式其实不是很友好。
