### ISSUE TITLE
支持 Native 方法的增强

### ISSUE THREAD

**Issue by z3tta** [alibaba/jvm-sandbox#208]
应用场景：研究程序中变量之间的传递关系，有时候会涉及一些 Native 调用，比如 System.arraycopy() 等。
目前测试结果来看 jvm-sandbox 不支持 Native 方法的增强，所以在上述场景下只能在 Native 调用的上一层进行增强。但此方案过于依赖人工梳理，而代码的多样性使得其并不能保证穷举所有涉及 Native 方法的上层调用，增强的方法数量上也无法收敛。
此种场景是否考虑予以支持？

**Comment by dongchenxu** [comment]
当前JVM-SANDBOX的技术选型无法让我支持native的方法，这个先挂起，未来我们会考虑改动架构
