### ISSUE TITLE
Enhance the performance of handling with each event

### ISSUE THREAD

**Issue by cryptosession** [alibaba/jvm-sandbox#209]
The high frequent handling of an object being necessary for each event listening, especially when the probes are inserted into `String` class, makes this scenario prone to poor performance. We can improve the overall performance by the following optimization methods:

1. Replace the `StringUtils.replace` with `String.replace`
2. Use `StringBuilder` instead of `String.format` —— As [this issue](https://stackoverflow.com/questions/925423/is-it-better-practice-to-use-string-format-over-string-concatenation-in-java) shows, this might lead to tenfold improvement in performance.
3. Loading target classes when necessary rather than each time when event fires.

**Comment by dongchenxu** [comment]
thank you for your PR, we merged and fix some bug in it
