### ISSUE TITLE
sandbox怎么在docker上监听服务

### ISSUE THREAD

**Issue by kangkangjiang123** [alibaba/jvm-sandbox#213]
菜鸟打听下，有没有办法支持或者相关的wiki

**Comment by dongchenxu** [comment]
我个人没有在docker上使用过，你是遇到什么问题了？

**Comment by meiyouxiaojianpan** [comment]
在docker上监听服务，是指把sandbox打包为一个docker镜像运行在docker中，然后监听docker中的其他服务？
