### ISSUE TITLE
不停启动/停止 sandbox，SandboxClassLoader 实例越加载越多。根本没卸载，jdk1.8

### ISSUE THREAD

**Issue by xingchen-Ann** [alibaba/jvm-sandbox#215]
<img width="1263" alt="sd" src="https://user-images.githubusercontent.com/30392401/65769610-8a9d7700-e166-11e9-952c-b82403bb47e3.png">

**Comment by dongchenxu** [comment]
非常感谢提醒，1.2.2版本的确有内存泄漏问题，请退回到1.2.1版本使用，这个版本我确认没有内存泄漏

**Comment by Mark-WJQ** [comment]
1.2.1 多次挂载也会有多个 SandboxClassLoader 实例，shutdown也不会卸载，nameSpace 不一样

**Comment by oldmanpushcart** [comment]
- 经过测试，无论1.2.1还是1.2.2，在JDK1.8下都没有出现内存泄漏的问题。
- 内存泄漏可能来自于自己写的module，sandbox自己带的module都经过测试和检查，内存在卸载的时候都会正常释放。所以核对下你是否加载了自己写的module，问题可能出在这些module上
