### ISSUE TITLE
构建类匹配器时hasAnnotationTypes是什么含义？

### ISSUE THREAD

**Issue by AlexRenCN** [alibaba/jvm-sandbox#217]
new EventWatchBuilder(moduleEventWatcher)
                .onClass("*")
                .hasAnnotationTypes("org.springframework.stereotype.Controller")
                .includeSubClasses()
                .onBehavior("*")
                .onWatch(new ControllerListener());

我尝试使用上面的代码来监控controller，但是实际运行中通过
Object result=advice.getReturnObj();
获得的结果永远是一个类：org.springframework.web.bind.annotation.RestController
看源码这个就是用来匹配类级别注解的，请问问题出在哪里呢？

用来测试的接口非常简单
    @GetMapping("/hello")
    public String hello(){
        return "hello, ******!";
    }

PS：通过改为以下代码可以正常获得返回值
        new EventWatchBuilder(moduleEventWatcher)
                .onClass("*公司名*Controller*")
                .includeSubClasses()
                .onBehavior("*")
                .onWatch(new ControllerListener());

**Comment by oldmanpushcart** [comment]
请问你当时是什么版本呢？我在1.2.2版本中测试是OK的；我写了测试用例在工程中可以参考
`com.alibaba.jvm.sandbox.qatest.core.issues.TestIssues217`

**Comment by AlexRenCN** [comment]
hi  我在develop-for-20191204分支中看到了你说的这个类，我现在理解了这个问题，这是因为在spring中，@RestController通过在本身添加了@ Controller注解获取了相对应的能力，如果我监听@RestController类可以正常获取，及hasAnnotationTypes这个方法并不会递归查找是否有对应的接口。

对于使用者来说，由于项目架构本身就会有很大的偏差，我不会使用@RestController作为检验标准，因为这不能覆盖大部分场景，在现有的代码逻辑下，多个注解只能取并集，我只能指定两个watcher来分别指向两个注解，希望能在取并集的基础上添加一个取或逻辑，采用List<String[]>的形式，在list每个元素里取并集，并作为最终结果取或的因子。

我碰到的不仅是这个是用场景，还有很多类似的注解，也是通过注解里引用注解的方式使用的，比如spring的@RequestMapping。

**Comment by oldmanpushcart** [comment]
哈，我弄明白了你的需求了，不过在此之前，我们得先说清一个概念：`注解组合`

### 注解组合

Java标准的Annotation定义中，并没有定义注解可以进行组合，这意味着

```java
@Controller
public @interface RestController {}
```

和

```java
public @interface Controller {}
```

在Java语言看来是两个完全独立的注解，组合注解是Spring自己发明的概念，是Spring这个框架自己实现的一套规范，目前是没有纳入到Java规范的。jvm-sandbox的定位并不是满足Spring框架，所以我们跟随Java语言的规范进行注解的解析。


### 问题解法

面对你的需求，我建议你的代码可以这样写，避免两个watch的尴尬

```java
new EventWatchBuilder(watcher)
    .onAnyClass()
    .hasAnnotationTypes("org.springframework.stereotype.Controller")
    .onAnyBehavior()
    .onAnyClass()
    .hasAnnotationTypes("org.springframework.web.bind.annotation.RestController")
    .onAnyBehavior()
    .onWatch(new EventListener() {
        @Override
        public void onEvent(Event event) throws Throwable {

        }
    });
```

**Comment by oldmanpushcart** [comment]
再给你补充一个用正则表达式的写法

```java
    @Target(ElementType.TYPE)
    @Retention(RetentionPolicy.RUNTIME)
    @interface TestAAnnotation {

    }

    @Target(ElementType.TYPE)
    @Retention(RetentionPolicy.RUNTIME)
    @interface TestBAnnotation {

    }

    @TestAAnnotation
    @TestBAnnotation
    class TestAB {

    }

    @TestAAnnotation
    class TestA {

    }

    @TestBAnnotation
    class TestB {

    }

    @Test
    public void matching__TestA_or_TestB__Annotation() {

        final GetMatcherModuleEventWatcher watcher = new GetMatcherModuleEventWatcher();

        new EventWatchBuilder(watcher, REGEX)
                .onAnyClass()
                .hasAnnotationTypes(".*Test(A|B)Annotation")
                .onAnyBehavior()
                .onWatch(new EventListener() {
                    @Override
                    public void onEvent(Event event) throws Throwable {

                    }
                });

        final Matcher matcher = watcher.getMatcher();
        Assert.assertTrue(matcher.matching(createClassStructure(TestA.class)).isMatched());
        Assert.assertTrue(matcher.matching(createClassStructure(TestB.class)).isMatched());
        Assert.assertTrue(matcher.matching(createClassStructure(TestAB.class)).isMatched());

    }
```

**Comment by AlexRenCN** [comment]
cooooool，之前没有了解过**组合注解**和**元注解**的区别，受教了。

看到1.2.2版本里ClassStructure接口getFamilyAnnotationTypeClassStructures方法的具体实现确实是根据当前类递归**查找父类**和**实现接口**来确定“家族类”范围的，确实不是我理解的用法，使用正则表达式的想法给了我一些思路，我会先尝试用一个方法来确定当前ApplicationContext中所有能**直接关联**到的组合注解，然后生成正则表达式来解决这个问题。
