### ISSUE TITLE
RoutingURLClassLoader死锁

### ISSUE THREAD

**Issue by haola334** [alibaba/jvm-sandbox#218]
RoutingURLClassLoader在loadClass方法前加了synchronize，可能会导致死锁，建议按className维度加锁，类似这样
![image](https://user-images.githubusercontent.com/1846439/66891917-d6806500-f01c-11e9-9459-50fb2a712c51.png)

**Comment by oldmanpushcart** [comment]
很好的建议，我已经按照你的建议在实现，在1.2.3版本中发布
