### ISSUE TITLE
Spy的advice方式会不会因为生成太多的Object[] 和 原始数据类型的Box类型造成内存占用增大，GC频繁

### ISSUE THREAD

**Issue by shidongwa** [alibaba/jvm-sandbox#219]
你好，JVM-Sandbox（包括greys）这种Spy 通过Method反射调用方式，不知是否遇到过内存占用增大，GC频繁影响服务质量的问题？特别是如果Advice在调用频繁的类，比如Http请求入口类，会随着服务TPS请求线性增长，GC STW造成请求出错率增加，服务质量下降还是比较明显的。

![image](https://user-images.githubusercontent.com/315525/67136342-9d800480-f257-11e9-8d5d-edc57566a069.png)

多谢。

**Comment by oldmanpushcart** [comment]
AdviceListener是一种非常重的工作模式，Greys默认采用这种模式。是绝对会极大的影响性能开销的。所以在对性能非常敏感的场景，是绝对不推荐采用AdviceListener来处理事件。

推荐EventListener，他的内存使用是经过比较严格的控制和包括类似对象池的设计，尽可能的减少临时内存的分配。

你截图的地方目前内存开销的确存在，但他产生的对象虽然多但是比较小，目前经过实践，他还比较少的被业务方投诉为影响GC的点（业务方其他地方的对象浪费得更多）

**Comment by shidongwa** [comment]
多谢驰哥回答。我了解一下EventListener方式。
