### ISSUE TITLE
单核处理器情况下，加载repeater模块报错

### ISSUE THREAD

**Issue by xueyb** [alibaba/jvm-sandbox#228]
### **_sandbox_**报错日志如下：
![图片](https://user-images.githubusercontent.com/32808004/68862243-145dcf80-0728-11ea-8b1f-9fb645dde8bc.png)

**Comment by oldmanpushcart** [comment]
从错误信息来看，应该是repeater模块的问题，这个和单核处理器应该也没啥关系。建议找[repeater](https://github.com/alibaba/jvm-sandbox-repeater)的人来问，我真不知道呢

**Comment by zhaoyb1990** [comment]
该问题是repeater问题，并且已Close，跟sandbox无关，具体可查看 [cpu核心数小于2报错](https://github.com/alibaba/jvm-sandbox-repeater/issues/40)
