### ISSUE TITLE
建议com.alibaba.jvm.sandbox.api.resource.ModuleEventWatcher接口提供方法watch(Filter filter, AdviceListener listener, Event.Type... eventType)

### ISSUE THREAD

**Issue by lpl606606** [alibaba/jvm-sandbox#231]
虽然现在可以通过AdviceAdapterListener过度adviceListener，但还是建议提供该方法简化使用过程，watching也建议提供AdviceListener对象

**Comment by oldmanpushcart** [comment]
两个观点哈 

1. AdviceListener其实真的很重，用来入门挺合适，用到实际生产中其实反馈的问题是极大的。问题主要集中在性能和ClassLoader导致的死锁上

1. EventWatchBuilder就是用来简化ModuleEventWatcher的使用复杂度的，建议用EventWatchBuilder来完成watch的构建哦
