### ISSUE TITLE
目标进程用户名太长时sandbox.sh运行失败

### ISSUE THREAD

**Issue by LeoZhao86** [alibaba/jvm-sandbox#232]
版本1.2.2
机器上有个进程，用户已经不存在。运行 sandbox.sh -p $PID 提示 
su: user xxx does not exist
permission denied, ~xxx/.sandbox.token is not readable

这个进程所属到用户名很奇怪，带个‘+’，也没法用useradd创建

看了对应代码是这段：
`  
TARGET_JVM_USER=$(ps aux | awk '$2==PID' PID=${TARGET_JVM_PID} | grep java | awk '{print $1}')
    if [[ "${USER}" != "${TARGET_JVM_USER}" ]]; then
        SANDBOX_TOKEN_FILE=$(eval echo "~${TARGET_JVM_USER}")/${SANDBOX_TOKEN_FILENAME}
        # touch attach token file
        su - ${TARGET_JVM_USER} -c "touch ${SANDBOX_TOKEN_FILE}" \
            || exit_on_err 1 "permission denied, ${SANDBOX_TOKEN_FILE} is not readable."
    fi
`
可以用当前用户${USER}目录下到token file， 而不用${TARGET_JVM_USER}目录下到token file么？

**Comment by LeoZhao86** [comment]
研究后发现是user name太长了，用ps是如果名字太长，第8个字符后面就都省略成‘+’。请问考虑这个情况。

**Comment by LeoZhao86** [comment]
有一个workaround是 https://askubuntu.com/questions/523673/ps-aux-for-long-charactered-usernames-shows-a-plus-sign

**Comment by oldmanpushcart** [comment]
1.2.3版本中规避这个问题
