### ISSUE TITLE
申请加入钉钉群

### ISSUE THREAD

**Issue by JavaProgrammerLB** [alibaba/jvm-sandbox#235]
扫加群二维码，现在显示成员人数达到上限1000人，无法加入；在跑Clock示例的时候，一步一步反复做了好几遍，还是没能解决，想进群请教

**Comment by oldmanpushcart** [comment]
目前正在想办法筹钱扩建钉钉群，升级企业群需要RMB的。
有问题可以在这里解答也挺好，增加issues的人气

**Comment by Mark-WJQ** [comment]
新建一个钉钉群呢？

**Comment by JavaProgrammerLB** [comment]
Clock修复坏了的钟问题请教；（-l命令能看到broken-clock-tinker模块；-d命令后没有报错；class名[com.taobao.demo.Clock]和方法名[checkState]正确；没有成功修复钟，代码依旧报错）
（1）创建java工程clock；mvn clean package打包，java -cp clock-1.0.jar com.taobao.demo.Clock命令运行Clock类
（2）创建java工程clock-tinker；mvn clean install打包，cp clock-tinker-1.0-jar-with-dependencies.jar ~/.sandbox-module
（3）下载运行jvm-sandbox
```
wget https://ompc.oss.aliyuncs.com/jvm-sandbox/release/sandbox-stable-bin.zip
unzip sandbox-stable-bin.zip
cd sandbox/bin
./sandbox.sh -p 18177
./sandbox.sh -p 18177 -l
./sandbox.sh -p 18177 -d 'broken-clock-tinker/repairCheckState'
``` 
![image](https://user-images.githubusercontent.com/3973419/70603135-d96c9000-1c30-11ea-8adb-6ab0ab045628.png)

命令执行后，Clock类仍然抛异常，未打印出时间
![image](https://user-images.githubusercontent.com/3973419/70603047-ba6dfe00-1c30-11ea-9aa8-cbe4c688d304.png)

创建的代码保存在这里：
https://github.com/JavaProgrammerLB/jvm-sandbox-playground

**Comment by oldmanpushcart** [comment]
@Mark-WJQ 建群的目的是主要是信息互享，答疑解惑是次要的，两个群有点违背这个意愿。
