### ISSUE TITLE
避免死锁的优化

### ISSUE THREAD

**Issue by z529192557** [alibaba/jvm-sandbox#242]
1 SandboxClassFileTransformer中有过滤sandbox自己类的逻辑
![image](https://user-images.githubusercontent.com/9245774/70790046-369e4800-1dcf-11ea-8d2e-afc70ef3b33e.png)
2.这部分逻辑在DefaultLoadedClassDataSource.findForReTransform 入口再做一次，可以避免
DefaultModuleEventWatcher.watch 中，调用DefaultLoadedClassDataSource.findForReTransform中获取sandbox自己的类结构信息时可能出现的加锁情况，降低死锁概率（混沌工程遇到过一次类似死锁问题）
![image](https://user-images.githubusercontent.com/9245774/70790350-de1b7a80-1dcf-11ea-9c2e-bbf28222b74c.png)

**Comment by oldmanpushcart** [comment]
多谢建议，在最新的分支上实现，下个版本发布掉
