### ISSUE TITLE
用agent方式启动，不能使我的实现代码生效

### ISSUE THREAD

**Issue by wayddmldbzz** [alibaba/jvm-sandbox#246]
加jvm参数“-javaagent:/Users/liyang/sandbox/lib/sandbox-agent.jar”启动后程序正常启动并且
自己实现的处理jar包已经放在文件夹下
![image](https://user-images.githubusercontent.com/28469498/71174349-ee37cc00-229f-11ea-86ca-7be6337b53df.png)
但是程序启动后我的修改并没有成功生效（这个jar包用动态编织的方式运行修改同样的方法运行能正常工作）
请指导下怎么处理？

**Comment by oldmanpushcart** [comment]
能把sandbox.log启动的日志贴出么？
