### ISSUE TITLE
启动报错  attach JVM 1365 fail, attach lose response 报错  用户名都是root 

### ISSUE THREAD

**Issue by acwyge** [alibaba/jvm-sandbox#248]
attach JVM 1365 fail, attach lose response

root@ydfat025031 bin]# ll
total 12
-rwxr-xr-x 1 root root 11186 Dec 12 11:42 sandbox.sh
[root@ydfat025031 bin]# ./sandbox.sh -p 1365
attach JVM 1365 fail, attach lose response.
[root@ydfat025031 bin]# ps -ef|grep java
root      1365     1  0 Dec03 ?        00:45:13 /usr/local/java/bin/java -jar -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=logs ifdriver.jar
用户名跟启动进程的一致，不知道为什么会报错，少配置什么了？
执行步骤按照快速安装的步骤一步一步进行的，谢谢大家

**Comment by oldmanpushcart** [comment]
需要看下两个日志

1. sandbox.log
1. 业务的默认日志

这两个日志中会有具体的错误信息

**Comment by fattyhan** [comment]
1、用户不一致指的不是操作启动target和attach时的用户不一样，也就是说我们通过sudo或其他命令切换用户是不可以的。这里指的是安装sandbox的用户、启动target用户、attach用户都要一致；
2、可以通过观察sandbox日志来查看是那个用户安装的，前提是没有自定义安装路径，其次需要查看token文件所在位置来确定，可以通过find命令来查看；
