### ISSUE TITLE
解决 #209 引入的问题

### ISSUE THREAD

**Issue by z529192557** [alibaba/jvm-sandbox#256]
EventWatchBuilder.onWatch(AdviceListener adviceListener, Event.Type... eventTypeArray) 不可以让开发者随意指定eventTypeArray，必须BEFORE，RETURN，THROWS 全部指定。
- 由于AdviceAdapterListener  BEFORE中会操作入栈
- RETURN，THROWS出栈，因此需要强制指定三个事件全部监听
否则：
1. 仅关注BEFORE，会导致不停入栈，OOM
2. 仅关注RETURN | THROWS ， 由于BEFORE没有入栈，导致功能失效

**Comment by oldmanpushcart** [comment]
啊，非常感谢，确实漏考虑了！但你的修复方案过于暴力，在保证基础功能可用的情况下必须得考虑API的向下兼容性。修复方案我先打回，但我会额外进行修复。
