### ISSUE TITLE
1.3.1版本EventListenerHandler.handleOnEnd中SandboxProtector.instance.isInProtecting()执行时机问题

### ISSUE THREAD

**Issue by z529192557** [alibaba/jvm-sandbox#259]
1. handleOnEnd中 SandboxProtector.instance.isInProtecting()应该在process.popInvokeId() : 403 之后做，以避免调用栈错位。
![image](https://user-images.githubusercontent.com/9245774/72232084-f0b8e780-35f9-11ea-9a76-bef79c8bd525.png)

2. handleOnCallXXX系列事件，  if(SandboxProtector.instance.isInProtecting())后没有立即return
![image](https://user-images.githubusercontent.com/9245774/72232047-b4858700-35f9-11ea-8f02-5e9c500ffd7b.png)

**Comment by oldmanpushcart** [comment]
1. handleOnEnd中的执行时机问题，因为有ThreadLocal的保护，所以不会出栈错位的情况。但需要补充测试用例证明和保障

1. line/call事件的处理的确漏掉了return，已经在最新的分支上补充上了这个逻辑。 #250
