### ISSUE TITLE
支持Module中通过二方包使用宿主应用类

### ISSUE THREAD

**Issue by z529192557** [alibaba/jvm-sandbox#260]
支持Module中通过二方包使用宿主应用类的方案：
1. 类加载策略优化
![image](https://user-images.githubusercontent.com/9245774/72419593-1ab80880-37b8-11ea-9a6e-e8eea5d7c52b.png)

2. 需要Module工程做的关键变更和注意事项：
   - maven引入的二方包scope必须是provided，任何打入Module jar的Class，如果和宿主类重名都会优先从Module jar 文件中加载。
   - Module的生命周期阶段，无法使用二方包中的宿主类，会抛出ClassNotFoundException。
   - 使用二方包中的宿主类范围：只能在AdviceListener/EventListener的系列事件方法调用中

**Comment by zhaofb** [comment]
这种解决方案只对非模块块的应用系统是可行的，如果一个类由多个ClassLoader加载生成多个Class实例时二方包中引用的类则始终是第一个应用使用的类加载器加载，这仍然会导致类加载问题
