### ISSUE TITLE
crash错误

### ISSUE THREAD

**Issue by nfw999** [alibaba/jvm-sandbox#269]
jdk1.8.0_05
sandbox version : 1.2.0 / 1.2.1/1.3.1
attach方式 root用户执行
宿主进程 root用户执行

打印某方法返回值

```

@Override
protected void afterReturning(Advice advice) {
        log.info(JSON.toJSONString(advice.getReturnObj()));
}

```

sandbox日志没有异常记录

![image](https://user-images.githubusercontent.com/33611490/74914361-46549100-53fd-11ea-99cc-3429f2b91cbd.png)

crash 日志:
[hs_err_pid5865.log](https://github.com/alibaba/jvm-sandbox/files/4229425/hs_err_pid5865.log)

**Comment by DayJun** [comment]
jdk1.8的低版本有bug，可以看一下openjdk的相关提交和issue

**Comment by oldmanpushcart** [comment]
@nfw999 

我看crash的点是在module中的代码，

```
RAX=0x00000000cf7023b8 is an oop
io.***.statsd.StatsdMeterRegistry$$Lambda$145/1707567367 
 - klass: 'io/***/statsd/StatsdMeterRegistry$$Lambda$145'
RBX=0x00007f9074e55250 is an unknown value
RCX=0x00007f9118ad0640 is at begin+12 in a stub
MethodHandle::interpreter_entry::_linkToStatic [0x00007f9118ad0634, 0x00007f9118ad0658[ (36 bytes)
RDX=0x00000000cd499c58 is an oop
java.lang.invoke.MemberName 
 - klass: 'java/lang/invoke/MemberName'
RSP=0x00007f9074508f10 is pointing into the stack for thread: 0x00007f8ffc950000
RBP=0x00007f8ea1e5cdf8 is an unknown value
RSI=0x00000000cf7023b8 is an oop
io.***.statsd.StatsdMeterRegistry$$Lambda$145/1707567367 
 - klass: 'io/***/statsd/StatsdMeterRegistry$$Lambda$145'
RDI=0x00007f90745090d0 is pointing into the stack for thread: 0x00007f8ffc950000
R8 =0x00000000cd499c58 is an oop
java.lang.invoke.MemberName 
 - klass: 'java/lang/invoke/MemberName'
R9 =0x0000000000679848 is an unknown value
R10=0x00000000cf7023b8 is an oop
io.***.statsd.StatsdMeterRegistry$$Lambda$145/1707567367 
 - klass: 'io/***/statsd/StatsdMeterRegistry$$Lambda$145'
R11=0x00007f9118acf900 is at entry_point+0 in (nmethod*)0x00007f9118acf7d0
R12=0x0000000000000000 is an unknown value
R13=0x00007f9074508f00 is pointing into the stack for thread: 0x00007f8ffc950000
R14=0x00007f9074508fa8 is pointing into the stack for thread: 0x00007f8ffc950000
R15=0x00007f8ffc950000 is a thread
```

你可能要看看这里的代码在干啥诱发了 @DayJun 所说的JVM的BUG。

@DayJun 能翻出对应的BUG ISSUES么？我也挺好奇的

**Comment by xl1605368195** [comment]
内部使用jvm-sandbox的的错误贴下

# nacos 加载 sandbox crash

## 现象

nacos 加载jvm-sandbox后崩溃, 出现 `hs_err_pid32403.log`

## 诊断

使用 CrashAnalysis 诊断工具 分析 `hs_err_pid32403.log`

```shell
java -jar CrashAnalysis-1.0-SNAPSHOT.jar hs_err_pid32403.log
```

分析结果：


![img](https://user-images.githubusercontent.com/26989019/195803059-2d547abb-8ea8-4b62-9e83-42e12a278094.png)

![img_1](https://user-images.githubusercontent.com/26989019/195803294-0cdc66f1-eec2-44c7-b151-e8186ffc6e5a.png)


从诊断工具的结论来看，可能是`jdk bug`，但是由sandbox 修改直接码触发

## 排查

+ 不加载任何模块（无字节码修改）,没有crash

+ 当前nacos的使用的jdk是1.8.0_05 、而换用1.8.0_112 没有问题（ ？？）

## 初步的解决办法

换用高版本jdk 如: `jdk1.8.0_112`

**Comment by oldmanpushcart** [comment]
@xl1605368195 使用的jvm-sandbox版本是多少，方便使用develop-for-20220822分支的1.4.0-SNAPSHOT版本测试下么，在这个分支我们修复了 #328

**Comment by DayJun** [comment]
https://bugs.openjdk.org/browse/JDK-8097231

**Comment by oldmanpushcart** [comment]
@DayJun 原来如此，多谢提供

**Comment by DayJun** [comment]
依据 https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8041920
在java命令行添加 -XX:CompileCommand=exclude,java/lang/invoke/LambdaForm$*.invoke* 参数即可规避崩溃，测试过可行

**Comment by oldmanpushcart** [comment]
@DayJun 学习到了，多谢
