### ISSUE TITLE
目前修复时钟的demo无法运行(急)

### ISSUE THREAD

**Issue by ipnuboyok** [alibaba/jvm-sandbox#270]
我按这个上面的做了好几遍https://github.com/alibaba/jvm-sandbox/wiki/FIRST-MODULE
问题1.启动的时候目前用ATTACH无法启动,报错如下:
MacBook-Pro:bin $ ./sandbox.sh -p 94676 
target JVM 94676 lose response.
我在sh里加调度代码打印了个URL 
MacBook-Pro:bin zhupy-pc$ ./sandbox.sh -p 94676 
./sandbox.sh: line 291: http://https://account.jetbrains.com:443:58309/sandbox/default/module/http/sandbox-info/version?1=1: No such file or directory
target JVM 94676 lose response.

目前只能用AGENT方式启动
问题2.运行修复时钟的案例时，

MacBook-Pro:bin $ ./sandbox.sh -p 76431 -l
sandbox-info        	ACTIVE  	LOADED  	0    	0    	0.0.4          	luanjia@taobao.com
sandbox-module-mgr  	ACTIVE  	LOADED  	0    	0    	0.0.2          	luanjia@taobao.com
sandbox-control     	ACTIVE  	LOADED  	0    	0    	0.0.3          	luanjia@taobao.com
total=3

**Comment by wenbingz** [comment]
我猜你没有加services，java spi的那个规范

**Comment by zhongtaogithub** [comment]
楼主解决了没？
