### ISSUE TITLE
attach时出错，com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize

### ISSUE THREAD

**Issue by zhanghsiyu** [alibaba/jvm-sandbox#271]
windows可以attach，但是linux上就会报错
./sandbox.sh -p 39
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:61)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
sandbox load jvm failed : Agent JAR loaded but agent failed to initialize

**Comment by 0range228** [comment]
+1 我也遇到了

**Comment by zhangliang1024** [comment]
请教同样的问题：
![image](https://user-images.githubusercontent.com/30827471/125015127-760f4200-e0a1-11eb-87ee-2bf489cc8964.png)

**Comment by zhangliang1024** [comment]
> windows可以attach，但是linux上就会报错
> ./sandbox.sh -p 39
> com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
> at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
> at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:61)
> at com.alibaba.jvm.sandbox.core.CoreLauncher.(CoreLauncher.java:20)
> at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
> sandbox load jvm failed : Agent JAR loaded but agent failed to initialize

检查下被 ATTACH，看下报错信息。我在windows环境 ATTACH 进程时，sandox/bin/sandbox.sh脚本中：SANDBOX_HOME_DIR 获取本地目录错误，导致ATTACH失败。修改sandbox.sh中SANDBOX_HOME_DIR为正确路径即可。不知道是否可以帮助到你。
下图修改后的sandbox.sh:
![image](https://user-images.githubusercontent.com/30827471/125034025-ae734800-e0c2-11eb-8d51-2e6a442ca9ec.png)
