### ISSUE TITLE
z529192557 / jvm-sandbox里有BusinessClassLoaderHolder，为何没有合入？应该可以执行业务代码了？

### ISSUE THREAD

**Issue by zhenjia001** [alibaba/jvm-sandbox#272]
z529192557 / jvm-sandbox里新增了BusinessClassLoaderHolder，改造了EventListenerHandler
加入这部分能力是不是就可以获取业务classloader，反射执行业务代码？

**Comment by z529192557** [comment]
是的,目前还在评估之中

**Comment by zhenjia001** [comment]
还在评估？

**Comment by zhenjia001** [comment]
@z529192557 你好，请问你的BusinessClassLoaderHolder在你的git里没有了，还没有评估完吗？

**Comment by z529192557** [comment]
1.3.2版本合并了

**Comment by zhenjia001** [comment]
非常感谢

**Comment by xiaoxiaocaiiao** [comment]
这个功能是不是可以 走代理的方式来 尽量不要用反射 比如 可以先定义一个空壳 类 类 中有个空方法 这个方法我们可以在自己的 agent 里面调用 ，在这个空壳方法上面 采用注解 或者其他方式指定是业务类将要对什么方法进行代理，在sandbox 做 注入代码的时候 将需要注入的方法注入到代理类中去。 agent 就可以像调用自己方法一样调用业务方法不用 使用反射的方式。
