### ISSUE TITLE
Slf4j Classloader问题

### ISSUE THREAD

**Issue by KimShen** [alibaba/jvm-sandbox#273]
激活Module时抛出以下错误导致没办法加载：
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/alibaba/jvm/sandbox/core/classloader/ModuleJarClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature

检查应用代码，发现第三方包使用了lombok.extern.slf4j.Slf4j。如果第三方包没有办法替换，怎么避免上面这个错误让Moudle加载起来呢。

**Comment by oldmanpushcart** [comment]
引入三方包的时候，主动exclude掉是否可以？
