### ISSUE TITLE
EventWatchBuilder 添加trace事件，对性能影响很大

### ISSUE THREAD

**Issue by zyhui98** [alibaba/jvm-sandbox#285]
`watcher = new EventWatchBuilder(moduleEventWatcher, EventWatchBuilder.PatternType.REGEX)
                .onClass(classPattern)
                .onBehavior(methodPattern)
                .onWatching().withProgress(process).onWatch(traceListener,
                        Event.Type.BEFORE, Event.Type.RETURN, Event.Type.THROWS
                );`

上面的代码，比如类是400个，方法4000个匹配上了，相应的接口qps会降到1/4左右
![image](https://user-images.githubusercontent.com/5568889/84913246-e80a9700-b0ec-11ea-81ab-3d0e316eef06.png)

其中注入和取消注入，对qps影响很大。
特别是“取消注入”的阶段，几乎qps降为0.

**Comment by zyhui98** [comment]
```
please
```

**Comment by zyhui98** [comment]
`
^(?!<init>$)^(?!equals$)^(?!hashCode$)^(?!toString$)^(?!submit$)^(?!run$)^(?!start$)^(?!main$)
`
以上正则表达式，可以匹配方法，但是sandbox中匹配的结果是空。

**Comment by Tommyww** [comment]
我也是小白，慢的原因我觉得有两个
1.在注入的时候，因为会替换方法区已经加载的类，在new对象的时候，这个class类都不存在了，那肯定得先加载。但是加载类的底层有synchronized修饰，你得加载完成才行，加载那个类的程序只能等待。换句话说：你注入的方法越多，加载完成时间越长，对性能影响越大
2.加载过程中有字节码生成和注入逻辑，很耗cpu，在cpu资源固定的情况下，这边占用cpu的资源会更多一些，因为要依赖加载，正常业务线程已经挂起了。

**Comment by zyhui98** [comment]
> 我也是小白，慢的原因我觉得有两个
> 1.在注入的时候，因为会替换方法区已经加载的类，在new对象的时候，这个class类都不存在了，那肯定得先加载。但是加载类的底层有synchronized修饰，你得加载完成才行，加载那个类的程序只能等待。换句话说：你注入的方法越多，加载完成时间越长，对性能影响越大
> 2.加载过程中有字节码生成和注入逻辑，很耗cpu，在cpu资源固定的情况下，这边占用cpu的资源会更多一些，因为要依赖加载，正常业务线程已经挂起了。

是的， 只能去掉了。
还有个问题， 多次注入，classloader加载的类元数据销毁不了，classloader.close貌似没有触发metaspace区的销毁

**Comment by oldmanpushcart** [comment]
1. sandbox观察的类不建议太多，否则对性能影响不能被忽视。强烈建议是有针对性的观察方法。
2. 多次注入metaspace区无法被销毁，我dump了下内存，强制进行了一次FGC似乎没有重现这个问题。我保持关注，如果后续有重现，reopen
