### ISSUE TITLE
jvm-sandbox对自定义类进行增强的时候，如果这个类不存在，希望能够报错提示出来。

### ISSUE THREAD

**Issue by WildSeeds** [alibaba/jvm-sandbox#291]
EventWatcher eventWatcher = eventWatchBuilder.onClass(className)
            .onBehavior(functionName)
            .withParameterTypes(parameterTypes)
            .onWatch(new UserDefinedListenner(sentry,parameterTypes)
                ,Type.BEFORE
                ,Type.IMMEDIATELY_RETURN
                ,Type.RETURN);

当传入的className，在应用中找不到的情况下，一点报错信息都没有，加大了问题排查的难度

**Comment by z529192557** [comment]
这个在日志里有打印
