### ISSUE TITLE
Can jvm-sandbox AOP replace Spring AOP? 

### ISSUE THREAD

**Issue by ChrisLogosZen** [alibaba/jvm-sandbox#300]
Hi owners:
    If we can replace spring AOP with jvm-sandbox AOP in the application design. Is there a test report to help assessing the impact of the performance, before lanching and after.Thanks.

**Comment by oldmanpushcart** [comment]
spring AOP的设计是around的编码风格，功能上能替代，但编码上不行，造成这个原因的JVMTI的限制。
但可以通过复杂的逻辑变化处理，让sandbox.AOP可以模拟成spring.AOP，就是性能损耗上得不偿失，所以最终废弃了这段代码。

**Comment by ChrisLogosZen** [comment]
谢谢回复，我们在深入使用java agent attach这块，请不吝赐教，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/jvm-sandbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 中午11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/jvm-sandbox] Can jvm-sandbox AOP replace Spring AOP?  (#300)





 
spring AOP的设计是around的编码风格，功能上能替代，但编码上不行，造成这个原因的JVMTI的限制。
 但可以通过复杂的逻辑变化处理，让sandbox.AOP可以模拟成spring.AOP，就是性能损耗上得不偿失，所以最终废弃了这段代码。
