### ISSUE TITLE
Testing Framework supports

### ISSUE THREAD

**Issue by cryptosession** [alibaba/jvm-sandbox#301]
It's all-important to reduce the cost of testing,  obtain higher fault coverage and improve the R& D efficiency, we starve for an easy-to-use test framework.

**Comment by oldmanpushcart** [comment]
jvm-sandbox是有测试框架支撑的哦，测试框架的核心类JvmHelper可以模拟类被字节码增强的过程，还是很牛逼的

**Comment by oldmanpushcart** [comment]
jvm-sandbox是有测试框架支撑的哦，测试框架的核心类JvmHelper可以模拟类被字节码增强的过程，还是很牛逼的
