### ISSUE TITLE
加强泛型方法时,出现多次enhance的问题

### ISSUE THREAD

**Issue by tangtangsara** [alibaba/jvm-sandbox#304]
代码如下 :
 
new EventWatchBuilder(moduleEventWatcher)
                .onClass("com.mongodb.operation.ReadOperation")
                .includeSubClasses()
                .onBehavior("execute")

[INFO ] rewrite method com.mongodb.operation.CountOperation#execute(com.mongodb.binding.ReadBinding) for listener[id=1035];event=BEFORE,RETURN,THROWS,IMMEDIATELY_RETURN,IMMEDIATELY_THROWS;[http-nio-8080-exec-7][com.alibaba.jvm.sandbox.core.enhance.weaver.asm.EventWeaver]
[INFO ] rewrite method com.mongodb.operation.CountOperation#execute(com.mongodb.binding.ReadBinding) for listener[id=1035];event=BEFORE,RETURN,THROWS,IMMEDIATELY_RETURN,IMMEDIATELY_THROWS;[http-nio-8080-exec-7][com.alibaba.jvm.sandbox.core.enhance.weaver.asm.EventWeaver]

对于泛型方法, Class中有一个返回值是Object的同签名方法, 造成加强多次

建议将 EventWeaver.java代码中isMatchedBehavior改为, 请确认方案是否可行

    private boolean isMatchedBehavior(final String signCode) {
        return signCodes.remove(signCode);
    }

**Comment by z529192557** [comment]
mongodb client的坐标依赖发一下看看

**Comment by oldmanpushcart** [comment]
泛形同签名，编译应该通不过才对吧
