### ISSUE TITLE
这个支持java11吗

### ISSUE THREAD

**Issue by wuguanyu** [alibaba/jvm-sandbox#305]
![image](https://user-images.githubusercontent.com/24486917/100302713-def3ef00-2fd5-11eb-877a-7f15c8997a73.png)

Could not resolve dependencies for project com.alibaba.jvm.sandbox:sandbox-core:jar:1.3.3: Could not find artifact com.sun:tools:jar:1.8 at specified path /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/../lib/tools.jar -> [Help 1]

**Comment by RecursionHs** [comment]
兄弟  不是介绍了支持[6,11]吗？

**Comment by wuguanyu** [comment]
@RecursionHs 之前放开始接触不大懂
