### ISSUE TITLE
层次较深的泛型场景下 Behavior#getReturnType 返回的Class类型无法满足JSON String到对象反序列

### ISSUE THREAD

**Issue by aceshot** [alibaba/jvm-sandbox#310]
com.alibaba.jvm.sandbox.api.listener.ext.Behavior
建议支持下返回Type，新增方法： Type getGenericReturnType();   // jdk1.8及以上版本

    class MethodImpl implements Behavior {

        @Override
        public Type getGenericReturnType() {
            return target.getGenericReturnType();
        }

    class ConstructorImpl implements Behavior {

        @Override
        public Type getGenericReturnType() {
            return target.getDeclaringClass();
        }

**Comment by z529192557** [comment]
如果有样例类例子的话，“无法满足json String 到对象的反序列化例子” 更好

**Comment by oldmanpushcart** [comment]
@aceshot 已经在v1.4.0版本实现。

如果你使用老版本，建议使用下边这个方法，拿到原始目标对象自行处理

```java
/**
     * 获取被封装的目标对象: Method/Constructor
     *
     * @return 目标对象
     * @since {@code sandbox-api:1.2.2}
     */
    AccessibleObject getTarget();
```
