### ISSUE TITLE
beforeLine回调方法没有被执行

### ISSUE THREAD

**Issue by five3** [alibaba/jvm-sandbox#311]
尝试过挂在beforeLine行为，实际上没有被调用。同一个挂载模块中before挂载行为就生效了。

另外【利用LineEvnet实现了行链路识别和标记】这个有样例么

**Comment by z529192557** [comment]
beforeLine等系列方法要调用  withCall()方法来打开  DebugTraceModule有例子

**Comment by reeduszhang** [comment]
withCall()方法打开依然没有生效。参考了DebugTraceModule。before和afterThrowing是可以的。

**Comment by reeduszhang** [comment]
这里明白了。针对beforeCall来说，如果onBehavior是 a方法，并不是beforeCall a，而是a中的方法。如果a方法里面没有子方法调用，是触发不了这个事件的。

**Comment by yuruotong1** [comment]
问题解决了吗，我的 beforeLine 也无法被回调！

**Comment by code-bez** [comment]
收到

**Comment by yuruotong1** [comment]
> 收到

这个项目是你在维护吗？？这么快就回复了
