### ISSUE TITLE
目前jvm-sandbox的应用除了chaosblade, repeater，还有没有其他应用，比如限流，容错，路由，安全方面的应用？

### ISSUE THREAD

**Issue by chenhuandong8010** [alibaba/jvm-sandbox#312]
目前jvm-sandbox的应用除了chaosblade, repeater，还有没有其他应用，比如限流，容错，路由，安全方面的应用？

**Comment by z529192557** [comment]
1.流量录制回放
2.接口依赖感知
3.sql采集等等集团内部有非常多的三方模块，来完成自己特定的功能

**Comment by orangle** [comment]
接口依赖感知 是什么样的功能？

**Comment by xl1605368195** [comment]
安全方面的应用：
基于jvm-sandbox 构建了一个 开源项目：[jrasp](https://github.com/jvm-rasp/jrasp-agent)  仅供学习。
[官网](https://www.jrasp.com)
