### ISSUE TITLE
希望暴露Instrumentation给Api

### ISSUE THREAD

**Issue by tmtbe** [alibaba/jvm-sandbox#313]
DefaultCoreModuleManager的Instrumentation希望暴露给sandbox api，在active时传递过去，便于扩展，如在自定义模块中实现代码热重载等功能。

**Comment by z529192557** [comment]
感觉会破坏Sandbox的功能约定（仅做方法级别AOP，屏蔽底层字节码细节），而变成一个Instrumentation工具包，及时不暴露Instrumentation，也有办法进行代码重置，参考jvm-sandbox-repeater处理配置文件变更的代码： https://github.com/alibaba/jvm-sandbox-repeater/blob/master/repeater-module/src/main/java/com/alibaba/jvm/sandbox/repeater/module/RepeaterModule.java     noticeConfigChange(

**Comment by tmtbe** [comment]
还是有特定场景需要的，比如制作热重载功能，另外开放class增强环绕也是需要的，比如我需要sandbox增强前进行classbyte处理，sandbox增强后再处理，毕竟sandbox本身的增强功能是有限的。我已经在我自己的分支中实现了上面2个的需求。
