### ISSUE TITLE
idea调试的时候，无法获取应用的类

### ISSUE THREAD

**Issue by lishun888** [alibaba/jvm-sandbox#317]
背景：本地启动两个应用，一个是开发代码，一个是sandbox-repeater，进行调试回放过程。

问题：在调试过程中，hessian反序列化过程中，无法获取到开发代码工程的类，导致对象反序列化为hashmap

**Comment by z529192557** [comment]
正常来说，在sandbox-repeater ，进行的hessian反序列化，理论上就是应该转化为HashMap，而在业务应用中才可以正确反序列化为真实类型，这个问题不会影响回放

**Comment by tmtbe** [comment]
“无法获取到开发代码工程的类“这个问题应该可以通过反射实现，通过获取业务的ClassLoader可以通过反射拿到业务的Class类，这样就可以反序列化了。模块中使用的RoutingURLClassLoader，找不到类的情况下最后会走BusinessClassLoaderHolder去获取类。这里的BusinessClassLoader就是业务的类加载器了。
