### ISSUE TITLE
各位开发注意一个问题：指令爆炸

### ISSUE THREAD

**Issue by z529192557** [alibaba/jvm-sandbox#318]
**指令爆炸：**
    同一jvm下，反复针对一个方法的增强，可能会导致单个方法的指令数量以指数级别增长

##什么时候会出现：
 1.多个module增强同一个方法（不可控，难以避免）
 2. 单个module反复增强同一个方法（模块开发自己可控，可以避免）

**原因：**
Sandbox会针对方法的entrance，throw，xReturn，（AOP增强）进行字节码指令织入增强，而增强后的增加的throw，xReturn指令会变成第二次AOP增强的增强点，以此类推，会造成单个方法指令集在反复增强条件下呈指数级别增长，jvm单个方法最大指令数量为65535条，超过这个数量，会造成难以预料的后果（大概率asm先于jvm报错）。

以修钟为例子，增强到9次后，class byte[]大小逼近160KB，字节码无法反编译, 目标类加载速度非常低

**结论：**
1. 过多的ClassTransformer可能会降低了类加载速率（由于一个watch会增加一个ClassTransformer）
2. 针对同一个方法反复增强，同时也会每次增强耗时会越来越多直到asm崩溃
3. 目前不可以针对同一个方法进行太多次增强，很难说会在哪次增强造成asm崩溃（修钟例子，在我本机第10次增强后抛出异常），ams日志中样例异常:
java.lang.StackOverflowError: null
	at org.objectweb.asm.Handler.removeRange(Handler.java:123)
	at org.objectweb.asm.Handler.removeRange(Handler.java:123)
	at org.objectweb.asm.Handler.removeRange(Handler.java:123)
	at org.objectweb.asm.Handler.removeRange(Handler.java:123)

**解决策略（待做）：**
1. one-classTransformer
  只要一个classTransformer
2.  once-enanche
  同一个类只会被增强一次

**Comment by tmtbe** [comment]
我觉得one-classTransformer并不会有明显的性能提升，还会增加复杂度，因为sandbox有卸载的功能，通过removeTransformer再
retransformClasses(Class<?>... classes）达到卸载的目的，如果实现one-classTransformer会有额外的管理增强的逻辑在里面，实现会更为复杂，性能有没有提升也未知。

**Comment by tmtbe** [comment]
另外利用classTransformer可以重复增强是有场景的，比如同一个class我需要增强多个方法，那么确实可以watch多次进行重复增强，而不是用匹配模式写额外的代码（判断method名称）实现，所以once-enanche是由自己控制比较好。

**Comment by z529192557** [comment]
> 另外利用classTransformer可以重复增强是有场景的，比如同一个class我需要增强多个方法，那么确实可以watch多次进行重复增强，而不是用匹配模式写额外的代码（判断method名称）实现，所以once-enanche是由自己控制比较好。

解决的策略目前还不确定，因为评估了下额外的管理增强的逻辑确实很复杂，目前还是交给使用者来管控成本更低

**Comment by XHao** [comment]
除了单个方法的指令问题，one watch one transformer带来metaspace的额外开销也值得关注。
尤其是对于一些方法很多的类，如果能减少retransform，效果很明显。

**Comment by oldmanpushcart** [comment]
这个超级复杂，先挂起～
