### ISSUE TITLE
sandbox埋点和skywalking埋点的字节码冲突，导致sandbox的增强功能不可用

### ISSUE THREAD

**Issue by testerSunshine** [alibaba/jvm-sandbox#321]
sandbox版本1.3.3
场景1:  skywalking先开启，sandbox后开启，sandbox增强实效，skywalking功能正常
场景2: sandbox先开启，skywalking后开启，或者远程debug卡住skywalking实时增强，sandbox增强成功

**Comment by tmtbe** [comment]
可以dump class文件下来看下

**Comment by HendSame** [comment]
这个有解决方案了么

**Comment by anaer** [comment]
试下这个看看
[Compatibility with other Java agent bytecode processes
](https://github.com/apache/skywalking/blob/master/docs/en/FAQ/Compatible-with-other-javaagent-bytecode-processing.md)

**Comment by oldmanpushcart** [comment]
原因定位同 #328

**Comment by oldmanpushcart** [comment]
1.4.0中发布解决
