### ISSUE TITLE
不同sanbox应用attach冲突

### ISSUE THREAD

**Issue by orangle** [alibaba/jvm-sandbox#322]
jvmsandbox 版本 sandbox-1.3.0
目标程序  tomcat
目的是想同时使用2个基于sanbox的模块。

步骤 
1 先从官网下载 sandbox-1.3.0 版本，通过attach到tomcat进程
2 使用sandbox-1.3.0打包  chaosblade-jvm-sandbox，然后使用 chaosblade命令attach，无法attach成功

sandbox下只有一行日志，也没有模块load等信息
2021-04-26 11:54:14 default WARN  path=/chaosblade/status is matched module chaosblade, but not existed.

请问下，这种情况有啥排查手段吗？因为没啥异常的日志。

**Comment by tmtbe** [comment]
这个报错就是说Module没有找到，不是attach冲突问题。 chaosblade-jvm-sandbox没有加载成功，sandbox.sh -l 看一下应该没有这个模块。

**Comment by orangle** [comment]
就是attach冲突问题 默认的namespace冲突了。。有点坑。
