### ISSUE TITLE
AOP around某些情形无法很好的处理

### ISSUE THREAD

**Issue by tmtbe** [alibaba/jvm-sandbox#324]
例子
A：
public void test{
  //一堆业务代码
  //System.out.print("text");
}

想增强为：
public void test{
  xxx.run(()->{
       //一堆业务代码
       //System.out.print("text");
  });
}

即：
public void test{
  xxx.run(()->{
      proxy.test();
  });
}
这种around的情形用sandbox并不好处理。
如果用before增强test实现，势必涉及到递归了，（在before方法中继续调用自身。。。），很难正确处理。

请问这种情况有没有什么好思路。比如test的方法体想放到一个线程池中运行这种增强就很难实现。

**Comment by tmtbe** [comment]
目前我的做法是，将sandbox魔改，增加了SandboxClassTransform接口，在SandboxClassFileTransformer中new EventEnhancer()前后实现了hook。代码中通过获取class bytes重新手动修改。

**Comment by tmtbe** [comment]
其实我觉得，将原本方法名修改为private xxxx$original方法，再构建和原来签名相同的新方法:
xxx(){
    xxxx$original()
}
这种增强形式会不会更好一些。而不是直接在原始方法体上进行asm修改，新增private方法也不违反jvm规范。

**Comment by z529192557** [comment]
不会有递归的情况出现，进入before中的逻辑，不会再次进入before中

**Comment by oldmanpushcart** [comment]
@tmtbe 新增private方法不违反jvm规范么？我核对了下应该是影响的。

`java.lang.instrument#retransformClasses(Class<?>...)`方法说明

```
The retransformation may change method bodies, the constant pool and attributes. The retransformation must not add, remove or rename fields or methods, change the signatures of methods, or change inheritance. 
```
