### ISSUE TITLE
启动sandbox时，Spy.init()方法提示NoSuchMethodError

### ISSUE THREAD

**Issue by jhulk** [alibaba/jvm-sandbox#326]
![image](https://user-images.githubusercontent.com/22445203/120757904-bbd96780-c543-11eb-810d-2795814bc84d.png)

**Comment by z529192557** [comment]
这个是Soy多版本冲突造成，一般重启应用，重新挂载即可

**Comment by zjutkz** [comment]
> 这个是Spy多版本冲突造成，一般重启应用，重新挂载即可

你的意思是同一个项目引用了两个不同版本的sandbox吗？

**Comment by z529192557** [comment]
> > 这个是Spy多版本冲突造成，一般重启应用，重新挂载即可
> 
> 你的意思是同一个项目引用了两个不同版本的sandbox吗？

是的
