### ISSUE TITLE
sandbox 是否存在当 执行到spyMethodOnReturn 之后 当Ret.state==1 的时候栈未清空的情况，麻烦帮忙确认。

### ISSUE THREAD

**Issue by xiaoxiaocaiiao** [alibaba/jvm-sandbox#328]
复现step
1. 采用 -javaagent 方式启动 sandbox 增强 某个 方法 a
2. 重新写一个 java agent 在 transfer 中采用  javassist 中的 hookMethod.insertAfter 修改 同一个方法 a 抛出异常 jdk.internal.org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 125: Incompatible stack heights
	at jdk.internal.org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:324)
这种情况 大多数因为try catch 引起

**Comment by xiaoxiaocaiiao** [comment]
问题应该是出在了 如下代码如何是的 这个问题会不会造成内存溢出 先抛开我这个问题不谈 你们这个是不是有 栈 没有清空 的危险，在 131行栈里面还有两个值 可是只pop 了一个 要清理最早的一个需要交换两个栈顶值后再pop 一次 否则会有栈未清空的可能难道你们用的areturn 会清理最后的所有栈中值吗？ 请帮忙确认这个问题。。
 98: invokeinterface #163,  3    
       103: iconst_2
       104: pop
       105: dup
       106: ldc_w         #799                // String default
       109: sipush        1005
       112: invokestatic  #822                // Method java/com/alibaba/jvm/sandbox/spy/Spy.spyMethodOnReturn:(Ljava/lang/Object;Ljava/lang/String;I)Ljava/com/alibaba/jvm/sandbox/spy/Spy$Ret;
       115: dup
       116: getfield      #815                // Field java/com/alibaba/jvm/sandbox/spy/Spy$Ret.state:I
       119: dup
       120: iconst_1
       121: if_icmpeq     131
       124: iconst_2
       125: if_icmpeq     141
       128: goto          148
       131: pop
       132: getfield      #818                // Field java/com/alibaba/jvm/sandbox/spy/Spy$Ret.respond:Ljava/lang/Object;
       135: goto          205

**Comment by z529192557** [comment]
131执行完后，栈中值剩下Ret，在132中会用上

**Comment by z529192557** [comment]
最好把完整方法的字节码全部贴出来分析

**Comment by xiaoxiaocaiiao** [comment]
这个问题我已经在自己的代码修复掉了，这里131  还有一个 object 的，只是sanbox不容易发现，因为 sandbox 在135 行用的return 之类的指令 栈会被清空 所以不会看出问题，但是一旦 出现多个 agent 同时 注入一个方法的时候就会出现 ，这里会有 类检查 会报栈平衡问题错误。

**Comment by xiaoxiaocaiiao** [comment]
我贴的这个就已经可以看出问题了。

**Comment by xiaoxiaocaiiao** [comment]
我就是通过这段代码分析出来的

**Comment by z529192557** [comment]
131的object是132用的

**Comment by z529192557** [comment]
你的意思是指131 pop后栈两个对象，pop前有三个对象，还是指pop后栈中有一个对象，pop前有两个?

**Comment by z529192557** [comment]
我明白你的意思了，栈底状态是 [Ret.respond, object]，对吧，object 98行真实调用返回的

**Comment by xiaoxiaocaiiao** [comment]
是的

**Comment by xiaoxiaocaiiao** [comment]
需要把object 的 给pop 掉

**Comment by z529192557** [comment]
需要在ARETURN 的合适位置，swap pop一下，有时间的话，可以提交一份修复的PR吗

**Comment by xiaoxiaocaiiao** [comment]
我可以把修复代码贴出来哈

**Comment by z529192557** [comment]
> 我可以把修复代码贴出来哈

感谢

**Comment by xiaoxiaocaiiao** [comment]
我的修复点在 public class EventWeaver extends ClassVisitor implements Opcodes, AsmTypes, AsmMethods 中 的 
return new ReWriteMethod下。

1.添加两个个新方法      
            private boolean isNonReturn(int opcode) {
                return opcode == RETURN;
            }      
/**
             * 流程控制
             */
            private void processControlAfter() {
                final Label finishLabel = new Label();
                final Label returnLabel = new Label();
                final Label throwsLabel = new Label();
                dup();
                visitFieldInsn(GETFIELD, ASM_TYPE_SPY_RET, "state", ASM_TYPE_INT);
                dup();
                push(Spy.Ret.RET_STATE_RETURN);
                ifICmp(EQ, returnLabel);
                push(Spy.Ret.RET_STATE_THROWS);
                ifICmp(EQ, throwsLabel);
                goTo(finishLabel);
                mark(returnLabel);
                pop();
                swap();
                pop();
                visitFieldInsn(GETFIELD, ASM_TYPE_SPY_RET, "respond", ASM_TYPE_OBJECT);
                checkCastReturn(Type.getReturnType(desc));
                goTo(finishLabel);
                mark(throwsLabel);
                visitFieldInsn(GETFIELD, ASM_TYPE_SPY_RET, "respond", ASM_TYPE_OBJECT);
                checkCast(ASM_TYPE_THROWABLE);
                throwException();
                mark(finishLabel);
                pop();
            }

2.修改一个 方法
            @Override
            protected void onMethodExit(final int opcode) {
                if (!isThrow(opcode)) {
                    if(!isNonReturn(opcode)){
                        codeLockForTracing.lock(new CodeLock.Block() {
                            @Override
                            public void code() {
                                loadReturn(opcode);
                                push(namespace);
                                push(listenerId);
                                invokeStatic(ASM_TYPE_SPY, ASM_METHOD_Spy$spyMethodOnReturn);
                                processControlAfter();
                            }
                        });
                    }else {
                        codeLockForTracing.lock(new CodeLock.Block() {
                            @Override
                            public void code() {
                                loadReturn(opcode);
                                push(namespace);
                                push(listenerId);
                                invokeStatic(ASM_TYPE_SPY, ASM_METHOD_Spy$spyMethodOnReturn);
                                processControl();
                            }
                        });
                    }

                }
            }

**Comment by xiaoxiaocaiiao** [comment]
这里面 有 构造器的问题所以 只有 有返回值需要多pop一次

**Comment by z529192557** [comment]
这里有些不严谨的地方，我再看看，解决ARETURN是够了， 如果是LRETURN或DRETURN，似乎应该 用POP2

**Comment by xiaoxiaocaiiao** [comment]
关键是看 [Ret.respond, object] 中的 object 是什么类型，因为我们要移除掉的是object。

**Comment by xiaoxiaocaiiao** [comment]
似乎如果出现了 lreturn 和drentrun swap 是不是也会有问题，具体我没有调查过。我当时想的比较好的办法是定义变量来 存 返回值 需要的时候取出来 用完就释放掉，这样是最靠谱的做法。只是当时为了尽快解决就修复了areturn 的。

**Comment by oldmanpushcart** [comment]
@xiaoxiaocaiiao hello，可以提一个PR么？我们merge进去

**Comment by oldmanpushcart** [comment]
已发布1.4.0，多谢
