### ISSUE TITLE
在外部部署了jvm-sandbox的增强程序，如何链接到POD内的springBoot进程？

### ISSUE THREAD

**Issue by yangcoolq** [alibaba/jvm-sandbox#330]
加入项目是K8S+Docker方式部署，请问在不改变Docker镜像情况下，怎么利用jvm-sandbox连接到容器里的PID？

**Comment by orangle** [comment]
写crd或者执行exec。是想在宿主机直接attach?

**Comment by yangcoolq** [comment]
> 
> 
> 写crd或者执行exec。是想在宿主机直接attach?

是的，我希望在宿主机上就能连上pod内的进程，否则要改造镜像，太麻烦。

**Comment by BetaLi** [comment]
这个问题有进展么？我也是想直接attach到pod里面的进程

**Comment by yangcoolq** [comment]
> 
> 
> 这个问题有进展么？我也是想直接attach到pod里面的进程

没进展，要等官方回复

**Comment by orangle** [comment]
我知道的方案就是crd 用operator实现的

**Comment by orangle** [comment]
> 这个问题有进展么？我也是想直接attach到pod里面的进程
为啥要这么做？ 在宿主上做安全问题不是更大？

**Comment by Ammyz** [comment]
请问K8S+Docker方式部署的如何解决比较好呢？

**Comment by oldmanpushcart** [comment]
官方表示这个是运维问题，不在jvm-sandbox中解决。我对K8S也不熟，建议去K8S相关社区请教哦
