### ISSUE TITLE
Sandbox 注入java.lang.ClassFormatError: null at retransformClasses

### ISSUE THREAD

**Issue by Wadud-Ma** [alibaba/jvm-sandbox#333]
![image](https://user-images.githubusercontent.com/46469804/126090637-9d7045b1-cd3d-4cf5-a42b-e480c623335b.png)

**Comment by oldmanpushcart** [comment]
能贴出你watch的代码么，我想知道你在观察那个方法，好重现此问题

**Comment by dbjzx** [comment]
这个问题我也遇到，后来咋解决的呢
