### ISSUE TITLE
如何理解文档中说到的 “多租户” ？

### ISSUE THREAD

**Issue by lemon-simple** [alibaba/jvm-sandbox#334]
文档中提到
-------------------
沙箱的特性
无侵入：目标应用无需重启也无需感知沙箱的存在
类隔离：沙箱以及沙箱的模块不会和目标应用的类相互干扰
可插拔：沙箱以及沙箱的模块可以随时加载和卸载，不会在目标应用留下痕迹
多租户：目标应用可以同时挂载不同租户下的沙箱并独立控制
高兼容：支持JDK[6,11]
--------------------------------------

意思是目标应用 可以同时挂载多个沙箱吗？这个算多租户？什么场景会这么做？ 感谢解答。

**Comment by oldmanpushcart** [comment]
名词解释：多租户；同一个JVM进程，可以独立的挂载多个不同的jvm-sandbox，并独立加载各自的模块。当然，如果对名词定义不精准我们可以完善和修改，也欢迎提出建议哦。

适用场景：客户自己内部采用了sandbox完成部分模块，阿里云内部也有工具采用了sandbox完成特定运维功能。但两者的模块属于两个独立机构，不可能统一部署管理。这种情况下sandbox的多租户模式就可以发挥优势。阿里云和客户都可以独立的对同一个JVM进程加载自己的sandbox而不会相互干扰。

核心原理：框架内部给每个jvm-sandbox都开了不同的用户空间，并对同一份代码增强时进行了隔离识别，以此保持相互之间的独立。
