### ISSUE TITLE
请问我在使用processcontroller.returnimmediately(object)的时候 无法构造mock对象 要怎么处理呢  

### ISSUE THREAD

**Issue by Maginx** [alibaba/jvm-sandbox#336]

**Comment by Maginx** [comment]
提示castclassexcpetion 异常，有什么办法可以获取到jvm进程中的classloader进行mock对象实例化嘛

**Comment by ijustyce** [comment]
@Maginx 我遇到了同样的问题，你解决了没呢？方便讨论下嘛？我的场景是，使用了mybatis，然后将基本的增删改查丢到了泛型的父类里面，子类继承父类并指定泛型的类型，在这儿 return 时就会报错，告诉我 classcastexception cannot cast 子类 to 父类 …

**Comment by tmaerd** [comment]
> @Maginx 我遇到了同样的问题，你解决了没呢？方便讨论下嘛？我的场景是，使用了mybatis，然后将基本的增删改查丢到了泛型的父类里面，子类继承父类并指定泛型的类型，在这儿 return 时就会报错，告诉我 classcastexception cannot cast 子类 to 父类 …

需要将在module中定义的类,使用宿主classloader进行加载,如javaasssit实现:
 protected void before(Advice advice) throws Throwable {
                        ClassPool pool = ClassPool.getDefault();
                        pool.insertClassPath(new ClassClassPath(A.class));
                        CtClass ctClass= pool.get("com.A");
                        ctClass.toClass(advice.getLoader(), null);
                        Class<?> loadClass = ctClass.toClass(advice.getLoader(), null);
                        // 通过ProcessController来改变原有方法的执行流程
                        ProcessController.returnImmediately(loadClass.newInstance());
    }

**Comment by oldmanpushcart** [comment]
@Maginx 在`BeforeEvent.javaClassLoader`可以拿到对应的ClassLoader，当然像 @tmaerd 一样从Advice中拿会更方便。

**Comment by reducm** [comment]
对于泛型的获取，录制与Mock的过程都有各种不同情况，简单的原则是，原来代码的泛型类型定义在哪里(类 方法返回 方法参数)就从哪里获取

例如GuavaCache，get的真实返回值的，要回塑到CacheBuilder的动态load方法的签名，通过反射就能获取
