### ISSUE TITLE
module加载失败，且没有log

### ISSUE THREAD

**Issue by zhaoxi0703** [alibaba/jvm-sandbox#340]
用户自定义module加载失败，sandbox-controller也没有加载成功
![image](https://user-images.githubusercontent.com/65761046/127837598-18507f0f-1441-4f7b-bfa2-a5b9902a1a07.png)
同时，也没有在~/目录下生成logs目录，无法排查
请问是什么原因呢？只安装了jre，没有安装jdk，是否跟这个有关系？

**Comment by oldmanpushcart** [comment]
错误日志在目标jvm的主日志中，可以找找
