### ISSUE TITLE
windows 下 启动sandbox无日志无异常信息

### ISSUE THREAD

**Issue by zhenjia001** [alibaba/jvm-sandbox#342]
打包后，手工执行
java  -Xbootclasspath/a:C:\Java\jdk1.8.0_231\lib\tools.jar -Xms128M -Xmx128M -Xnoclassgc -ea -jar sandbox-core.jar 35988 sandbox-agent.jar "home=D:\sandbox;server.ip=127.0.0.1;server.port=3356"
启动无任何日志，url访问返回404
最终定位缺少cfg目录
需要修改LogbackUtils.init，如果没有目录抛出异常并且打印日志，判断logbackCfgFilePath变量

**Comment by oldmanpushcart** [comment]
最终你解决了这个问题了么？
日志在目标jvm的默认日志中
