### ISSUE TITLE
pgrep -U 无法识别，与容器里的pgrep指令不匹配

### ISSUE THREAD

**Issue by yangcoolq** [alibaba/jvm-sandbox#343]
cat: can't open '/root/.sandbox.token': No such file or directory
+ test -n '' -a -z ''
+ check_permission
+ pgrep java
+ grep 1
+ pgrep -U root
+ grep 1
**pgrep: unrecognized option: U**
BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.

Usage: pgrep [-flanovx] [-s SID|-P PPID|PATTERN]

Display process(es) selected by regex PATTERN

	-l	Show command name too
	-a	Show command line too
	-f	Match against entire command line
	-n	Show the newest process only
	-o	Show the oldest process only
	-v	Negate the match
	-x	Match whole name (not substring)
	-s	Match session ID (0 for current)
	-P	Match parent process ID
+ exit_on_err 1 'permission denied, root is not allow attach to 1.'
+ [[ -n permission denied, root is not allow attach to 1. ]]
+ echo 'permission denied, root is not allow attach to 1.'
permission denied, root is not allow attach to 1.

_____________________________________________________
以上问题，其他人也提到过

**Comment by oldmanpushcart** [comment]
@z529192557 在docker下有遇到pgrep不可用么？我没有docker环境的经验。
@yangcoolq 能否帮助我们完善呢

1. 小建议：不要用root来执行
2. 期待回馈：我们没有你的环境比较难重现问题，sandbox.sh建议在实际公司部署的时候根据自己的环境情况进行修改，同时我们也很乐意能接收到你的pull-request
