### ISSUE TITLE
您好，是否可支持JDK17的版本

### ISSUE THREAD

**Issue by quanjun5428** [alibaba/jvm-sandbox#347]
您好，我们新建设的系统使用JDK17的版本，并在应用chaosblade开展混沌测试，但chaosblade不支持JDK17。chaosblade底层依赖于jvm-sandbox，需要jvm-sandbox支持JDK17，请问诸位大佬是否可以支持，感谢！

**Comment by qobin** [comment]
我们也在测试jdk17，用jvm-sandbox-repeater 录制回放时发现mybatis也是很多问题，暂时没排查到时jvm-sandbox 还是repeater、又或者时mybatis的问题，请问 jvm-sandbox支持JDK17目前发现有什么问题吗？

**Comment by oldmanpushcart** [comment]
在`1.4.0`版本中支持，可以关注分支[develop-for-20220822](https://github.com/alibaba/jvm-sandbox/tree/develop-for-20220822)

**Comment by oldmanpushcart** [comment]
1.4.0已支持

**Comment by peterZhang000** [comment]
> 1.4.0已支持

这个分支，sdk还是1.8？还是jdk17?

**Comment by ljqseu** [comment]
这个分支看起来是jdk8? 依赖里还有tools.jar
<img width="560" alt="image" src="https://github.com/alibaba/jvm-sandbox/assets/50127039/2090f13b-ffc9-4922-a78b-02fca45fd45c">
