### ISSUE TITLE
java.lang.ClassNotFoundException:com.alibaba.jvm.sandbox.agent.AgentLauncher

### ISSUE THREAD

**Issue by itrenjie** [alibaba/jvm-sandbox#359]
环境：Linux
sandbox版本：1.3.1
现象：UrlClassLoader调用findClass方法时找不到AgentLauncher，  用同样的sandbox代码在Windows上可以找到这个类，linux上找不到。

**Comment by code-bez** [comment]
收到

**Comment by itrenjie** [comment]
问题原因找到了，大致原因是公司对springBoot又做了一层封装导致javaAgent在对JVM做侵入后，目标服务器的classLoader
没能加载到agent.jar的路径
