### ISSUE TITLE
现在项目希望全部推行sandbox，有全部的demo样例吗，demo只要线上故障模拟？？

### ISSUE THREAD

**Issue by lizhichao999** [alibaba/jvm-sandbox#36]
线上故障定位
线上系统流控
线上故障模拟
方法请求录制和结果回放
动态日志打印
安全信息监测和脱敏
行链路计算和覆盖率统计

**Comment by dongchenxu** [comment]
这些项目都是阿里内部真实使用sandbox的实战项目，但因为是实战的项目，所以不方便放出demo，不过我们可以在钉钉群里面沟通，帮你解决一些技术难点哦～
