### ISSUE TITLE
vulnerability issue with  commons-io:commons-io: 2.4

### ISSUE THREAD

**Issue by JohnMatty** [alibaba/jvm-sandbox#361]
https://github.com/alibaba/jvm-sandbox/blob/master/sandbox-core/pom.xml#L129

Please update to the version to the 2.5.   The current version 2.4 has vulnerabilities.
Chaosblade uses this jar file and it has been flagged with vulnerability.

Please fix it. Appreciate it.

**Comment by JohnMatty** [comment]
I see that there is a pull request already for this issue. Please push this.
https://github.com/alibaba/jvm-sandbox/pull/323

**Comment by oldmanpushcart** [comment]
maybe I will, but not the right time.
