### ISSUE TITLE
可不可以将sandbox需要的组件和编写的module全部打包的agent中,通过agent的方式启动生效,不用sh命令触发

### ISSUE THREAD

**Issue by tmaerd** [alibaba/jvm-sandbox#365]
可不可以将sandbox需要的组件和编写的module全部打包的agent中,通过agent的方式启动生效,不用sh命令
有些业务场景中单纯的想使用sandbox的类隔离以及增强功能,

**Comment by luutqf** [comment]
是因为需要热加载,无必要的module没必要加载的. 如果你愿意,也可以直接把实现放在agent中,然后在doMethod()添加一些自己的逻辑替换掉coreModuleManager.get(uniqueId);

**Comment by oldmanpushcart** [comment]
https://github.com/alibaba/jvm-sandbox/wiki/INSTALL#agent%E6%96%B9%E5%BC%8F%E5%90%AF%E5%8A%A8
这个agent模式启动是不是你想要的？

**Comment by tmaerd** [comment]
已有方案,谢谢回复
