### ISSUE TITLE
./sandbox.sh -p 71816 -X 被注入项目报错

### ISSUE THREAD

**Issue by ad-duyb** [alibaba/jvm-sandbox#366]
被注入项目报 Full thread dump Java HotSpot(TM) 64-Bit Server VM (11.0.7+8-LTS mixed mode): 有没有遇到过？怎么解决的？

**Comment by oldmanpushcart** [comment]
可能要更多一些的错误信息，这个感觉不应该是会出的信息，这一行应该是执行了jstack而不是执行了sandbox
