### ISSUE TITLE
时钟的例子成功执行但时钟没修复

### ISSUE THREAD

**Issue by chrischjh** [alibaba/jvm-sandbox#37]
你好，

我在尝试时钟修复的例子的时候，植入成功，两个修复命令都执行了没有报错，但是时钟却没有被修复，会是什么原因呢？

**root@fde2808ec2a0:/home/xxxxx/.opt/sandbox/bin#** ./sandbox.sh -p 2524
                    NAMESPACE : default
                      VERSION : 0.1.0.2
                         MODE : ATTACH
                  SERVER_ADDR : localhost
                  SERVER_PORT : 33617
               UNSAFE_SUPPORT : ENABLE
                 SANDBOX_HOME : /home/xxxxx/.opt/sandbox/lib/..
            SYSTEM_MODULE_LIB : /home/xxxxx/.opt/sandbox/lib/../module
              USER_MODULE_LIB : ~/.sandbox-module;
          SYSTEM_PROVIDER_LIB : /home/xxxxx/.opt/sandbox/lib/../provider
           EVENT_POOL_SUPPORT : ENABLE
  EVENT_POOL_PER_KEY_IDLE_MIN : 50
  EVENT_POOL_PER_KEY_IDLE_MAX : 100
 EVENT_POOL_PER_KEY_TOTAL_MAX : 2000
             EVENT_POOL_TOTAL : 6000
**root@fde2808ec2a0:/home/xxxxx/.opt/sandbox/bin#** ./sandbox.sh -p 2524 -d 'broken-clock-tinker/repairCheckState'
**root@fde2808ec2a0:/home/xxxxx/.opt/sandbox/bin#** ./sandbox.sh -p 2524 -d 'broken-clock-tinker/repairDelay'
**root@fde2808ec2a0:/home/xxxxx/.opt/sandbox/bin#**

**Comment by chrischjh** [comment]
这是log

2018-01-24 08:38:30 INFO  waitingReTransformClassSet is empty, ignore reTransformClasses. module[id=broken-clock-tinker;];watchId=1002;
2018-01-24 08:38:30 INFO  active listener success. listener-id=6;listener=BrokenClockTinkerModule$1@24b0c1af;
2018-01-24 08:39:36 INFO  waitingReTransformClassSet is empty, ignore reTransformClasses. module[id=broken-clock-tinker;];watchId=1003;
2018-01-24 08:39:36 INFO  active listener success. listener-id=7;listener=BrokenClockTinkerModule$2@29d4110c;

**Comment by chrischjh** [comment]
看了另一个issue里的回复，匹配正则表达式后，成功了，谢谢！

**Comment by LLLucian** [comment]
怎么处理

**Comment by LLLucian** [comment]
使用root启用jar包也没反应

**Comment by williamfzc** [comment]
+1，
<img width="565" alt="image" src="https://user-images.githubusercontent.com/13421694/178143134-edd925a7-fdeb-4b0b-a9ab-36dbee534098.png">

从日志上看匹配不到任何类，完全放宽也匹配不上：

<img width="480" alt="image" src="https://user-images.githubusercontent.com/13421694/178143155-25ec8d11-1c28-4cff-8e6d-4f1aae7b7f5e.png">
