### ISSUE TITLE
请教一下jvm-sandbox repeater如何调试？

### ISSUE THREAD

**Issue by Mengleijin** [alibaba/jvm-sandbox#370]
jvm-sandbox repeater基于jvm-sandbox，请教一下如何debug？

**Comment by oldmanpushcart** [comment]
jvm-sandbox在完成attach到目标后，直接远程debug目标JVM即可

**Comment by Mengleijin** [comment]
@oldmanpushcart 谢谢大佬，我回头试一下，然后顺便问一下repeater中的入口流量（Http/Dubbo/Java）中的Java入口指的什么情况啊？
