### ISSUE TITLE
Deadlock when multiple javaagents

### ISSUE THREAD

**Issue by eightpigs** [alibaba/jvm-sandbox#371]
[SandboxClassLoader#loadClass](https://github.com/alibaba/jvm-sandbox/blob/3f6583b8eac6730c8414bb7e8a3f050e2a21931c/sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/SandboxClassLoader.java#L50) has a deadlock problem when use multiple javaagents.

### Related
- [BUG: SandboxClassLoader 死锁问题](https://github.com/alibaba/jvm-sandbox/issues/352)

### Reproduce

1. Custom a Sandbox module
    ```java
    new EventWatchBuilder(moduleEventWatcher, EventWatchBuilder.PatternType.REGEX)
      // more classes
      .onClass("com.aabbccddeeff.*")
      .includeSubClasses()
      .onAnyBehavior()
      .onWatch(event -> { }, Event.Type.BEFORE);
    ```
2. Load multiple javaagents at startup
    ```bash
    java -javaagent:/opt/skywalking-agent.jar -javaagent:/opt/sandbox-agent.jar` -jar /opt/app.jar
    ```

### Logs
- [deadlock-1.log](https://github.com/alibaba/jvm-sandbox/files/9349935/deadlock-1.log)
- [deadlock-2.log](https://github.com/alibaba/jvm-sandbox/files/9349937/deadlock-2.log)
- [deadlock-3.log](https://github.com/alibaba/jvm-sandbox/files/9349938/deadlock-3.log)

**Comment by oldmanpushcart** [comment]
个人经验：在onClass(...)的时候，你可能要更精确的控制要观察的类范围，这样可以比较有效的减少死锁冲突。
毕竟我们手头上没有skywalking的使用场景，很难去在本地复现这个问题

**Comment by eightpigs** [comment]
[SandboxClassLoader#loadClass](https://github.com/alibaba/jvm-sandbox/blob/3f6583b8eac6730c8414bb7e8a3f050e2a21931c/sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/SandboxClassLoader.java#L50) 的锁调整下可以解决:  
移除方法上的 `synchronized`，使用 JDK 7 的 `ClassLoader.registerAsParallelCapable()` 和 `getClassLoadingLock`（或者使用你们兼容的版本：`ClassLoadingLock`）

**Comment by oldmanpushcart** [comment]
多谢，这里修改略有反复，让我想想。我拉了一个分支解决这个问题。

**Comment by z529192557** [comment]
> [SandboxClassLoader#loadClass](https://github.com/alibaba/jvm-sandbox/blob/3f6583b8eac6730c8414bb7e8a3f050e2a21931c/sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/SandboxClassLoader.java#L50) 的锁调整下可以解决: 移除方法上的 `synchronized`，使用 JDK 7 的 `ClassLoader.registerAsParallelCapable()` 和 `getClassLoadingLock`（或者使用你们兼容的版本：`ClassLoadingLock`）

能提供一下使用的sandbox版本吗

**Comment by eightpigs** [comment]
> 能提供一下使用的sandbox版本吗
- 1.3.1
- 1.3.3

**Comment by z529192557** [comment]
> > 能提供一下使用的sandbox版本吗
> 
> * 1.3.1
> * 1.3.3
问题：为什么会有两个版本？是同时部署两个不同版本的sandbox在同一个进程中吗？

**Comment by eightpigs** [comment]
> 问题：为什么会有两个版本？是同时部署两个不同版本的sandbox在同一个进程中吗？

不是同时使用，是都使用过且存在该问题；比较容易复现：多个 javaagent 同时观察较多的类。

**Comment by eightpigs** [comment]
下面是我基于 JDK 7 的修复方式，由于前段时间 master 分支单测跑不过（[#355](https://github.com/alibaba/jvm-sandbox/pull/355#issuecomment-1216509498)），就没提 PR：

```diff
--- a/sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/SandboxClassLoader.java
+++ b/sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/SandboxClassLoader.java
@@ -19,6 +19,11 @@ class SandboxClassLoader extends URLClassLoader {
     private final String toString;
     private final String path;

+    static {
+        // 启用并行加载
+        ClassLoader.registerAsParallelCapable();
+    }
+
     SandboxClassLoader(final String namespace,
                        final String sandboxCoreJarFilePath) throws MalformedURLException {
         super(new URL[]{new URL("file:" + sandboxCoreJarFilePath)});
     SandboxClassLoader(final String namespace,
                        final String sandboxCoreJarFilePath) throws MalformedURLException {
         super(new URL[]{new URL("file:" + sandboxCoreJarFilePath)});
@@ -47,25 +52,22 @@ class SandboxClassLoader extends URLClassLoader {
     }

     @Override
-    protected synchronized Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
-        final Class<?> loadedClass = findLoadedClass(name);
-        if (loadedClass != null) {
-            return loadedClass;
-        }
-
-//        // 优先从parent（SystemClassLoader）里加载系统类，避免抛出ClassNotFoundException
-//        if(name != null && (name.startsWith("sun.") || name.startsWith("java."))) {
-//            return super.loadClass(name, resolve);
-//        }
+    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
+        synchronized (getClassLoadingLock(name)) {
+            final Class<?> loadedClass = findLoadedClass(name);
+            if (loadedClass != null) {
+                return loadedClass;
+            }

-        try {
-            Class<?> aClass = findClass(name);
-            if (resolve) {
-                resolveClass(aClass);
+            try {
+                Class<?> aClass = findClass(name);
+                if (resolve) {
+                    resolveClass(aClass);
+                }
+                return aClass;
+            } catch (Exception e) {
+                return super.loadClass(name, resolve);
             }
-            return aClass;
-        } catch (Exception e) {
-            return super.loadClass(name, resolve);
         }
     }
```

**Comment by z529192557** [comment]
getClassLoadingLock 会再次引起偶发性死锁，提升了锁冲突概率，这个内部版本已经出现多次，还是得想其他办法，通过堆栈分析是LocalCache$LocalManualCache 采用的类似JDK7中的ConrrentHashMap中的Segment段锁策略，如果LocalCache$LocalManualCache采用无锁化机制，可能会大大缓解死锁问题

**Comment by z529192557** [comment]
所以我还是想缓存转换的类接口所用的本地缓存，使用无锁化的Map实现，我先看看guava是否有相关的替代方案

**Comment by z529192557** [comment]
> getClassLoadingLock 会再次引起偶发性死锁，这个内部版本已经出现多次，还是得想其他办法，通过堆栈分析是LocalCache$LocalManualCache 采用的类似JDK7中的ConrrentHashMap中的Segment段锁策略，如果LocalCache$LocalManualCache采用无锁化机制，可能会大大缓解死锁问题，所以我还是想，先看看guava是否有相关的替代方案

deadlocak-1 升级到1.3.3应该可以解决，出现了SandboxClassTransformer转换sandbox自己类

**Comment by eightpigs** [comment]
从 guava 的 LocalCache 的实现上看，短期内不会有调整；

所以是否可以先使用 `getClassLoadingLock` 等方案细化锁粒度来降低死锁情况（如文档 [Multithreaded Custom Class Loaders in Java SE 7](https://docs.oracle.com/javase/7/docs/technotes/guides/lang/cl-mt.html) 所建议的方式优化）？

或者，重新评估下是否需要使用 guava 的 LocalCache？

**Comment by z529192557** [comment]
我分析了一下堆栈，有两个问题不明确
![Uploading image.png…]()
请问你们是否基于某个源码版本有过自己的修改

**Comment by z529192557** [comment]
![image](https://user-images.githubusercontent.com/9245774/187862618-4e3c280f-b7d3-4ba2-92b4-fb3fb4d77dc8.png)

**Comment by eightpigs** [comment]
日志的确是我们内部版本产生的，我使用上游版本多次验证后，没有复现该问题，我先关闭该 issue。

---

我仔细过了一遍我们维护的情况，发现我们的维护存在问题：**我们内部版本源码与上游是保持一致的，但打的包却没有及时跟上，导致源码有更新但 sandbox-*.jar 没有及时更新**。

排查问题时我只关注了维护的源码，未注意到打包版本的情况，且未使用上游版本验证复现。所以从 `SandboxClassLoader#loadClass` 的锁方面下手解决该问题，当内部不再复现后，遂提出该 issue 以希望帮助上游解决...

不好意思，由于我的不专业打扰几位的时间了。
