### ISSUE TITLE
这个项目有没有考虑过 国内外的顶级基金会孵化吗？进一步提升价值

### ISSUE THREAD

**Issue by lemon-simple** [alibaba/jvm-sandbox#372]

**Comment by oldmanpushcart** [comment]
感谢认同我们项目的价值

我们开源这个内核不是为了炫技的，而是带着使命和目的

1. 和pandora一样，成为基础设施，进入到每一个应用中
2. 能被阿里云采纳，进入到阿里云java运维标准组件

这两个目标需要我们把代码开源并做到公司对我们的性能指标要求，只有sandbox有足够多的用户，module才能有足够大的市场空间，后续开源的运营经费策略应该来自于module的收费。

回到主题，我们当前还在努力为这两个目标而奋斗，进入国内外的顶级基金会确实我们还没有渠道接触，更别提考虑这件事啦～
