### ISSUE TITLE
项目协议问题，目前看项目是LGPL和GPL协议，但看到又提到了Apache。能否确定下协议，如果是LPGL和GPL，后续有考虑改成Apache协议吗？不然使用该项目存在一些担忧

### ISSUE THREAD

**Issue by yananliuyanjiang** [alibaba/jvm-sandbox#375]

**Comment by oldmanpushcart** [comment]
多谢提醒，我们尽快和公司法务确认下，争取下周给个答复，确实存在一次转型。

**Comment by yananliuyanjiang** [comment]
好的，希望能有更松散的协议推动这个项目发展。目前协议规定的比较死，大家想基于该项目创新和发展有很多顾虑

**Comment by lemon-simple** [comment]
我们前期也遇到了同样问题……

**Comment by lemon-simple** [comment]
GPL协议限制性很大，而且有强传染性哇哈哈

**Comment by oldmanpushcart** [comment]
@lemon-simple 我们希望市场上类似的产品，竞争力来自于module而不是sandbox本身。所以就要求sandbox必须足够开放和透明，并也强制二次开发的竞争对手开放，逼迫竞争对手将核心竞争力集中在module功能上
