### ISSUE TITLE
使用Agent模式在启动时加载module导致启动时间明显变长

### ISSUE THREAD

**Issue by the-wang** [alibaba/jvm-sandbox#378]
公司基于sandbox开发了流量录制、mock等模块并且在线上线下大量应用。使用的是agent模式，在启动时加载module。

这种方式下带来一个明显问题，就是应用的启动时间急剧升高且波动剧烈，比如原本启动时间3分钟，在使用sandbox后会变成6分钟。

经排查发现主要耗时来自于SandboxClassFileTransformer，推测是因为启动时注册transformer，几乎所有的类都是第一次加载，此时并没有Class对象，SandboxClassFileTransformer的匹配逻辑会直接分析字节码来进行匹配，耗时较大。

想问下，在使用agent模式的同时，是否可以做到应用启动后再去加载module，通过Instrumentation.retransformClasses方式进行注入？此时由于类已经加载过了，匹配逻辑会变得非常轻量化，执行时间应该会降低许多。

**Comment by the-wang** [comment]
@oldmanpushcart 求支持！

**Comment by oldmanpushcart** [comment]
@the-wang 我们根据 #292 的建议优化了Matcher的代码，应该能缓解你遇到的agent的问题，当前他在分支[develop-for-20220822](https://github.com/alibaba/jvm-sandbox/tree/develop-for-20220822)上，欢迎测试哦

**Comment by the-wang** [comment]
> @the-wang 我们根据 #292 的建议优化了Matcher的代码，应该能缓解你遇到的agent的问题，当前他在分支[develop-for-20220822](https://github.com/alibaba/jvm-sandbox/tree/develop-for-20220822)上，欢迎测试哦

感谢回复，只是我们的场景下还真有根据接口类型进行匹配的，不过还有个特点就是我们只需要增强极少数的类。目前的现状就是为了增强个位数的类就要在启动过程中对几万个类的字节码进行解析匹配操作。如果等应用启动的差不多了再去加载module、注册transformer、通过retransfrom方式触发增强，那么相信效率能够提升更多。

**Comment by oldmanpushcart** [comment]
根据 #292 的建议，一共有两个性能损耗点`hasInterfaceTypes`和`hasAnnotationTypes`，所以还是会有一定的性能提升。

另外我看到你提到一个我感兴趣的关键点：“不过还有个特点就是我们只需要增强极少数的类”，那我换个核心思路，在应用启动的过程中不插入transformer，而是启动完成后再进行。

前提：只需要增强极少数的类

1. 是否可以用attach模式来加载呢？

2. 如果必须要用agent模式，可以在让module关闭加载时激活，

    ```java
    // 关闭modiule加载时激活
    @Information(isActiveOnLoad=false)
    ```

    然后在应用启动脚本中增加调用请求，在对应的请求`@Command`中完成watch，也能解决你的问题。
