### ISSUE TITLE
想问一下怎么访问被观测方法的入参？

### ISSUE THREAD

**Issue by QinFred2003** [alibaba/jvm-sandbox#38]
问题：
 想观察一下系统所有的对外发起HTTP的requestBody (基于Apache HTTPClient)，记录到log文件。 
` @Override`
   ` public CloseableHttpResponse execute(`
           ` final HttpUriRequest request,`
            `final HttpContext context) throws IOException, ClientProtocolException`
在观察的事件里面需要调用request.getURI()之类的方法

这里的HttpUriRequest,  HttpContext, CloseableHttpResponse 类在应用系统里面（Tomcat）均是被WebappClassLoader载入的， 在沙箱的模块代码里面如何访问这些应用的Class的？ 

我看了下沙箱项目的ClassLoader的设计和Class的隔离的管理，下面是我的理解，不知道是否有误：
1. 沙箱项目的Spy类在最顶级的BootstrapClassLoader被加载         
2. 被观察的系统的类按照其自己的设计和部署（比如Tomcat）, 用合适的ClassLoader载入自己相关目录资源下面的class.
3. 沙箱模块自己的Class由沙箱自己的SandboxClassLoader载入，包括用户使用的EventWatcher
4.在被观察模块里面注入对Spy类的调用(触发调用用户提供的Handler)

用户在自己的handler里面怎么才能访问到入参的Class呢？这里是要用ContextClassLoader来反射调用吗？

**Comment by dongchenxu** [comment]
你的理解没有问题，在自己的module/handler中想访问目标Class并调用，必须通过反射来完成。

**Comment by QinFred2003** [comment]
OK, 了解了。
