### ISSUE TITLE
疑似jdk11无法卸载jvm-sandbox

### ISSUE THREAD

**Issue by xl1605368195** [alibaba/jvm-sandbox#382]
1.系统：macos
2.JDK版本：jdk11
3.操作：attach 之后执行卸载
**./sandbox.sh -p 65682 -S**
4.使用jmap 查看 卸载是否正常：
～  jmap -histo:live 65682 | grep com.alibaba

![image](https://user-images.githubusercontent.com/26989019/190065513-ce09ae16-c155-4f9b-952a-bf118fad56c5.png)

使用 jprofile 查看堆内存 （仅剩下 sandbox-spy，**符合预期**）
![image](https://user-images.githubusercontent.com/26989019/190065362-b8e5b741-a815-4100-98d1-215209cfe606.png)
实时内存：（sandbox 没有卸载，执行full gc 依然不可卸载，**不符合预期**）
![image](https://user-images.githubusercontent.com/26989019/190065424-3f2afabf-f2f2-4b01-acce-5a6071584aeb.png)

jvm 启动参数 `-verbose:class` 没有观察到类卸载事件

----------------------------------
奇怪的是，使用jdk8来启动相同的服务，并执行与上面相同操作，**确可以卸载**。

![image](https://user-images.githubusercontent.com/26989019/190066414-6b79b89e-195f-4536-8b8b-0c0808bde077.png)

观察到类卸载事件：

![image](https://user-images.githubusercontent.com/26989019/190066334-165b7604-4216-48be-85c9-445142d61bd2.png)

jprofile 观察结果：

实时内存中没有sandbox，符合预期：
![image](https://user-images.githubusercontent.com/26989019/190066550-79b0007b-b1b3-4356-a9e3-05d013aa2876.png)

堆中没有sandbox，符合预期
![image](https://user-images.githubusercontent.com/26989019/190066684-4bcb2617-9080-4962-bfda-0fd4b744fda6.png)

注：linux 不同版本jdk没有测试；使用的版本是 在master1.3.3版本编译打包

**Comment by oldmanpushcart** [comment]
@xl1605368195 

我测试的JDK版本是JDK17没有重现你的问题
```shell
vlinux@B-3CT3Q05P-2050 ~ % java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

vlinux@B-3CT3Q05P-2050 bin % ./sandbox.sh -p 12628 -S
jvm-sandbox[default] shutdown finished.

vlinux@B-3CT3Q05P-2050 bin % jmap -histo:live 12628 | grep com.alibaba
  21:           512          16384  java.com.alibaba.jvm.sandbox.spy.Spy$SelfCallBarrier$Node
  66:             1           2064  [Ljava.com.alibaba.jvm.sandbox.spy.Spy$SelfCallBarrier$Node;
 569:             1             16  java.com.alibaba.jvm.sandbox.spy.Spy$SelfCallBarrier
```

执行多次没有重现。在JDK8的时候重现问题，但在一次FGC之后，内存被回收。
通过你的描述，在堆内存中不再出现spy之外的对象，但在`所有内存`中出现，这里需要进一步观察，这部分对象的引用关系类型，是否已经被降级为弱引用/幽灵引用/无引用，在下一次GC/FGC到来时候会被回收。如果是，那仍然还是符合设计预期的。

如果你还有疑问，方便的话可否把内存dump:live下来，我们做进一步探讨呢？

**Comment by oldmanpushcart** [comment]
@DayJun 收到可能debug模块中的例子有不合理的地方，我抽空重现。不过sandbox-core自身我们测试过，都能正确释放，请放心哈
