### ISSUE TITLE
JDK >= 11的条件下卸载sandbox会有内存泄漏的问题

### ISSUE THREAD

**Issue by DayJun** [alibaba/jvm-sandbox#384]
复现方法：

1. 在JDK 版本 >= 11的环境，注入sandbox，同时载入sandbox自带的debug模块。
2. 卸载sandbox
3. 使用jprofile查看实时内存，会发现sandbox大量对象
4. 使用jprofile创建堆快照，选择弱引用，同样会发现大量对象

可能原因：
有一部分的gc根会经过SandboxProtector，怀疑可能是Spy中经过isInProtecting调用产生了多余的threadLocal没有清理掉，我的处理办法是修改函数：
```
public boolean isInProtecting() {
        boolean res = isInProtectingThreadLocal.get().get() > 0;
        if(!res) {
            isInProtectingThreadLocal.remove();
        }
        return res;
    }
```
但是另外还有其他情况导致的泄漏

**Comment by oldmanpushcart** [comment]
收到，虽然我断时间无法确认，不过从代码上来看增加这部分代码将会让整个框架更严谨，所以我已经在分支 develop-for-20220822 中实现了你的建议。也希望你能切换这个分支，执行
```shell
./bin/package.sh
```
重新编译打包1.4.0-SNAPSHOT版本，再次进行尝试

**Comment by xl1605368195** [comment]
应该有个机制保证在卸载时能够完成清除线程变量。
比如：反射thread的remove 方法清除
