### ISSUE TITLE
wiki中很多链接点过去是原地跳转的

### ISSUE THREAD

**Issue by ztyqwe** [alibaba/jvm-sandbox#389]

**Comment by oldmanpushcart** [comment]
嗯，收到。我抽看了下，部分API介绍和沙箱Developer部分是空链接。空的原因是原计划预定的作者放鸽子了，我抽空补下。多谢提醒。

你想知道点什么，我知无不言。

**Comment by oldmanpushcart** [comment]
已修正空链接，暂无内容的去掉了链接，并补充了部分。
