### ISSUE TITLE
部分应用挂载sandbox报错

### ISSUE THREAD

**Issue by 15669072513** [alibaba/jvm-sandbox#392]
环境：jdk1.8  linux（centos）
多次挂载后报错信息如下：
*** Error in `java': double free or corruption (out): 0x00007fe582358d40 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7fe587d96329]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x6428b6)[0x7fe5873648b6]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x655e9a)[0x7fe587377e9a]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x46a1d8)[0x7fe58718c1d8]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x46b168)[0x7fe58718d168]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0xa3665c)[0x7fe58775865c]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x987271)[0x7fe5876a9271]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x98c42e)[0x7fe5876ae42e]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x98cca3)[0x7fe5876aeca3]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x483f14)[0x7fe5871a5f14]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0xac96e1)[0x7fe5877eb6e1]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0xad1765)[0x7fe5877f3765]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0xacfb3a)[0x7fe5877f1b3a]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0xacfebe)[0x7fe5877f1ebe]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0xad0330)[0x7fe5877f2330]
/usr/java/jdk1.8.0_131/jre/lib/amd64/server/libjvm.so(+0x927568)[0x7fe587649568]
/lib64/libpthread.so.0(+0x7ea5)[0x7fe588504ea5]
/lib64/libc.so.6(clone+0x6d)[0x7fe587e13b0d]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:01 16777369                           /usr/java/jdk1.8.0_131/jre/bin/java
00600000-00601000 rw-p 00000000 08:01 16777369                           /usr/java/jdk1.8.0_131/jre/bin/java
01d61000-01e10000 rw-p 00000000 00:00 0                                  [heap]
e0c00000-1013e0000 rw-p 00000000 00:00 0 
1013e0000-140000000 ---p 00000000 00:00 0 
7fe4d3f7f000-7fe4d3f9f000 rw-p 00000000 00:00 0 
7fe4d3f9f000-7fe4d417f000 ---p 00000000 00:00 0 
7fe4d417f000-7fe4d437f000 rw-p 00000000 00:00 0 
7fe4d437f000-7fe4d457f000 rw-p 00000000 00:00 0 
7fe4d4594000-7fe4d4597000 ---p 00000000 00:00 0 
7fe4d4597000-7fe4d4895000 rw-p 00000000 00:00 0 
7fe4d4895000-7fe4d4a95000 rw-p 00000000 00:00 0 
7fe4d4a95000-7fe4d4c95000 rw-p 00000000 00:00 0 
7fe4d4c95000-7fe4d4d7f000 r--s 01691000 08:01 4912862                    /tmp/sandbox_module_jar_1332486247427739497.jar
7fe4d4d7f000-7fe4d4d82000 ---p 00000000 00:00 0 
7fe4d4d82000-7fe4d4e80000 rw-p 00000000 00:00 0 
7fe4d4e80000-7fe4d4e83000 ---p 00000000 00:00 0 
7fe4d4e83000-7fe4d4f81000 rw-p 00000000 00:00 0 
7fe4d4f81000-7fe4d4f84000 ---p 00000000 00:00 0 
7fe4d4f84000-7fe4d5082000 rw-p 00000000 00:00 0 
7fe4d5082000-7fe4d5085000 ---p 00000000 00:00 0 
7fe4d5085000-7fe4d5183000 rw-p 00000000 00:00 0 
7fe4d5183000-7fe4d5186000 ---p 00000000 00:00 0 
7fe4d5186000-7fe4d5284000 rw-p 00000000 00:00 0 
7fe4d5284000-7fe4d5287000 ---p 00000000 00:00 0 
7fe4d5287000-7fe4d5385000 rw-p 00000000 00:00 0 
7fe4d5385000-7fe4d5388000 ---p 00000000 00:00 0 
7fe4d5388000-7fe4d5486000 rw-p 00000000 00:00 0 
7fe4d5486000-7fe4d5489000 ---p 00000000 00:00 0 
7fe4d5489000-7fe4d5587000 rw-p 00000000 00:00 0 
7fe4d5587000-7fe4d558a000 ---p 00000000 00:00 0 
7fe4d558a000-7fe4d5688000 rw-p 00000000 00:00 0 
7fe4d5688000-7fe4d568b000 ---p 00000000 00:00 0 
7fe4d568b000-7fe4d5989000 rw-p 00000000 00:00 0 
7fe4d5989000-7fe4d598c000 ---p 00000000 00:00 0 
7fe4d598c000-7fe4d5c8a000 rw-p 00000000 00:00 0 
7fe4d5c8a000-7fe4d5e8a000 rw-p 00000000 00:00 0 
7fe4d5e8a000-7fe4d608a000 rw-p 00000000 00:00 0 
7fe4d608a000-7fe4d608d000 ---p 00000000 00:00 0 
7fe4d608d000-7fe4d618b000 rw-p 00000000 00:00 0 
7fe4d618b000-7fe4d618e000 ---p 00000000 00:00 0 
7fe4d618e000-7fe4d628c000 rw-p 00000000 00:00 0 
7fe4d628c000-7fe4d628f000 ---p 00000000 00:00 0 
7fe4d628f000-7fe4d638d000 rw-p 00000000 00:00 0 
7fe4d638d000-7fe4d6390000 ---p 00000000 00:00 0 
7fe4d6390000-7fe4d668e000 rw-p 00000000 00:00 0 
7fe4d668e000-7fe4d6691000 ---p 00000000 00:00 0 
7fe4d6691000-7fe4d678f000 rw-p 00000000 00:00 0 
7fe4d678f000-7fe4d6792000 ---p 00000000 00:00 0 
7fe4d6792000-7fe4d6890000 rw-p 00000000 00:00 0 
7fe4d6890000-7fe4d6893000 ---p 00000000 00:00 0 
7fe4d6893000-7fe4d6991000 rw-p 00000000 00:00 0 
7fe4d6991000-7fe4d6994000 ---p 00000000 00:00 0 
7fe4d6994000-7fe4d6a92000 rw-p 00000000 00:00 0 
7fe4d6a92000-7fe4d6a95000 ---p 00000000 00:00 0 
7fe4d6a95000-7fe4d6b93000 rw-p 00000000 00:00 0 
7fe4d6b93000-7fe4d6b96000 ---p 00000000 00:00 0 
7fe4d6b96000-7fe4d6c94000 rw-p 00000000 00:00 0 
7fe4d6c94000-7fe4d6c97000 ---p 00000000 00:00 0 
7fe4d6c97000-7fe4d6d95000 rw-p 00000000 00:00 0 
7fe4d6d95000-7fe4d6d98000 ---p 00000000 00:00 0 
7fe4d6d98000-7fe4d6e96000 rw-p 00000000 00:00 0 
7fe4d6e96000-7fe4d6e99000 ---p 00000000 00:00 0 
7fe4d6e99000-7fe4d6f97000 rw-p 00000000 00:00 0 
7fe4d6f97000-7fe4d6f9a000 ---p 00000000 00:00 0 
7fe4d6f9a000-7fe4d7098000 rw-p 00000000 00:00 0 
7fe4d7098000-7fe4d709b000 ---p 00000000 00:00 0 
7fe4d709b000-7fe4d7199000 rw-p 00000000 00:00 0 
7fe4d7199000-7fe4d719c000 ---p 00000000 00:00 0 
7fe4d719c000-7fe4d729a000 rw-p 00000000 00:00 0 
7fe4d729a000-7fe4d729d000 ---p 00000000 00:00 0 
7fe4d729d000-7fe4d739b000 rw-p 00000000 00:00 0 
7fe4d739b000-7fe4d739e000 ---p 00000000 00:00 0 
7fe4d739e000-7fe4d749c000 rw-p 00000000 00:00 0 
7fe4d749c000-7fe4d749f000 ---p 00000000 00:00 0 
7fe4d749f000-7fe4d759d000 rw-p 00000000 00:00 0 
7fe4d759d000-7fe4d75a0000 ---p 00000000 00:00 0 
7fe4d75a0000-7fe4d7a9f000 rw-p 00000000 00:00 0 
7fe4d7a9f000-7fe4d7aa2000 ---p 00000000 00:00 0 
7fe4d7aa2000-7fe4d7ba0000 rw-p 00000000 00:00 0 
7fe4d7ba0000-7fe4d7ba3000 ---p 00000000 00:00 0 
7fe4d7ba3000-7fe4d7ca1000 rw-p 00000000 00:00 0 
7fe4d7ca1000-7fe4d7ca4000 ---p 00000000 00:00 0 
7fe4d7ca4000-7fe4d81a3000 rw-p 00000000 00:00 0 
7fe4d81a3000-7fe4d81a6000 ---p 00000000 00:00 0 
7fe4d81a6000-7fe4d86a5000 rw-p 00000000 00:00 0 
7fe4d86a5000-7fe4d86a8000 ---p 00000000 00:00 0 
7fe4d86a8000-7fe4d87a6000 rw-p 00000000 00:00 0 
7fe4d87a6000-7fe4d87a9000 ---p 00000000 00:00 0 
7fe4d87a9000-7fe4d88a7000 rw-p 00000000 00:00 0 
7fe4d88a7000-7fe4d88aa000 ---p 00000000 00:00 0 
7fe4d88aa000-7fe4d89a8000 rw-p 00000000 00:00 0 
7fe4d89a8000-7fe4d89ab000 ---p 00000000 00:00 0 
7fe4d89ab000-7fe4d8eaa000 rw-p 00000000 00:00 0 
7fe4d8eaa000-7fe4d8ead000 ---p 00000000 00:00 0 
7fe4d8ead000-7fe4d8fab000 rw-p 00000000 00:00 0 
7fe4d8fab000-7fe4d8fae000 ---p 00000000 00:00 0 
7fe4d8fae000-7fe4d94ad000 rw-p 00000000 00:00 0 
7fe4d94ad000-7fe4d94b0000 ---p 00000000 00:00 0 
7fe4d94b0000-7fe4d95ae000 rw-p 00000000 00:00 0 
7fe4d95ae000-7fe4d95b1000 ---p 00000000 00:00 0 
7fe4d95b1000-7fe4d98af000 rw-p 00000000 00:00 0 
7fe4d98af000-7fe4d98b2000 ---p 00000000 00:00 0 
7fe4d98b2000-7fe4d99b0000 rw-p 00000000 00:00 0 
7fe4d99b0000-7fe4d99b3000 ---p 00000000 00:00 0 
7fe4d99b3000-7fe4d9cb1000 rw-p 00000000 00:00 0 
7fe4d9cb1000-7fe4d9cb4000 ---p 00000000 00:00 0 
7fe4d9cb4000-7fe4d9db2000 rw-p 00000000 00:00 0 
7fe4d9db2000-7fe4d9db5000 ---p 00000000 00:00 0 
7fe4d9db5000-7fe4d9eb3000 rw-p 00000000 00:00 0 
7fe4d9eb3000-7fe4d9eb6000 ---p 00000000 00:00 0 
7fe4d9eb6000-7fe4d9fb4000 rw-p 00000000 00:00 0 
7fe4d9fb4000-7fe4d9fb7000 ---p 00000000 00:00 0 
7fe4d9fb7000-7fe4da0b5000 rw-p 00000000 00:00 0 
7fe4da0b5000-7fe4da0b8000 ---p 00000000 00:00 0 
7fe4da0b8000-7fe4da3b6000 rw-p 00000000 00:00 0 
7fe4da3b6000-7fe4da3b9000 ---p 00000000 00:00 0 
7fe4da3b9000-7fe4da4b7000 rw-p 00000000 00:00 0 
7fe4da4b7000-7fe4da4ba000 ---p 00000000 00:00 0 
7fe4da4ba000-7fe4da5b8000 rw-p 00000000 00:00 0 

只在某些应用存在这个问题。一般2次后就会出现这个问题。

**Comment by 15669072513** [comment]
问下作者在调用Java本地库的代码中有没有做多线程安全的措施

**Comment by 15669072513** [comment]
已解决，挂载多个Java agent引起的多线程调用Java本地库的问题，skywalking有个参数设置为true可以避免这个问题，但是还是会偶然复现。暂时解决了部分。

**Comment by oldmanpushcart** [comment]
@15669072513 这里问题有没有规避的方案？

**Comment by 15669072513** [comment]
如果是自己写的代码在调用本地native库的时候可以加上同步代码synchronized，如果是用的现成的中间件，需要找找参数是否可以解决这个问题。
