### ISSUE TITLE
最新快照版启动报错

### ISSUE THREAD

**Issue by ilaotan** [alibaba/jvm-sandbox#394]
Invalid initial heap size: -Xms128M -Xmx128M -Xnoclassgc -ea -Xbootclasspath/a:/usr/java/jdk1.8.0_191-amd64/lib/tools.jar

经过与老版本对比，
https://github.com/alibaba/jvm-sandbox/blob/master/bin/sandbox.sh#L256 这行的  "${SANDBOX_JVM_OPS}"   加了双引号导致的 
可能与系统有关？ 有类似错误的自己改下吧

**Comment by oldmanpushcart** [comment]
收到，多谢提醒。最近更新了插件，统一格式化了部分shell代码，当前正在处于写单元测试阶段，这类错误会在最终release之前的回归中纠正。
