### ISSUE TITLE
可以运行时给方法/类添加注解吗

### ISSUE THREAD

**Issue by toohandsome** [alibaba/jvm-sandbox#399]
我们有个系统根据 方法/类上 是否有注解决定是否记录日志，是否可以借助 jvm-sandbox 在运行时动态 给指定的类/方法 加上注解？

**Comment by oldmanpushcart** [comment]
不可以，jvm-sandbox只能去做到AOP的功能，不去做修改类/方法的定义。从我个人的经验来看，我必须指出“非正式途径提供变更线上代码逻辑的行为，不是一个好的运维习惯”。
