### ISSUE TITLE
如何集成到one java agent

### ISSUE THREAD

**Issue by shenba299** [alibaba/jvm-sandbox#400]
我们需要用agent的方式启动，并且需要和其他agent一块集成到one java agent ，因为sandbox的sandbox-agent.jar不是个完整包，所以想问下要怎么集成

**Comment by oldmanpushcart** [comment]
我阅读了one-java-agent项目的README，里面有一章节 (迁移)[https://github.com/alibaba/one-java-agent#%E8%BF%81%E7%A7%BB]，按照上边的实现应该可以满足你的需求。

需要对`com.alibaba.jvm.sandbox.agent.AgentLauncher'和sandbox-core.jar的打包方式做一些改变。不过当前我还没收到公司内部要求统一整合到one-java-agent的要求，所以短期内我也不会去提供这个功能。

这两个都是开源的项目，你可以自己根据你的需要做一些修改和调整。

**Comment by shenba299** [comment]
你好,我是黄荣鹏,你的邮件我已经收到了,祝你生活愉快！！！
