### ISSUE TITLE
修复破损的钟失败，执行了命令，还是在报错

### ISSUE THREAD

**Issue by TreeFireMen** [alibaba/jvm-sandbox#401]
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/54127694/208868839-b982e1bb-aac3-4767-9ebb-6205bf0038e3.png">
打包的module
<img width="949" alt="image" src="https://user-images.githubusercontent.com/54127694/208868990-33de86f7-a654-4b86-a35f-535b6189f691.png">

**Comment by oldmanpushcart** [comment]
你执行的命令和sandbox.log都提供下？
