### ISSUE TITLE
能不能搞个可视化界面呀？感觉还是很难上手

### ISSUE THREAD

**Issue by LyingDragons** [alibaba/jvm-sandbox#403]
日志在哪里添加这些没看懂

**Comment by oldmanpushcart** [comment]
抱歉哦，基于jvm-sandbox的定位出发，我想不到可视化的界面如何才能帮助大家快速上手。我在钉钉群中解答的很多问题也不像可以通过可视化界面解决的，你在上手的过程中是遇到什么困难了么？或者你认为对那一部分提供可视化的工具能更好的帮助到更多人呢？
