### ISSUE TITLE
这款工具与Arthas的区别在哪里?有什么优劣吗?

### ISSUE THREAD

**Issue by shiliang-star** [alibaba/jvm-sandbox#405]

**Comment by oldmanpushcart** [comment]
jvm-sandbox和arthas的关系，看这篇网文说得挺好的 [解密阿里线上问题诊断工具Arthas和jvm-sandbox](https://blog.51cto.com/u_14980978/2544726)

arthas的定位是故障定位工具，他最厉害的地方是用几个命令沉淀了多年来高级程序员定位故障的经验，这几个关键的命令是必须基于对方法的AOP拦截来实现。arthas的优点是**专业**。与之对应的是他缺点，arthas的缺点是他优点的另一面**封闭**。除了故障定位相关的功能，其他AOP能做到的事情他一律不做。做出这样的取舍也是为了能聚焦做好一件事情上。

基于arthas的选择是做好故障定位工具，jvm-sandbox的定位是做好AOP框架，基于AOP可以实现的所有功能jvm-sandbox一概不做，专注在把JVM的方法AOP做到极致。

以上就是我对两个工具的定位分析，希望能解答你的疑惑。
