### ISSUE TITLE
请问哪里有更详尽的使用文档、用户手册呢？

### ISSUE THREAD

**Issue by haicc-wang** [alibaba/jvm-sandbox#408]
作为一个新手，想了解更多场景化的解决问题的步骤、示例工程。
看了下wiki，都是介绍项目的架构。

具体一点，现在有个java工程，我想给某个bean的某个方法增加日志，从0到1怎么做？

**Comment by oldmanpushcart** [comment]
不知道这两篇文章是否能帮助到你
- [修复一个损坏了的钟](https://github.com/alibaba/jvm-sandbox/wiki/MDEV-FIRST-MODULE)
- [利用JVM-SANDBOX窥探JVM应用的SOCKET数据](https://github.com/oldmanpushcart/sandbox-module-example/blob/master/README.md)

**Comment by haicc-wang** [comment]
> 不知道这两篇文章是否能帮助到你
> 
> * [修复一个损坏了的钟](https://github.com/alibaba/jvm-sandbox/wiki/MDEV-FIRST-MODULE)
> * [利用JVM-SANDBOX窥探JVM应用的SOCKET数据](https://github.com/oldmanpushcart/sandbox-module-example/blob/master/README.md)

非常感谢你的回复，我去看一下
