### ISSUE TITLE
关于Windows平台部署jvm-sandbox的可行性

### ISSUE THREAD

**Issue by UchihaYong** [alibaba/jvm-sandbox#412]
您好，
想请教下是否有计划支持在Windows平台部署呢？是只需要修改那些sh脚本就可以吗？还是说一些源码也依赖Linux系统？

**Comment by code-bez** [comment]
收到

**Comment by UchihaYong** [comment]
emmm，是后续会支持的意思吗？现在如果我想在Windows部署，只需要改造sandbox.sh脚本即可？

**Comment by UchihaYong** [comment]
> 

emmm，是后续会支持的意思吗？现在如果我想在Windows部署，只需要改造sandbox.sh脚本即可？

**Comment by oldmanpushcart** [comment]
@UchihaYong jvm-sandbox是纯Java写的，天然跑在windows上不会有任何问题。唯一的障碍就是`sandbox.sh`是bash脚本，所以你如果想在windows上部署，直接改这个脚本即可。

**Comment by UchihaYong** [comment]
@oldmanpushcart 谢谢！

**Comment by UchihaYong** [comment]
我发现在windows下获取插件路径的时候，文件分隔符写死了Linux的 / ，要在PathUtils下要稍微改改。

**Comment by oldmanpushcart** [comment]
@UchihaYong 不可能吧，我特意走查了一遍，没发现写死了文件分割符，这点还是非常注意的。而且sandbox也没`PathUtils`这个类呀

**Comment by UchihaYong** [comment]
@oldmanpushcart 不好意思，弄错了。是基于sandbox开发的sandbox-repeater的问题。。。。

**Comment by UchihaYong** [comment]
[https://github.com/alibaba/jvm-sandbox-repeater/blob/master/repeater-plugin-core/src/main/java/com/alibaba/jvm/sandbox/repeater/plugin/core/util/PathUtils.java](url)

`package com.alibaba.jvm.sandbox.repeater.plugin.core.util;

import org.apache.commons.lang3.StringUtils;

import java.io.File;
import java.lang.reflect.Field;

/**
 * {@link PathUtils} 插件路径
 * <p>
 * repeater插件目录如下；如果使用默认路径，可以通过repeater-module.jar定位到 plugins & cfg 的位置
 * <p>
 *
 * ├── cfg
 * │   ├── repeater-logback.xml
 * │   └── repeater.properties
 * ├── plugins
 * │   ├── dubbo-plugin.jar
 * │   ├── http-plugin.jar
 * │   ├── ibatis-plugin.jar
 * │   ├── java-plugin.jar
 * │   └── mybatis-plugin.jar
 * ├── repeater-bootstrap.jar
 * └── repeater-module.jar
 * </p>
 *
 * @author zhaoyb1990
 */
public class PathUtils {

    /**
     * 获取插件绝对路径
     *
     * @return 插件绝对路径
     */
    public static String getPluginPath() {
        String modulePath = getModulePath();
        if (StringUtils.isEmpty(modulePath)) {
            return null;
        }
        return modulePath + "/plugins";
    }

    /**
     * 获取配置文件路径
     *
     * @return 配置绝对路径
     */
    public static String getConfigPath() {
        String modulePath = getModulePath();
        if (StringUtils.isEmpty(modulePath)) {
            return null;
        }
        return modulePath + "/cfg";
    }


    /**
     * 获取当前模块绝对路径
     *
     * @return 模块绝对路径
     */
    public static String getModulePath() {
        // moduleClassloader
        ClassLoader classLoader = PathUtils.class.getClassLoader();
        // moduleClassloader class
        Class<? extends ClassLoader> aClass = classLoader.getClass();
        try {
            Field field = aClass.getDeclaredField("moduleJarFile");
            boolean accessible = field.isAccessible();
            field.setAccessible(true);
            File file = (File) field.get(classLoader);
            field.setAccessible(accessible);
            return file.getParentFile().getAbsolutePath();
        } catch (Throwable e) {
            // ignore
        }
        return null;
    }
}`

**Comment by oldmanpushcart** [comment]
```java
"/plugins"
"/cfg"
```
看到了，那有点...去那个项目提吧，哈哈. @UchihaYong
