### ISSUE TITLE
waitingForBroken被中断没有走finally逻辑。

### ISSUE THREAD

**Issue by lqxandxl** [alibaba/jvm-sandbox#414]
我自己仿照写Module，之后使用sandbox命令执行命令。比如如下：
```
./sandbox.sh -p 4375 -d 'uaa-module/makeException?class=redis.clients.jedis.Jedis&method=lpush'
```

module中的一部分代码如下：
```
        try {
            //阻塞打印
            printer.waitingForBroken();
        }
        finally {
            //最后取消实验
            watcher.onUnWatched();
        }
```
但是我发现并不能在ctrl+c后，顺利执行 watcher.onUnWatched();方法。看起来只有在./sandbox.sh -p 4375 -S的时候才会执行finally的方法。看起来线程中断这里出了些问题？我想知道该如何进行排查？

**Comment by oldmanpushcart** [comment]
`printer.waitingForBroken();`有个特性，如果在这个过程中printer没有数据写入，`CTRL+C`后是不会被检查出broken的。这样设计的原因是：如果没broken的目的是为了静默（过程中printer无数据写入），那么其实你没必要这样去实现。
