### ISSUE TITLE
在方法拦截的时候，碰到了这个报错，没有什么头绪，大神有空帮忙过目

### ISSUE THREAD

**Issue by 54rtwo** [alibaba/jvm-sandbox#415]
default WARN  new instance class structure by using ASM failed, will return null. class=java/lang/constant/ConstantDesc;
java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9

**Comment by 54rtwo** [comment]
已处理！

**Comment by peterZhang000** [comment]
如何处理的?

**Comment by hs1515810** [comment]
@54rtwo  我也遇到这个问题了，方便说下怎么处理的吗
