### ISSUE TITLE
请问如何获取到attach的进程的classLoader呢？

### ISSUE THREAD

**Issue by settingsun1225** [alibaba/jvm-sandbox#42]

**Comment by dongchenxu** [comment]
attach的进程的ClassLoader是个啥？

**Comment by settingsun1225** [comment]
sandbox -p xxx 对应的应用的classloader；因为sandboxClassLoader 和应用的classLoader隔离了，有需求想要获取应用的classLoader

**Comment by dongchenxu** [comment]
目标应用可能会有多个ClassLoader，你无法确定你需要那个。
不过你可以轻松拿到本次调用的ClassLoader，在BEFORE_EVENT里面有

**Comment by settingsun1225** [comment]
O(∩_∩)O谢谢，解决了
