### ISSUE TITLE
能否对使用方屏蔽部署动作

### ISSUE THREAD

**Issue by JeanseLam** [alibaba/jvm-sandbox#422]
我有个诉求：
1.业务应用需要接入sandbox能力时，不需要显式的部署sandbox牵引程序
2.另外部署一个独立的web应用，让业务在可视化后台上传自己的moudel配置增强哪些目标应用的方法（希望在业务机器下载moudel，然后装载进sandbox，激活）
3.业务可以在可视化后台上线和下线moudle

请问老板们有没有什么方案能是实现上述能力。

**Comment by oldmanpushcart** [comment]
不需要显示的部署sandbox牵引程序，这个我是否可以理解为在maven中直接引用sandbox的一个引导jar包，然后自动完成sandbox的引导呢？

**Comment by 1229256875** [comment]
可以使用ssh远程投递，也可使用守护进程

**Comment by oldmanpushcart** [comment]
[挂载目标JVM](https://github.com/alibaba/jvm-sandbox/wiki/USER-QUICK-START#%E6%8C%82%E8%BD%BD%E7%9B%AE%E6%A0%87jvm) 这个章节是否能解答你的问题，不影响目标Java进程，也不需要目标Java进程重启。
