### ISSUE TITLE
sandbox load jvm failed : Unable to open socket file: target process not responding or HotSpot VM not loaded

### ISSUE THREAD

**Issue by lsh243725786** [alibaba/jvm-sandbox#423]
执行jvm-sandbox挂载应用：
![image](https://user-images.githubusercontent.com/38611763/236136128-2812879d-4f02-4456-b658-a2b7ed24f655.png)

应用失败日志：
![image](https://user-images.githubusercontent.com/38611763/236136716-a6003b9c-ffd9-4102-ba93-7741bb6bc02c.png)
![image](https://user-images.githubusercontent.com/38611763/236137234-28fddb2e-1369-4826-a75a-5edc8613cea3.png)

**Comment by lsh243725786** [comment]
目标应用是用docker部署的

**Comment by z529192557** [comment]
这并不是真正的失败日志，一般会在宿主应用的标准错误输出中（即日志里）打印相关的失败信息

**Comment by 54rtwo** [comment]
这个问题解决了吗？楼主，我也碰到同样的问题

**Comment by godtroop-github** [comment]
Have a look at, this may help you.
 
https://stackoverflow.com/questions/32198820/why-jstack-not-working-when-the-tmp-java-pidnum-socket-file-has-been-deleted
