### ISSUE TITLE
关于WebSocket的一些问题，希望沙箱可以支持实时数据交互

### ISSUE THREAD

**Issue by ShiningXu** [alibaba/jvm-sandbox#431]
咨询一下大佬。sandbox我看源码使用Jetty实现了WebSocket的通讯，但是被标记废弃了，想知道原因是什么，之前设计时如何考量的？

我们业务场景是，希望用沙箱做监控，对监控的数据投递的实时性和性能要求比较高，希望用SSE(Server-Sent-Eevent)或者WebSocket，可以直接在module里通过加@Command注解简单实现，和外部建立长连接投递数据。

这部分功能沙箱能否实现，还是说放到module层面比较合适？

希望大佬帮忙解答一下。

**Comment by oldmanpushcart** [comment]
module和外部的通讯，希望放到module层面比较合适。

sandbox使用jetty的原因是为了解决shell和core/module的通讯，但我个人非常后悔因为太重了。如果时间能重来我会采用telnet取代jetty，这也是我废弃websocket的原因。

**Comment by z529192557** [comment]
这种比较重module和外部通信的能力，希望模块能够自己来实现

**Comment by crytis** [comment]
> module和外部的通讯，希望放到module层面比较合适。
> 
> sandbox使用jetty的原因是为了解决shell和core/module的通讯，但我个人非常后悔因为太重了。如果时间能重来我会采用telnet取代jetty，这也是我废弃websocket的原因。

确实，现在亟需精简

**Comment by oldmanpushcart** [comment]
@crytis 已经精简不下去了，因为有兼容性承诺在。除非2.0
