### ISSUE TITLE
ls: cannot access (path: No such file or directory

### ISSUE THREAD

**Issue by longlife** [alibaba/jvm-sandbox#432]
按文档说明加载sandbox后，提示这个：ls: cannot access (path: No such file or directory
![image](https://github.com/alibaba/jvm-sandbox/assets/2416906/404049f4-b64e-427e-bd51-ac4c1313ee20)

不知道是哪里错了，但是好像加载上去了，应用运行日志里有sandbox的日志，只是一直打印这种异常：
`INFO  - 2023-07-03 19:17:01 [Schedule-Task-Processor-15175-com.sprucetec.pay.core.task.SignStatusStatusQuerySchedule-7987335785]com.alibaba.jvm.sandbox.module.debug.DebugLogExceptionModule.lambda$loadCompleted$0(DebugLogExceptionModule.java:40) -- org.apache.commons.dbcp.AbandonedTrace$AbandonedObjectException occur an exception: org.apache.commons.dbcp.AbandonedTrace$AbandonedObjectException: DBCP object created 1970-01-01 08:00:00 by the following code was never closed:`

**Comment by z529192557** [comment]
这种可能是在云原生环境下，多个容器pid是共享的，通过      lsof -p "${TARGET_JVM_PID}" | grep "/bin/java" | awk '{print $9}' |来获取虚拟机的目录，但是该目录不是多容器共享，导致ls 指定目录的报错

**Comment by oldmanpushcart** [comment]
@longlife 
我看你是用root账号，
[USER-FAQ](https://github.com/alibaba/jvm-sandbox/wiki/USER-FAQ)正好有这个问题的描述
```
沙箱不推荐在linux/unix系统下用root账号运行。如果必须要求root账号运行，则需要自行对sandbox.sh脚本做适当修改
```
