### ISSUE TITLE
在拦截点获取ThreadLocal内容为空

### ISSUE THREAD

**Issue by LiuYingjie-rd** [alibaba/jvm-sandbox#435]
场景是：业务代码已经通过ThreadLocal实现了traceId的异步传递，每次异步开启线程时，都可以在当前线程获取到traceId，实现流量的串联。 
但是当我在sandbox拦截点拦截到方法时，使用ThreadLocal.get()却取不到想要的traceId，但是debug后端代码却可以拿到，这是为什么呢？不都是同一个线程吗？
<img width="829" alt="image" src="https://github.com/alibaba/jvm-sandbox/assets/37172335/96c972d7-81a2-4765-ba2f-7ca22adb1c65">

**Comment by LiuYingjie-rd** [comment]
想到一种可能，是否是因为上面的Tracer类在业务代码和sandbox代码并非同一个类加载器加载的，所以对应不同的ThreadLocal?

**Comment by huangsir1** [comment]
这个问题你解决了吗，我也遇到了变量共享的问题
