### ISSUE TITLE
【 jvm-sandbox-repeater最新情况咨询】jvm-sandbox-repeater还在维护吗，最新master代码可否发版maven仓库

### ISSUE THREAD

**Issue by Reason94** [alibaba/jvm-sandbox#436]
jvm-sandbox-repeater这个项目里提交的issue没有人回复，借此宝地咨询问题，希望可以帮忙转交或者解答
1. jvm-sandbox-repeater项目还在维护吗？
2. 最新master代码，可否发布到maven仓库
3. 有支持JDK17的计划吗
感谢关注

**Comment by oldmanpushcart** [comment]
呃，这里是sandbox社区，不是repeater
