### ISSUE TITLE
使用ProcessController.returnImmediately(httpRequest) 返回自定义类失败，异常报错 null ，目标方法继续执行 

### ISSUE THREAD

**Issue by 1saacYing** [alibaba/jvm-sandbox#443]
想使用sandbox在 HookTarget类的report方法调用之前，并立即返回一个自定义的httpRequest对象，不运行原来的report方法，report本身返回的对象与httpRequest同一个类
但是启动后 ProcessController.returnImmediately(httpRequest) 抛出异常 异常信息为null， 原来report方法继续运行了

看了一下ProcessController.returnImmediately 的源码 好像就是抛出异常 那到底是怎么实现立即返回的呢？

        public class hook_jvm implements Module {
            @Resource
            private ModuleEventWatcher moduleEventWatcher;

            public void ceshiren(final Map<String, String> param) {
                new EventWatchBuilder(moduleEventWatcher)
                    .onClass("HookTarget")
                    .onBehavior("report")
                    .onWatch(new AdviceListener() {
                        @Override
                        protected void before(Advice advice) throws Throwable {
                            HttpRequest httpRequest = new HttpRequest();
                            ProcessController.returnImmediately(httpRequest);
                        }
                    });
            }
        }

**Comment by tangtangsara** [comment]
通过反射创建,  advice.classLoader.loadClass("包名. HttpRequest").newInstance()
直接声明和使用反射, 使用的classloader不同

**Comment by 1saacYing** [comment]
> 通过反射创建, advice.classLoader.loadClass("包名. HttpRequest").newInstance() 直接声明和使用反射, 使用的classloader不同
我用了反射代替直接创建的httpRequest，但是还是没有用
我try catch了一下 
HttpRequest httpRequest = new HttpRequest();
ProcessController.returnImmediately(httpRequest);
报错异常信息就是null，没有直接结束返回

**Comment by z529192557** [comment]
> httpRequest

正解

**Comment by z529192557** [comment]
> 通过反射创建, advice.classLoader.loadClass("包名. HttpRequest").newInstance() 直接声明和使用反射, 使用的classloader不同

这个是正解
