### ISSUE TITLE
可以拦截接口方法的调用吗？

### ISSUE THREAD

**Issue by yu120** [alibaba/jvm-sandbox#447]
我想拦截RocketMQ消费者的调用请求，拦截点为：org.apache.rocketmq.client.consumer.listener.MessageListenerConcurrently#consumeMessage。
因为业务中都是各自实现不同的MessageListenerConcurrently接口来完成业务的消费逻辑处理，所以无法明确到该拦截哪个实现类。因此尝试了，拦截MessageListenerConcurrently接口的consumeMessage方法调用，结果一直接收不到Event。所以想了解一下目前jvm-sandbox是否支持拦截接口方法的调用？

**Comment by ShiningXu** [comment]
支持，参考一下这个
![image](https://github.com/alibaba/jvm-sandbox/assets/15712567/d07674a0-e1cd-470b-b8cd-b4c6d8fcd44d)

https://github.com/alibaba/jvm-sandbox-repeater/pull/187/commits/24335e95b9f9955d45c59ce6d6f9983aa7324229#diff-36da76b4873b4d7d45bca3c4e2d098a34527db0b5d1b827184a84969e6bb7bac

**Comment by yu120** [comment]
@ShiningXu 请问一下，是jvm-sandbox哪个版本才能支持吗?或者还有其他什么特殊配置或要求吗？我把源码原封不动的贴进去，还是没有收到BeforeEvent事件呢

**Comment by yu120** [comment]
@ShiningXu 
![image](https://github.com/alibaba/jvm-sandbox/assets/15116235/420fbb5e-48d5-4d5e-88a7-7ae1c28c2a8f)
![image](https://github.com/alibaba/jvm-sandbox/assets/15116235/f41da728-0f8c-4d89-8b09-313994501135)
看上图，我在第一步打印了日志，都没发现拦截到了mq都调用事件

**Comment by yu120** [comment]
@ShiningXu 感谢，拦截到了

**Comment by SampsonJava** [comment]
如果我拦截的接口没有实现类呢, 可行吗

**Comment by ShiningXu** [comment]
> 如果我拦截的接口没有实现类呢, 可行吗

增强不会报错，就是拦截不到呗

**Comment by z529192557** [comment]
> 如果我拦截的接口没有实现类呢, 可行吗

增强不会报错，没有实现类的接口没有拦截的意义
