### ISSUE TITLE
请问有群吗, 二维码失效了

### ISSUE THREAD

**Issue by SampsonJava** [alibaba/jvm-sandbox#449]
同一个command下面的多个AdviceListener回调是不是同一个线程呢, 能不能用ThreadLocal传递数据, 如果不行的话, 有什么办法在多个onWatch之间传递数据呢, 本来想通过invokeId存储的, 但是我看invokeId每次触发不同的AdviceListener时候invokeId都不一样

**Comment by SampsonJava** [comment]
大佬帮忙更新一下群二维码哈

**Comment by oldmanpushcart** [comment]
@SampsonJava 每个AdviceListener的回调都和被监听方法的调用是同线程的，但不是一个command进行了多次watch，每个watch的AdviceListener都是同线程。

invokeId的确是全局分配的，即使同一个类#方法的同一个调用，在不同watch下，同一次调用大家拿到的都是同一个invokeId。

**Comment by oldmanpushcart** [comment]
群二维码已经更新，多谢提醒

**Comment by huangsir1** [comment]
又失效了，麻烦重新更新一下
