### ISSUE TITLE
监听before、return、throw事件的处理不是异步的吗？

### ISSUE THREAD

**Issue by yu120** [alibaba/jvm-sandbox#450]
针对录制流量时，希望针对before、return、throw事件解析请求参数、组装响应结果或异常时，可能存在较为耗时的操作，所以希望该事件是通过异步处理后才向外通知，但是目前跟踪了一下jvm-sandbox，没有找到异步化的逻辑。所以想确认一下jvm-sandbox针对上述3个事件都是没有异步处理的吗？也就是这3个逻辑是会增加代码的调用耗时的？是吗？

**Comment by z529192557** [comment]
不是异步的，是全同步化操作，是否要异步由使用者自己在事件处理代码中决定

**Comment by oldmanpushcart** [comment]
同时也提醒下，这几个Event都是被池化的对象，如果你想异步处理，请务必先clone出来，避免内容被污染。
