### ISSUE TITLE
afterCall或者afterCallReturning从advice获取返回值对象一直为null

### ISSUE THREAD

**Issue by dalianpai** [alibaba/jvm-sandbox#451]
afterCall或者afterCallReturning能触发，但是从advice获取返回值对象一直为null，这是为什么？我对A方法增强，其中调用B方法，且B方法有返回值，我想获取其返回值，应该怎么做

**Comment by z529192557** [comment]
你需要对B 增强，来获取B的返回值

**Comment by oldmanpushcart** [comment]
方法A调用方法B，你无法通过拦截方法A来获取方法B的返回值。推荐的做法是直接拦截方法B，嗯嗯。
如果你需要拦截从方法A调过来的方法B返回值，也是有解法，可以另外开课题讨论。
