### ISSUE TITLE
如何基于jvm-sandbox开发一个java agent

### ISSUE THREAD

**Issue by Mility** [alibaba/jvm-sandbox#453]
如果只想基于jvm-sandbox的module拦截功能来开发一个可以拦截任意指定类的java agent，且所有的依赖包都在同一个jar中，应该如何实现，有相应的demo吗？

**Comment by z529192557** [comment]
https://github.com/alibaba/jvm-sandbox/blob/master/sandbox-debug-module/src/main/java/com/alibaba/jvm/sandbox/module/debug/DebugWatchModule.java

这个是一个不错的例子，但是你可能需要考虑类和方法的配置从哪里读取，jar包的路径如何组织

**Comment by Mility** [comment]
> https://github.com/alibaba/jvm-sandbox/blob/master/sandbox-debug-module/src/main/java/com/alibaba/jvm/sandbox/module/debug/DebugWatchModule.java
> 
> 这个是一个不错的例子，但是你可能需要考虑类和方法的配置从哪里读取，jar包的路径如何组织

是啊，就是想问下有没有相应的开源工程啊

**Comment by ghost** [comment]
> > https://github.com/alibaba/jvm-sandbox/blob/master/sandbox-debug-module/src/main/java/com/alibaba/jvm/sandbox/module/debug/DebugWatchModule.java
> > 这个是一个不错的例子，但是你可能需要考虑类和方法的配置从哪里读取，jar包的路径如何组织
> 
> 是啊，就是想问下有没有相应的开源工程啊

https://github.com/alibaba/jvm-sandbox-repeater，这是个基于sandbox的做流量回放的开源项目，你可以借鉴它的一些结构和对sandbox的使用。
