### ISSUE TITLE
master 版本试用example 出问题

### ISSUE THREAD

**Issue by ddavidzhang** [alibaba/jvm-sandbox#454]
master版本有问题：
1、example 的 debug module 加载不全：./sandbox.sh -p xx -l 看不全
2、debug-trace 报错：java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils

直接现在的编译好的 1.4.0  版本无此问题，

**Comment by z529192557** [comment]
是不是用错了jar包，需要使用jar-withdependence 的那个jar包
