### ISSUE TITLE
JDK 17下的错误ClassCircularityError

### ISSUE THREAD

**Issue by fawen18** [alibaba/jvm-sandbox#456]
JDK17环境下，有概率发生如下错误，求解？JDK 17兼容情况是不是不完美？加上sandbox agent会报错，去掉后问题消失
<img width="978" alt="企业微信截图_4393a439-9b83-453f-aefd-9cefaf475845_副本" src="https://github.com/alibaba/jvm-sandbox/assets/13283368/4d97f52c-ae31-4f02-9166-6d10f62e0f78">

**Comment by z529192557** [comment]
堆栈中看不到sandbox相关的信息，日志里是否有更多的信息？和sandbox相关

**Comment by fawen18** [comment]
没有sandbox相关异常
