### ISSUE TITLE
快速开始中的钉钉二维码过期了

### ISSUE THREAD

**Issue by cnbeiyu** [alibaba/jvm-sandbox#457]
<img width="1601" alt="image" src="https://github.com/alibaba/jvm-sandbox/assets/31825675/43b1ceaa-5120-45de-b111-5e99c26e19bf">

**Comment by code-bez** [comment]
收到

**Comment by kerchiner** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cnbeiyu** [comment]
补充过期提示图片
![image](https://github.com/alibaba/jvm-sandbox/assets/31825675/f1112e7c-014f-4935-8b6a-6b323a7d0f54)

**Comment by oldmanpushcart** [comment]
@cnbeiyu 多谢提醒，已经更新最新的二维码。钉钉群分享二维码有效期只有一年，尴尬
