### ISSUE TITLE
attack docker中进程失败

### ISSUE THREAD

**Issue by ruokkkkk** [alibaba/jvm-sandbox#458]
![image](https://github.com/alibaba/jvm-sandbox/assets/7558849/5aea7c75-4ee1-49d2-b9c6-f02c4b71fa67)

**Comment by z529192557** [comment]
一般来说，这个不是sandbox自身的错误，sandbox依赖一个引导的java进程来向目标进程注入（attach）自己的agent，这个能力是JVM的标准能力
attach后，会试图打开 /tmp/{{pid}} 这个文件来完成引导进程和JVM进程的通信，目测是这个文件打开失败了，所以看一下，引导进程和目标进程是否能同时看到/tmp文件夹
