### ISSUE TITLE
使用反射，sandbox还是报错class redefinition failed: attempted to change the schema (add/remove fields)，请问这里应该怎么修改？

### ISSUE THREAD

**Issue by yyyfind** [alibaba/jvm-sandbox#459]
使用了两次反射，sandbox还是报错class redefinition failed: attempted to change the schema (add/remove fields)
![mocktest](https://github.com/alibaba/jvm-sandbox/assets/165645072/ee61c151-6746-4441-8c4a-c2f1612b46fb)

**Comment by code-bez** [comment]
收到

**Comment by z529192557** [comment]
从报错来看，和使用反射的次数没有关系，是有字节码工具试图为一个已存在的类修改（添加或者删除）属性，这种情况一般是进程中，多个agent冲突，check一下单个进程中是否有多个字节码工具存在

**Comment by Aresxue** [comment]
agent冲突了，看下有没有使用Skywalking这玩意不遵守jvm规范最容易报这个错了
