### ISSUE TITLE
如何对运行时生成的类进行增强？

### ISSUE THREAD

**Issue by foodjth** [alibaba/jvm-sandbox#460]
如何对运行时生成的类进行增强？
有一些类和方法是通过运行时候采用javassist动态生成的，或者通过new xxImpl来创建实现类。请问怎么解决？

**Comment by z529192557** [comment]
本身就是支持，如果你预先知道动态生成的类名字或者模式，可以通过指定类名的模式方式来增强满足一类命名规则的类，如果这些类本身会实现一些接口，可以通过对接口开启子类增强的方式进行增强
![image](https://github.com/alibaba/jvm-sandbox/assets/9245774/def4cca1-523b-4285-aa4e-295f8252211a)
