### ISSUE TITLE
1.4.0版本使用agent方式sandbox-module不生效，使用wiki步骤上的attach没问题是为什么

### ISSUE THREAD

**Issue by 1095071913** [alibaba/jvm-sandbox#476]
版本：2.4.0
attach：按照wiki上的流程修复损坏的钟是可以加载sandbox-module的
agent：java -javaagent:/jvm-sandbox/sandbox/lib/sandbox-agent.jar -jar patpet-test.jar 却无法加载sandbox-module，尝试过使用-Dsandbox.modules=/jvm-sandbox/sandbox/sandbox-module 却不生效

**Comment by code-bez** [comment]
收到

**Comment by kerchiner** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 1095071913** [comment]
@oldmanpushcart @kerchiner 可以帮助一下我吗 ？

**Comment by 1095071913** [comment]
已解决，通过实现LoadCompleted 初始化阶段加载代理，感谢钉钉的杜小琨大佬指点

**Comment by YLChen-007** [comment]
这样配置可以：

package com.alibaba.jvm.sandbox.demo;

import com.alibaba.jvm.sandbox.api.Information;
import com.alibaba.jvm.sandbox.api.Module;
import com.alibaba.jvm.sandbox.api.ProcessController;
import com.alibaba.jvm.sandbox.api.annotation.Command;
import com.alibaba.jvm.sandbox.api.listener.ext.Advice;
import com.alibaba.jvm.sandbox.api.listener.ext.AdviceListener;
import com.alibaba.jvm.sandbox.api.listener.ext.EventWatchBuilder;
import com.alibaba.jvm.sandbox.api.resource.ModuleEventWatcher;
import com.alibaba.jvm.sandbox.api.LoadCompleted;
import org.kohsuke.MetaInfServices;

import javax.annotation.Resource;

@MetaInfServices(Module.class)
@Information(id = "broken-clock-tinker")
public class BrokenClockTinkerModule implements Module, LoadCompleted {

    @Resource
    private ModuleEventWatcher moduleEventWatcher;

    @Override
    public void loadCompleted() {
        // 在模块加载完成时自动调用 repairCheckState 方法
        repairCheckState();
    }

    @Command("repairCheckState")
    public void repairCheckState() {
        new EventWatchBuilder(moduleEventWatcher)
                .onClass("com.taobao.demo.Clock")
                .onBehavior("checkState")
                .onWatch(new AdviceListener() {
                    @Override
                    protected void afterThrowing(Advice advice) throws Throwable {
                        ProcessController.returnImmediately(null);
                    }
                });
    }
}
