### ISSUE TITLE
call before 为何对调用两次？

### ISSUE THREAD

**Issue by zhenjia001** [alibaba/jvm-sandbox#50]
moduleEventWatcher.watch(

                // 匹配到Clock$BrokenClock#checkState()
                new NameRegexFilter("TestLambda", "main1"),

                // 监听THROWS事件并且改变原有方法抛出异常为正常返回
                new EventListener() {
                    @Override
                    public void onEvent(Event event) throws Throwable {
                        // 立即返回
                        System.out.println("aaaaaaaaaaaaaaaaaaaaaa");

                    }
                },
                // 指定监听的事件为抛出异常
                Event.Type.CALL_BEFORE

把例子稍微修改了一下，为何调用一次main1之前会调用两次这个call before的内容，有遇到过的吗

**Comment by zhenjia001** [comment]
难道是两个线程的问题？我试一下

**Comment by zhenjia001** [comment]
不对 ，单个线程也是打印了两次aaaaaaa，为何两次调用call before的内容？

**Comment by HashZhang** [comment]
你把Event的类型也打印出来，看看是不是坚挺了其他类型的Event

**Comment by zhenjia001** [comment]
@HashZhang 你说的这个情况确实有可能，我得找找在哪里能打印除了，监听了其他类型
