### ISSUE TITLE
稍微修改一下，在windows下也可以使用和调试了

### ISSUE THREAD

**Issue by zhenjia001** [alibaba/jvm-sandbox#51]
AgentLauncher就把substringBeforeLast修改了一下
windows下使用，用浏览器访问
http://127.0.0.1:5679/sandbox/default/module/http/broken-clock-tinker/repairCheckState
http://127.0.0.1:5679/sandbox/default/module/http/module-mgr/active?ids=broken-clock-tinker
可以使用了

**Comment by oldmanpushcart** [comment]
哦？提交下PR?
