### ISSUE TITLE
新版“脊柱”发布公告

### ISSUE THREAD

**Issue by oldmanpushcart** [alibaba/jvm-sandbox#55]
## 新版“脊柱”发布公告

> 同步群主的消息

年后SANDBOX将会发布新版本，代号：**脊柱**；

核心特性有

1. **插桩点增强**

   - **增加`AspectJ Pointcut expression`支持**

     > 可能会跳票
   
     将会精简实现Aspject的部分表达式语法，以后写埋点的时候将不用那么痛苦去实现Filter，直接拼写表达式即可。表达式可以参考：[Spring AOP AspectJ Pointcut Expressions With Examples](https://howtodoinjava.com/spring/spring-aop/writing-spring-aop-aspectj-pointcut-expressions-with-examples/)
   
   - **增加`Wildcard Pointcut expression`支持**

     进一步降低类匹配门槛
   
   - **增加对实现类、子类的支持**
   
     当前Filter只能过滤普通的Class，但实际在使用过程中往往实现类是匿名内部类或通过工厂模式所生产，无法拿到确定的类。
       

2. **API优化**

   相信各位已经在实现Sandbox-Module的时候被Event的处理折腾疯了，我也看到很多人在写例子的时候会踩到线程安全，递归调用等常见的坑，这些都是API不够友好所导致。
   
   很多人也私聊推荐我们采用bytebuddy的优美API，我们收到了。正在考虑中，希望集思广益～

3. **模块消息通讯**

   开源的最大价值在于给JVM-SANDOBX沉淀更多的模块。但沉淀的模块如果没有被复用的价值，那是不会有人期待公共模块的诞生，没有买卖就没有市场。
   
   最近也在看Pinpoint的代码，里面对我触动最大的就是沉淀了市面上常见的中间件的埋点代码。如何让更多的埋点事件沉淀到JVM-SANDBOX生态圈上，并进一步降低大家的门槛。
   
   我们的解决方案是增加模块之间的消息通讯，敬请期待～

4. **增加更多的Example**

   这个似乎是更多人的呼声了，但你希望增加那些EXAMPLE呢？时间毕竟有限，我可以选择投票最高的**2个**来实现。
   
   - 线上故障定位
   - 线上系统流控
   - 线上故障模拟
   - 方法请求录制和结果回放
   - 动态日志打印
   - 安全信息监测和脱敏

5. **合并大家的PR**

   以下PR将会被合并，非常感谢大家的努力参与
   
   1. [Code enhancement for #20](https://github.com/alibaba/jvm-sandbox/pull/26) Author：[caoenergy](https://github.com/caoenergy)
   1. [sandbox.log时区问题](https://github.com/alibaba/jvm-sandbox/pull/34) Author: [duxiaokang](https://github.com/duxiaokang)
   1. [获取参数的方式错误](https://github.com/alibaba/jvm-sandbox/pull/47) Author: [yangqiju](https://github.com/yangqiju)
   1. [fix SANDBOX_HOME on Windews #52](https://github.com/alibaba/jvm-sandbox/pull/53) Author: [Xlongshu](https://github.com/Xlongshu)

**Comment by fuyi-wang** [comment]
线上故障定位
线上故障模拟

**Comment by HashZhang** [comment]
线上故障定位
线上故障模拟

**Comment by liuyang054** [comment]
线上故障模拟
方法请求录制和结果回放

**Comment by QinFred2003** [comment]
方法请求录制和结果回放
线上故障定位

**Comment by chrischjh** [comment]
方法请求录制和结果回放
线上故障定位

**Comment by zhenjia001** [comment]
很期待，重点关注

**Comment by zhenjia001** [comment]
Pinpoint，已经很产品化，里面的埋点和可视化做的还是不错的

**Comment by zxddvp** [comment]
线上故障定位
方法请求录制和结果回放

**Comment by qipanliming** [comment]
方法请求录制和结果回放
动态日志打印

**Comment by oldmanpushcart** [comment]
已经发布：https://github.com/alibaba/jvm-sandbox/wiki/RELEASE-NOTES

|...|...|
|---|---|
|SANDBOX-API|1.0.14|
|SANDBOX容器|0.1.0.5|

相关教程：https://github.com/alibaba/jvm-sandbox/wiki/FOR-EXAMPLE

方法请求录制和结果回放，因为牵扯到其他团队，复杂度也不好做例子，所以暂时搁置。
