### ISSUE TITLE
执行.sandbox.sh时报错

### ISSUE THREAD

**Issue by liuyang054** [alibaba/jvm-sandbox#56]
安装成功，但是执行./sandbox.sh报错，具体报错信息如下，可能是什么原因了...
![_20180208230143_](https://user-images.githubusercontent.com/30917812/35979848-51ec859e-0d24-11e8-9360-3ef52b5c2561.jpg)

**Comment by oldmanpushcart** [comment]
老铁，最近你解决了没？

**Comment by liuyang054** [comment]
最后把主机的linux系统重装了，然后重新安装sandbox就好了，太奇怪了...

**Comment by dongchenxu** [comment]
怀疑你的环境变量不对，保持联系，再次出现问题反馈哦
