### ISSUE TITLE
用例过少

### ISSUE THREAD

**Issue by Wang-Jun-Chao** [alibaba/jvm-sandbox#58]
JVM Sandbox现在的用例非常少,可否供一些典型场景的用例供学习使用。这样子也方便项目推广。

**Comment by oldmanpushcart** [comment]
老铁说得没毛病，过年提供一篮子用例

**Comment by oldmanpushcart** [comment]
已经补充上用例，参考文章：https://github.com/alibaba/jvm-sandbox/wiki/FOR-EXAMPLE
