### ISSUE TITLE
怎么动态打印日志

### ISSUE THREAD

**Issue by tianxia007** [alibaba/jvm-sandbox#59]
怎么动态打印日志

**Comment by oldmanpushcart** [comment]
参考下这篇文章哦 https://github.com/alibaba/jvm-sandbox/wiki/FOR-EXAMPLE

**Comment by cabins** [comment]
https://github.com/alibaba/jvm-sandbox/blob/master/sandbox-debug-module/src/main/java/com/alibaba/jvm/sandbox/module/debug/DebugWatchModule.java

官方的这个例子中给出了动态打印日志的demo。
