### ISSUE TITLE
jvm-sandbox是否支持打成jar包，类似第三方依赖的方式引入项目

### ISSUE THREAD

**Issue by majianbin** [alibaba/jvm-sandbox#60]

**Comment by oldmanpushcart** [comment]
jvm-sandbox分容器和模块两个部分

- 容器本体是不支持打成jar包，但sandbox-core.jar可以跟随着以agent形式启动
- 模块API是在maven中心仓库

所以最好的方式是你的需求以自研module的形式研发，然后部署到sandbox容器中

**Comment by majianbin** [comment]
明白了，文档中已经指出可以使用agent的方式，我准备这样做：
1）服务部署前，在javaagent参数中指定sandbox-core.jar的目录未知。
2）服务部署时，下载自研module的jvm-sandbox到指定文件夹。
这样，在服务部署完成后就有了jvm-sandbox自研module的功能。

**Comment by oldmanpushcart** [comment]
一个模块的AOP拦截需要生效，需要有三个步骤

1. 模块加载
1. AOP插桩
1. 模块激活

其中模块激活的意思是，AOP代码插桩完成，但如果模块没有激活，EventListener是无法接收到任何事件的。只有模块激活之后，你指定的Event才会流转EventListener#onEvent()方法

模块默认是加载自动激活，但你可以手动配置模块在启动的时候默认不激活

```java
@MetaInfServices(Module.class)
@Information(id="my-example", isActiveOnLoad = false)
public class ExampleHelloModule implements Module, LoadCompleted {

    @Override
    public void loadCompleted() {

    }

}
```
