### ISSUE TITLE
需要一个机制更方便的复用别人已经写好的Watcher

### ISSUE THREAD

**Issue by oldmanpushcart** [alibaba/jvm-sandbox#62]
一些中间件的Watcher其实是可以复用的，但如何更好的让大家都进行复用，这里需要探索一个方案

**Comment by zhenjia001** [comment]
Watcher的概念？对应你得greys的啥？
我觉得Watcher 主要用到的是两类，1、查看具体值（已有变量和动态变量）2、统计（运行统计&根据条件统计）
按照这两类抽象两个watcher来做，个人理解

**Comment by oldmanpushcart** [comment]
greys的watch只能看不能改，sandbox的watch能篡改方法行为，不一样。

不过，你为了监控写了jdbc的watch，我为了流控，也写了jdbc的，我能否能复用你写的watch呢？毕竟自己分析jdbc的类好麻烦，想做到开箱即用：我不关心jdbc的类怎么拦截的，我只想用jdbc的增强类

**Comment by zhenjia001** [comment]
明白了，把别人的watch作为插件或者工具类来用
