### ISSUE TITLE
在Windows下利用git bash环境使用jvm-sandbox的方法

### ISSUE THREAD

**Issue by QinFred2003** [alibaba/jvm-sandbox#63]
现在手头没有Linux的环境，不过试验了下在windows的git bash的环境下，稍微注意也可以正常使用

安装阶段脚本：
  没有碰到任何问题，install.sh不需要更新. sandbox会安装到 C:\Users\USERNAME\\.opt\sandbox下

使用阶段脚本：
  碰到了两个小问题，不过基本可以绕过去。
  问题一:  JAVA_HOME环境变量的问题
  Windows上默认下载安装后，会放到 C:\Programe Files\...  下面，路径里面含有空格. sandbox.sh里面的引用JAVA_HOME时候没有加上引号，会导致解析失败。
  解决办法：
  把JVM安装在一个路径里面不含空格的目录里面比如: C:\Java\

  问题二：git bash环境里面的ps命令
  git bash 环境里面的ps aux 不能列出机器的所有进程，java进程无法显示，也就无法从进程中获得JVM的HOME和版本。
  解决办法：
  设置好环境变量后就行，不会再从已有的进程里面去寻找了

  问题三：如何知道JVM的进程ID
   解决办法： 简单。用windows的任务管理器查看具体进程的id就OK了

对于问题一，应该是个一般的问题，如果路径中含有空格就会失败，建议修复一下。

**Comment by QinFred2003** [comment]
Git bash 安装地址
https://gitforwindows.org/

**Comment by oldmanpushcart** [comment]
非常详尽的使用建议，非常感谢。
对于问题一，欢迎提交个PR，我会推动MERGE。虽然我们也可以修复，但我比较喜欢更多的人参与进来

**Comment by QinFred2003** [comment]
对问题二，google了下，可以用window下面的wmic 命令来查询.
wmic process get caption,commandline | grep java
输出：
javaw.exe                      "C:\Program Files\Java\jdk1.8.0_102\bin\javaw.exe" -Dfile.encoding=UTF-8 -classpath "C:\git\sandbox-fixclock\great.product\target\classes;C:\Users\fred\.m2\repository\javax\annotation\javax.annotation-api\1.2\javax.annotation-api-1.2.jar" com.sap.great.product.ClockStarter
