### ISSUE TITLE
大家有没有遇到启动工程中有groovy，切入sandbox后报错的问题

### ISSUE THREAD

**Issue by zhenjia001** [alibaba/jvm-sandbox#71]
在sandbox.log里有大量的
groovy.lang.MissingMethodException.getMessage(MissingMethodeException.java:59)
栈中主要是
com.alibaba.jvm.sandbox.module.debug.ExceptionLoggerModule$1.afterReturning(ExcepitonLoggerModule.java39)

**Comment by zhenjia001** [comment]
大量空指针异常
应该是debug module的问题

**Comment by oldmanpushcart** [comment]
能看下完整的异常堆栈么？

**Comment by dongchenxu** [comment]
同问，能给下完整的异常堆栈么
