### ISSUE TITLE
远程attach方式，报进程不存在

### ISSUE THREAD

**Issue by xiaolangnani** [alibaba/jvm-sandbox#73]
在目标机器启动：./bin/sandbox.sh -p 1823 -I 11.239.108.247
![image](https://user-images.githubusercontent.com/4570555/38065984-75df1c70-3338-11e8-8b2e-f6460f49a00c.png)

在远程机器启动：./bin/sandbox.sh -p 1823 -I 11.239.108.247
![image](https://user-images.githubusercontent.com/4570555/38066011-8e58ca6c-3338-11e8-8a08-5b5cd0072ebd.png)

**Comment by dongchenxu** [comment]
嗯，这个应该是我的WIKI/`usage`不够友好，你试试这样呢？

```shell
./bin/sandbox.sh -I 11.239.108.247 -P 38469
```

**Comment by jllamy** [comment]
请问这种方式解决了么？我这边没有解决，远程attach还是不行

**Comment by oldmanpushcart** [comment]
远程attach是必须远程的服务器先在本地完成sandbox加载操作的。因为需要对应的权限
