### ISSUE TITLE
沙箱容器版本更新是否需要重启目标应用

### ISSUE THREAD

**Issue by rumtipsy** [alibaba/jvm-sandbox#8]
如果目标应用已经被植入agent，而此时沙箱容器更新了版本，是不是必须要重启目标JVM才可以使用新版的沙箱容器？

**Comment by dongchenxu** [comment]
嗯，关于这个问题，你可以从[版本兼容性声明](https://github.com/alibaba/jvm-sandbox/wiki/RELEASE-NOTES#版本号兼容性声明)得到答案哈。

在兼容范围之内，你可以无需重启目标JVM即可完成容器动态升级

**Comment by rumtipsy** [comment]
好的，谢谢。另外加入交流群要什么条件？需要群主审核？

**Comment by dongchenxu** [comment]
当前凑人气，内部之前沟通有一个群，移动不了，外部使用的人不多，正在推广阶段。咨询也欢迎加群呀
