### ISSUE TITLE
望大家解答我一个关于类加载方面的困惑

### ISSUE THREAD

**Issue by liyebing** [alibaba/jvm-sandbox#80]
jvm-sandbox注入新的jar包，该包里面含有和目标jvm里相同的类，那么会造成目标jvm里面一个类文件被两个不同的类加载器加载，会生成两个class类吧？这对jvm应用的运行会造成什么影响吗？我学艺不精，这个问题一直没想明白，望赐教！

**Comment by yangsongbao** [comment]
不会。可以看下sandbox类加载器的图，sandbox对类加载器做了隔离，新注入的jar包和原先运行在jvm上的应用不在同一个classLoader里，不会影响。
