### ISSUE TITLE
依赖的jar的部署问题

### ISSUE THREAD

**Issue by jerryldh** [alibaba/jvm-sandbox#81]
watch module中依赖的class需要在哪边deploy

**Comment by oldmanpushcart** [comment]
没怎么明白你的问题，watch module是在debug模块中，将debug的jar包拷贝到user_lib中就好

**Comment by oldmanpushcart** [comment]
没怎么明白你的问题，watch module是在debug模块中，将debug的jar包拷贝到user_lib中就好

**Comment by oldmanpushcart** [comment]
没怎么明白你的问题，watch module是在debug模块中，将debug的jar包拷贝到user_lib中就好
