### ISSUE TITLE
例子JdbcLoggerModule.java需要强刷才能完成增强

### ISSUE THREAD

**Issue by chrischjh** [alibaba/jvm-sandbox#82]
1. 以agent方式启动成功，但刚开始没有任何class被增强

2. 目标应用相关方法被调用后，两个class被增强，但此时没有任何监听log被记录下来
    com/mysql/jdbc/CallableStatement
    com/mysql/jdbc/ConnectionImpl

3. 使用 -F 强刷后，总共5个class被增强：除了上面2个，又增加3个：
    com/mysql/jdbc/StatementImpl
    com/mysql/jdbc/ServerPreparedStatement
    com/mysql/jdbc/PreparedStatement

此时有jdbc的监听log产生，记录了sql的查询操作

**Comment by oldmanpushcart** [comment]
疑似BUG，我跟进下

**Comment by dongchenxu** [comment]
1.2.0版本废弃掉这个例子，没有考虑数据库连接池的情况

**Comment by dogourd** [comment]
> 疑似BUG，我跟进下



> 1.2.0版本废弃掉这个例子，没有考虑数据库连接池的情况


请问有没有找到后三个类没有被增强的原因？
