### ISSUE TITLE
改进：JVM-SANDBOX打印的日志和业务应用的日志分离

### ISSUE THREAD

**Issue by jackychee** [alibaba/jvm-sandbox#85]
每次执行JVM-SANDBOX的attatch操作和shutdown操作时，都会导致业务应用的日志中出现大量的JVM-SANDBOX的日志，这部分日志和业务应用日志无关，且容易给业务人员阅读日志带来不便和误解。希望后续版本能够优化下这块。

**Comment by oldmanpushcart** [comment]
大量的jvm-sandbox日志？呃，已经是独立的日志了呀...能提供下都是哪些日志混淆到业务日志中去了么？默认情况下是放在$HOME/logs/sandbox/sandbox.log

**Comment by jackychee** [comment]
这是我使用jvm-sandbox attach到一个jvm进程的时候，在业务日志中输出的内容。
![dml3 pfp3gk 4915idej i](https://user-images.githubusercontent.com/11421069/40814860-562e56b0-6575-11e8-9b61-a23aff6a7f37.png)

我的业务应用使用的是slf4j+log4j2日志框架，log4j2的root 配置如下：
`<root level="INFO">
          <appender-ref ref="BusinessFile"/>
       </root>`

我思考了下原因：是jvm-sandbox和目标应用都使用了slf4j这一日志框架有关。
有个问题（我还没验证），如果目标应用没有使用slf4j框架，jvm-sandbox应该会抛出class not found的异常吧（如果jvm-sandbox 对slf4j 的依赖是provided），也可能抛出类冲突相关的异常（如果jvm-sandbox 依赖的slf4j 和目标应用依赖的slf4j 版本不兼容）。

**Comment by oldmanpushcart** [comment]
@jackychee 截图看不到

**Comment by goody9807** [comment]
我也有同样的问题，我想把日志打印到自定义的一个路径，不知道怎么处理

**Comment by oldmanpushcart** [comment]
这个是个BUG，已经定位到了，周末发掉

**Comment by oldmanpushcart** [comment]
已经发布解决，版本1.0.16
