### ISSUE TITLE
改进：提供开关用于将运行期间修改的类的字节码保存到指定文件

### ISSUE THREAD

**Issue by jackychee** [alibaba/jvm-sandbox#86]
目的：帮助开发者了解自己开发的Module都对指定的类的字节码做了哪些改动，便于调试module。
实现机制：实现一个ClassFileTransformer，其作用是在transform方法中将接受到的字节码保存到文件中。然后将这个ClassFileTransformer添加到所有其他ClassFileTransformer 的最后执行。

**Comment by oldmanpushcart** [comment]
这个其实是有的，用于调试和测试字节码增强引擎环节。但当这个引擎稳定下来之后，这个类就删除掉了。增加这个类能帮助学习和了解sandbox的原理，但对真正使用而言，意义不大。

**Comment by jackychee** [comment]
是的，在开发自定义的module过程中，这个很有用。

> 这个其实是有的，用于调试和测试字节码增强引擎环节
具体见哪个类？
