### ISSUE TITLE
Bug: 通过-I -P指定host和端口不生效

### ISSUE THREAD

**Issue by DevotedTangLiu** [alibaba/jvm-sandbox#87]
CoreConfigure中使用"server.ip""server.port"作为key,
sh脚本和AgentLauncher中使用"ip""port"作为key,
在合并配置文件以及指令参数时，由于key不一致，导致jetty host / port不能正常获取。

**Comment by oldmanpushcart** [comment]
周末发版修复这个问题

**Comment by oldmanpushcart** [comment]
已经发布解决
