### ISSUE TITLE
能否获取到方法的参数名？

### ISSUE THREAD

**Issue by DevotedTangLiu** [alibaba/jvm-sandbox#89]
我在试图通过jvm-sandbox增强功能，记录我们的服务容器（tomcat）中的一些方法的请求参数，可以拿到参数的值和类型，但是无法拿到参数名。不知道有没有办法解决呢？

**Comment by dadiyang** [comment]
Java在编译的时候会把参数名抹除，所以编译之后是拿不到参数名的。
有两种方式获取参数名，都需要在编译时添加参数：

1. 生成调试信息，可以在编译时添加 -g 将方法参数名保留在 .class 文件的 LocalVariableTable 中，通过 asm 可以获取到。幸运的是，通过 **maven 编译都会默认添加 -g** 这个参数。
2. JDK8 之后，可以添加 -parameter 参数，然后就可以直接通过反射获取 Parameter，即 method.getParameters()，然后调用 Parameter 类提供的 getName 方法即可。

参考：[spring mvc如何实现参数名绑定](https://www.jianshu.com/p/2834d262fcc4)

**Comment by slowchen** [comment]
请问下参数名现在能获取了吗

**Comment by oldmanpushcart** [comment]
@slowchen 如果你的JVM是1.8，就可以的
