### ISSUE TITLE
Why don't we use `ClassLoader.registerAsParallelCapable()` in our classloader?

### ISSUE THREAD

**Issue by wind2412** [alibaba/jvm-sandbox#96]
As above.
Sandbox will load a lot of classes. If we open this feature, maybe it will make performance better.

**Comment by oldmanpushcart** [comment]
嗯，因为之前关注点在JDK6上（要兼容）所以忽略了这个1.7新增的API。之前并发加载类的诉求不常见，不过最近几次发现很多模块开发下来都不小，所以考虑试试

**Comment by oldmanpushcart** [comment]
再补充下，JVM-SANDBOX的类都是单线程加载，用不上`registerAsParallelCapable `
