### ISSUE TITLE
onCallBefore能否支持拿参数值？

### ISSUE THREAD

**Issue by haola334** [alibaba/jvm-sandbox#99]
onCallBefore能否支持拿参数值？
同时，也希望onCallBefore中能支持returnImmediately。
这样的好处在于，可以让一些方法本身不修改字节码，只在被调用的时候可以直接支持mock操作，这样一来，这个方法仅在必要时做了环绕，提升了transform的性能。此外，一些native方法也就可以支持mock了。

**Comment by oldmanpushcart** [comment]
这个问题很纠结，做是能做到，就是...

1. 如果目标是为了MOCK，那你光明正大去onBefore目标方法就好了
2. 如果目标是为了AOP掉native方法...这个可能考虑其他方案会更好点，感觉...虽然其他方案我们还在探讨

如果onCall系列的事件的确能通过改造拿到入参和返回值，就是性能上的折损真的很大，大到我宁可开辟一套新的事件来完成。
